// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="pixel_pack,hls_ip_2016_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg400-1,HLS_INPUT_CLOCK=7.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.941000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=812,HLS_SYN_LUT=655}" *)

module pixel_pack (
        ap_clk,
        ap_rst_n,
        in_stream_TDATA,
        in_stream_TVALID,
        in_stream_TREADY,
        in_stream_TUSER,
        in_stream_TLAST,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TREADY,
        out_stream_TUSER,
        out_stream_TLAST,
        s_axi_AXILiteS_AWVALID,
        s_axi_AXILiteS_AWREADY,
        s_axi_AXILiteS_AWADDR,
        s_axi_AXILiteS_WVALID,
        s_axi_AXILiteS_WREADY,
        s_axi_AXILiteS_WDATA,
        s_axi_AXILiteS_WSTRB,
        s_axi_AXILiteS_ARVALID,
        s_axi_AXILiteS_ARREADY,
        s_axi_AXILiteS_ARADDR,
        s_axi_AXILiteS_RVALID,
        s_axi_AXILiteS_RREADY,
        s_axi_AXILiteS_RDATA,
        s_axi_AXILiteS_RRESP,
        s_axi_AXILiteS_BVALID,
        s_axi_AXILiteS_BREADY,
        s_axi_AXILiteS_BRESP,
        control,
        ap_rst_n_control
);

parameter    ap_ST_st1_fsm_0 = 16'b1;
parameter    ap_ST_st2_fsm_1 = 16'b10;
parameter    ap_ST_st3_fsm_2 = 16'b100;
parameter    ap_ST_st4_fsm_3 = 16'b1000;
parameter    ap_ST_st5_fsm_4 = 16'b10000;
parameter    ap_ST_st6_fsm_5 = 16'b100000;
parameter    ap_ST_st7_fsm_6 = 16'b1000000;
parameter    ap_ST_st8_fsm_7 = 16'b10000000;
parameter    ap_ST_st9_fsm_8 = 16'b100000000;
parameter    ap_ST_st10_fsm_9 = 16'b1000000000;
parameter    ap_ST_st11_fsm_10 = 16'b10000000000;
parameter    ap_ST_pp4_stg0_fsm_11 = 16'b100000000000;
parameter    ap_ST_pp4_stg1_fsm_12 = 16'b1000000000000;
parameter    ap_ST_pp4_stg2_fsm_13 = 16'b10000000000000;
parameter    ap_ST_pp4_stg3_fsm_14 = 16'b100000000000000;
parameter    ap_ST_st18_fsm_15 = 16'b1000000000000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv32_C = 32'b1100;
parameter    ap_const_lv32_D = 32'b1101;
parameter    ap_const_lv32_E = 32'b1110;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv32_7 = 32'b111;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv32_9 = 32'b1001;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_3 = 32'b11;
parameter    C_S_AXI_AXILITES_DATA_WIDTH = 32;
parameter    ap_const_int64_8 = 8;
parameter    C_S_AXI_AXILITES_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_F = 32'b1111;
parameter    ap_const_lv32_10 = 32'b10000;
parameter    ap_const_lv32_17 = 32'b10111;
parameter    ap_const_lv32_18 = 32'b11000;
parameter    ap_const_lv32_1F = 32'b11111;
parameter    ap_const_lv32_2F = 32'b101111;
parameter    ap_const_lv32_30 = 32'b110000;
parameter    ap_const_lv32_47 = 32'b1000111;
parameter    ap_const_lv32_48 = 32'b1001000;
parameter    ap_const_lv32_5F = 32'b1011111;
parameter    ap_const_lv32_20 = 32'b100000;
parameter    ap_const_lv32_3F = 32'b111111;
parameter    ap_const_lv32_40 = 32'b1000000;

parameter C_S_AXI_AXILITES_WSTRB_WIDTH = (C_S_AXI_AXILITES_DATA_WIDTH / ap_const_int64_8);
parameter C_S_AXI_WSTRB_WIDTH = (C_S_AXI_DATA_WIDTH / ap_const_int64_8);

input   ap_clk;
input   ap_rst_n;
input  [23:0] in_stream_TDATA;
input   in_stream_TVALID;
output   in_stream_TREADY;
input  [0:0] in_stream_TUSER;
input  [0:0] in_stream_TLAST;
output  [31:0] out_stream_TDATA;
output   out_stream_TVALID;
input   out_stream_TREADY;
output  [0:0] out_stream_TUSER;
output  [0:0] out_stream_TLAST;
input   s_axi_AXILiteS_AWVALID;
output   s_axi_AXILiteS_AWREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1 : 0] s_axi_AXILiteS_AWADDR;
input   s_axi_AXILiteS_WVALID;
output   s_axi_AXILiteS_WREADY;
input  [C_S_AXI_AXILITES_DATA_WIDTH - 1 : 0] s_axi_AXILiteS_WDATA;
input  [C_S_AXI_AXILITES_WSTRB_WIDTH - 1 : 0] s_axi_AXILiteS_WSTRB;
input   s_axi_AXILiteS_ARVALID;
output   s_axi_AXILiteS_ARREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1 : 0] s_axi_AXILiteS_ARADDR;
output   s_axi_AXILiteS_RVALID;
input   s_axi_AXILiteS_RREADY;
output  [C_S_AXI_AXILITES_DATA_WIDTH - 1 : 0] s_axi_AXILiteS_RDATA;
output  [1:0] s_axi_AXILiteS_RRESP;
output   s_axi_AXILiteS_BVALID;
input   s_axi_AXILiteS_BREADY;
output  [1:0] s_axi_AXILiteS_BRESP;
input   control;
input   ap_rst_n_control;

reg in_stream_TREADY;
reg[31:0] out_stream_TDATA;
reg out_stream_TVALID;
reg[0:0] out_stream_TUSER;
reg[0:0] out_stream_TLAST;

reg    ap_rst_n_inv;
wire   [31:0] mode;
reg   [31:0] mode_0_data_reg;
reg    mode_0_vld_reg;
reg    mode_0_ack_out;
wire   [7:0] alpha_V;
reg   [7:0] alpha_V_0_data_reg;
reg    alpha_V_0_vld_reg;
reg    alpha_V_0_ack_out;
reg    in_stream_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [15:0] ap_CS_fsm;
reg    ap_sig_cseq_ST_pp4_stg0_fsm_11;
reg    ap_sig_89;
reg    ap_reg_ppiten_pp4_it0;
reg    ap_reg_ppiten_pp4_it1;
reg    ap_sig_cseq_ST_pp4_stg1_fsm_12;
reg    ap_sig_101;
reg   [0:0] in_stream_last_V_val_reg_945;
reg    ap_sig_cseq_ST_pp4_stg2_fsm_13;
reg    ap_sig_114;
reg   [0:0] last_2_1_reg_267;
reg    ap_sig_cseq_ST_pp4_stg3_fsm_14;
reg    ap_sig_126;
reg   [0:0] last_2_2_reg_307;
reg    ap_sig_cseq_ST_st11_fsm_10;
reg    ap_sig_138;
reg    ap_sig_cseq_ST_st7_fsm_6;
reg    ap_sig_146;
reg    ap_sig_cseq_ST_st8_fsm_7;
reg    ap_sig_154;
reg   [0:0] in_stream_last_V_val4_reg_911;
reg    ap_sig_cseq_ST_st9_fsm_8;
reg    ap_sig_165;
reg   [0:0] last_6_1_reg_173;
reg    ap_sig_cseq_ST_st10_fsm_9;
reg    ap_sig_176;
reg   [0:0] last_6_2_reg_203;
reg    ap_sig_cseq_ST_st5_fsm_4;
reg    ap_sig_187;
reg    ap_sig_cseq_ST_st6_fsm_5;
reg    ap_sig_195;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_203;
reg    ap_sig_cseq_ST_st4_fsm_3;
reg    ap_sig_211;
reg    out_stream_TDATA_blk_n;
reg    ap_rst_n_control_inv;
reg   [0:0] reg_429_1;
reg   [7:0] alpha_V_read_reg_847;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_304;
wire   [7:0] grp_fu_393_p4;
reg   [7:0] p_Result_s_30_reg_879;
wire   [7:0] grp_fu_403_p4;
reg   [7:0] p_Result_3_reg_884;
wire   [7:0] tmp_11_fu_444_p1;
reg   [7:0] tmp_11_reg_889;
wire   [15:0] tmp_8_fu_510_p1;
reg   [15:0] tmp_8_reg_897;
reg   [0:0] in_stream_user_V_val6_reg_905;
wire   [0:0] grp_fu_418_p1;
wire   [31:0] p_Result_9_fu_533_p5;
reg   [31:0] p_Result_9_reg_916;
wire   [0:0] user_3_1_fu_545_p2;
reg    ap_sig_323;
wire   [31:0] p_Result_33_1_fu_554_p5;
wire   [0:0] user_3_2_fu_565_p2;
reg    ap_sig_332;
wire   [31:0] p_Result_33_2_fu_575_p5;
reg    ap_sig_ioackin_out_stream_TREADY;
wire   [95:0] p_Result_7_fu_633_p5;
reg   [95:0] p_Result_7_reg_950;
reg   [3:0] tmp_13_fu_645_p4;
reg   [3:0] tmp_13_reg_956;
reg   [3:0] tmp_14_fu_655_p4;
reg   [3:0] tmp_14_reg_962;
wire   [95:0] p_Result_26_1_fu_665_p5;
reg    ap_sig_357;
reg   [3:0] tmp_16_fu_676_p4;
reg   [3:0] tmp_17_fu_685_p4;
wire   [95:0] p_Result_26_2_fu_694_p5;
reg    ap_sig_370;
reg   [3:0] tmp_19_fu_706_p4;
reg   [3:0] tmp_20_fu_716_p4;
reg   [31:0] p_Result_29_1_reg_998;
reg    ap_sig_382;
reg   [0:0] tmp_28_reg_1003;
reg   [0:0] tmp_29_reg_1008;
reg   [31:0] p_Result_29_2_reg_1013;
reg   [0:0] tmp_30_reg_1018;
reg   [0:0] tmp_31_reg_1023;
wire   [31:0] grp_read_fu_144_p2;
reg   [0:0] last_2_3_phi_fu_381_p4;
reg   [31:0] p_0464_2_1_reg_183;
reg   [0:0] user_1_1_reg_193;
reg   [31:0] p_0464_2_2_reg_214;
reg   [0:0] user_1_2_reg_224;
wire   [31:0] p_Result_33_3_fu_598_p5;
reg   [31:0] p_0464_2_3_phi_fu_237_p4;
reg    ap_sig_425;
reg   [0:0] last_6_3_phi_fu_248_p4;
wire   [0:0] user_3_3_fu_587_p2;
reg   [0:0] user_1_3_phi_fu_259_p4;
reg   [0:0] ap_reg_phiprechg_last_2_1_reg_267pp4_it0;
reg   [3:0] ap_reg_phiprechg_p_071_2_1_reg_277pp4_it0;
reg   [3:0] ap_reg_phiprechg_p_067_2_1_reg_287pp4_it0;
reg   [95:0] ap_reg_phiprechg_p_084_2_1_reg_297pp4_it0;
wire   [0:0] ap_reg_phiprechg_last_2_2_reg_307pp4_it0;
reg   [3:0] ap_reg_phiprechg_p_071_2_2_reg_318pp4_it0;
reg   [3:0] ap_reg_phiprechg_p_067_2_2_reg_328pp4_it0;
reg   [95:0] ap_reg_phiprechg_p_084_2_2_reg_338pp4_it0;
reg   [3:0] tmp_22_fu_739_p4;
wire   [3:0] ap_reg_phiprechg_p_071_2_3_reg_348pp4_it0;
reg   [3:0] p_071_2_3_phi_fu_351_p4;
reg   [3:0] tmp_23_fu_750_p4;
wire   [3:0] ap_reg_phiprechg_p_067_2_3_reg_358pp4_it0;
reg   [3:0] p_067_2_3_phi_fu_361_p4;
wire   [95:0] p_Result_26_3_fu_726_p5;
wire   [95:0] ap_reg_phiprechg_p_084_2_3_reg_368pp4_it0;
reg   [95:0] p_084_2_3_phi_fu_371_p4;
wire   [0:0] ap_reg_phiprechg_last_2_3_reg_378pp4_it0;
reg   [31:0] p_0464_s_fu_122;
reg   [95:0] p_084_s_fu_126;
reg   [3:0] p_067_s_fu_130;
reg   [3:0] p_071_s_fu_134;
wire   [31:0] p_Result_2_fu_498_p5;
wire   [31:0] p_Result_35_1_fu_518_p3;
wire   [31:0] p_Result_s_fu_616_p3;
wire   [31:0] tmp_25_fu_761_p1;
wire   [0:0] grp_fu_437_p2;
wire   [0:0] tmp_26_fu_766_p1;
reg    ap_reg_ioackin_out_stream_TREADY;
wire   [8:0] tmp_fu_448_p1;
wire   [8:0] tmp_1_fu_451_p1;
wire   [8:0] tmp_3_fu_461_p1;
wire   [8:0] tmp_4_fu_464_p1;
wire   [8:0] out_c1_V_fu_455_p2;
wire   [8:0] out_c2_V_fu_468_p2;
wire   [7:0] p_Result_8_fu_488_p4;
wire   [7:0] tmp_12_fu_484_p1;
wire   [7:0] p_Result_6_fu_474_p4;
wire   [15:0] tmp_10_fu_514_p1;
wire   [7:0] tmp_15_fu_529_p1;
wire   [7:0] tmp_18_fu_550_p1;
wire   [7:0] tmp_21_fu_571_p1;
wire   [7:0] tmp_24_fu_594_p1;
reg    ap_sig_cseq_ST_st18_fsm_15;
reg    ap_sig_814;
reg   [15:0] ap_NS_fsm;
reg    ap_sig_363;
reg    ap_sig_892;
reg    ap_sig_445;
reg    ap_sig_440;
reg    ap_sig_129;
reg    ap_sig_335;

// power-on initialization
initial begin
#0 mode_0_data_reg = 32'b00000000000000000000000000000000;
#0 mode_0_vld_reg = 1'b0;
#0 alpha_V_0_data_reg = 8'b00000000;
#0 alpha_V_0_vld_reg = 1'b0;
#0 ap_CS_fsm = 16'b1;
#0 ap_reg_ppiten_pp4_it0 = 1'b0;
#0 ap_reg_ppiten_pp4_it1 = 1'b0;
#0 ap_reg_ioackin_out_stream_TREADY = 1'b0;
end

pixel_pack_AXILiteS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_AXILITES_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_AXILITES_DATA_WIDTH ))
pixel_pack_AXILiteS_s_axi_U(
    .AWVALID(s_axi_AXILiteS_AWVALID),
    .AWREADY(s_axi_AXILiteS_AWREADY),
    .AWADDR(s_axi_AXILiteS_AWADDR),
    .WVALID(s_axi_AXILiteS_WVALID),
    .WREADY(s_axi_AXILiteS_WREADY),
    .WDATA(s_axi_AXILiteS_WDATA),
    .WSTRB(s_axi_AXILiteS_WSTRB),
    .ARVALID(s_axi_AXILiteS_ARVALID),
    .ARREADY(s_axi_AXILiteS_ARREADY),
    .ARADDR(s_axi_AXILiteS_ARADDR),
    .RVALID(s_axi_AXILiteS_RVALID),
    .RREADY(s_axi_AXILiteS_RREADY),
    .RDATA(s_axi_AXILiteS_RDATA),
    .RRESP(s_axi_AXILiteS_RRESP),
    .BVALID(s_axi_AXILiteS_BVALID),
    .BREADY(s_axi_AXILiteS_BREADY),
    .BRESP(s_axi_AXILiteS_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .mode(mode),
    .alpha_V(alpha_V),
    .clk(control),
    .rst(ap_rst_n_control_inv)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_out_stream_TREADY <= 1'b0;
    end else begin
        if ((((1'b1 == ap_sig_cseq_ST_st10_fsm_9) & ~((1'b0 == ap_sig_ioackin_out_stream_TREADY) | ap_sig_425)) | ((1'b1 == ap_reg_ppiten_pp4_it0) & (1'b1 == ap_sig_cseq_ST_pp4_stg3_fsm_14) & ~((1'b1 == ap_reg_ppiten_pp4_it0) & ((1'b0 == ap_sig_ioackin_out_stream_TREADY) | ap_sig_382))) | ((1'b1 == ap_sig_cseq_ST_st4_fsm_3) & ~((in_stream_TVALID == 1'b0) | (1'b0 == ap_sig_ioackin_out_stream_TREADY))) | ((1'b1 == ap_sig_cseq_ST_st6_fsm_5) & ~((in_stream_TVALID == 1'b0) | (1'b0 == ap_sig_ioackin_out_stream_TREADY))) | ((1'b1 == ap_sig_cseq_ST_st11_fsm_10) & ~((in_stream_TVALID == 1'b0) | (1'b0 == ap_sig_ioackin_out_stream_TREADY))) | ((1'b1 == ap_sig_cseq_ST_pp4_stg0_fsm_11) & (1'b1 == ap_reg_ppiten_pp4_it1) & ~(((1'b1 == ap_reg_ppiten_pp4_it0) & (in_stream_TVALID == 1'b0)) | ((1'b1 == ap_reg_ppiten_pp4_it1) & (1'b0 == ap_sig_ioackin_out_stream_TREADY)))) | ((1'b1 == ap_reg_ppiten_pp4_it1) & (1'b1 == ap_sig_cseq_ST_pp4_stg1_fsm_12) & ~(((1'b1 == ap_reg_ppiten_pp4_it1) & (1'b0 == ap_sig_ioackin_out_stream_TREADY)) | ((1'b1 == ap_reg_ppiten_pp4_it0) & ap_sig_357))))) begin
            ap_reg_ioackin_out_stream_TREADY <= 1'b0;
        end else if ((((1'b1 == ap_sig_cseq_ST_st4_fsm_3) & ~(in_stream_TVALID == 1'b0) & (1'b1 == out_stream_TREADY)) | ((1'b1 == ap_sig_cseq_ST_st6_fsm_5) & ~(in_stream_TVALID == 1'b0) & (1'b1 == out_stream_TREADY)) | ((1'b1 == ap_sig_cseq_ST_st10_fsm_9) & ~ap_sig_425 & (1'b1 == out_stream_TREADY)) | ((1'b1 == ap_sig_cseq_ST_st11_fsm_10) & ~(in_stream_TVALID == 1'b0) & (1'b1 == out_stream_TREADY)) | ((1'b1 == ap_reg_ppiten_pp4_it0) & (1'b1 == ap_sig_cseq_ST_pp4_stg3_fsm_14) & ~((1'b1 == ap_reg_ppiten_pp4_it0) & ap_sig_382) & (1'b1 == out_stream_TREADY)) | ((1'b1 == ap_sig_cseq_ST_pp4_stg0_fsm_11) & (1'b1 == ap_reg_ppiten_pp4_it1) & ~((1'b1 == ap_reg_ppiten_pp4_it0) & (in_stream_TVALID == 1'b0)) & (1'b1 == out_stream_TREADY)) | ((1'b1 == ap_reg_ppiten_pp4_it1) & (1'b1 == ap_sig_cseq_ST_pp4_stg1_fsm_12) & ~((1'b1 == ap_reg_ppiten_pp4_it0) & ap_sig_357) & (1'b1 == out_stream_TREADY)))) begin
            ap_reg_ioackin_out_stream_TREADY <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp4_it0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_pp4_stg3_fsm_14) & ~((1'b1 == ap_reg_ppiten_pp4_it0) & ((1'b0 == ap_sig_ioackin_out_stream_TREADY) | ap_sig_382)) & ~(1'b0 == last_2_3_phi_fu_381_p4))) begin
            ap_reg_ppiten_pp4_it0 <= 1'b0;
        end else if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (ap_const_lv32_0 == grp_read_fu_144_p2))) begin
            ap_reg_ppiten_pp4_it0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp4_it1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_pp4_stg3_fsm_14) & ~((1'b1 == ap_reg_ppiten_pp4_it0) & ((1'b0 == ap_sig_ioackin_out_stream_TREADY) | ap_sig_382)))) begin
            ap_reg_ppiten_pp4_it1 <= ap_reg_ppiten_pp4_it0;
        end else if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (ap_const_lv32_0 == grp_read_fu_144_p2))) begin
            ap_reg_ppiten_pp4_it1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_reg_ppiten_pp4_it0)) begin
        if (ap_sig_892) begin
            ap_reg_phiprechg_p_067_2_1_reg_287pp4_it0 <= tmp_14_fu_655_p4;
        end else if (ap_sig_363) begin
            ap_reg_phiprechg_p_067_2_1_reg_287pp4_it0 <= tmp_17_fu_685_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_sig_445) begin
        if (~(1'b0 == last_2_1_reg_267)) begin
            ap_reg_phiprechg_p_067_2_2_reg_328pp4_it0 <= ap_reg_phiprechg_p_067_2_1_reg_287pp4_it0;
        end else if ((1'b0 == last_2_1_reg_267)) begin
            ap_reg_phiprechg_p_067_2_2_reg_328pp4_it0 <= tmp_20_fu_716_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_reg_ppiten_pp4_it0)) begin
        if (ap_sig_892) begin
            ap_reg_phiprechg_p_071_2_1_reg_277pp4_it0 <= tmp_13_fu_645_p4;
        end else if (ap_sig_363) begin
            ap_reg_phiprechg_p_071_2_1_reg_277pp4_it0 <= tmp_16_fu_676_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_sig_445) begin
        if (~(1'b0 == last_2_1_reg_267)) begin
            ap_reg_phiprechg_p_071_2_2_reg_318pp4_it0 <= ap_reg_phiprechg_p_071_2_1_reg_277pp4_it0;
        end else if ((1'b0 == last_2_1_reg_267)) begin
            ap_reg_phiprechg_p_071_2_2_reg_318pp4_it0 <= tmp_19_fu_706_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_reg_ppiten_pp4_it0)) begin
        if (ap_sig_892) begin
            ap_reg_phiprechg_p_084_2_1_reg_297pp4_it0 <= p_Result_7_fu_633_p5;
        end else if (ap_sig_363) begin
            ap_reg_phiprechg_p_084_2_1_reg_297pp4_it0 <= p_Result_26_1_fu_665_p5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_sig_445) begin
        if (~(1'b0 == last_2_1_reg_267)) begin
            ap_reg_phiprechg_p_084_2_2_reg_338pp4_it0 <= ap_reg_phiprechg_p_084_2_1_reg_297pp4_it0;
        end else if ((1'b0 == last_2_1_reg_267)) begin
            ap_reg_phiprechg_p_084_2_2_reg_338pp4_it0 <= p_Result_26_2_fu_694_p5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_sig_440) begin
        if ((in_stream_last_V_val_reg_945 == 1'b0)) begin
            last_2_1_reg_267 <= in_stream_TLAST;
        end else if ((1'b1 == 1'b1)) begin
            last_2_1_reg_267 <= ap_reg_phiprechg_last_2_1_reg_267pp4_it0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_sig_445) begin
        if (~(1'b0 == last_2_1_reg_267)) begin
            last_2_2_reg_307 <= last_2_1_reg_267;
        end else if ((1'b0 == last_2_1_reg_267)) begin
            last_2_2_reg_307 <= in_stream_TLAST;
        end else if ((1'b1 == 1'b1)) begin
            last_2_2_reg_307 <= ap_reg_phiprechg_last_2_2_reg_307pp4_it0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_sig_335) begin
        if (~(1'b0 == last_6_1_reg_173)) begin
            last_6_2_reg_203 <= last_6_1_reg_173;
        end else if ((1'b0 == last_6_1_reg_173)) begin
            last_6_2_reg_203 <= in_stream_TLAST;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st7_fsm_6) & ~(in_stream_TVALID == 1'b0) & ~(1'b0 == grp_fu_418_p1))) begin
        p_0464_2_1_reg_183 <= p_Result_9_fu_533_p5;
    end else if (((1'b1 == ap_sig_cseq_ST_st8_fsm_7) & (1'b0 == in_stream_last_V_val4_reg_911) & ~ap_sig_323)) begin
        p_0464_2_1_reg_183 <= p_Result_33_1_fu_554_p5;
    end
end

always @ (posedge ap_clk) begin
    if (ap_sig_335) begin
        if (~(1'b0 == last_6_1_reg_173)) begin
            p_0464_2_2_reg_214 <= p_0464_2_1_reg_183;
        end else if ((1'b0 == last_6_1_reg_173)) begin
            p_0464_2_2_reg_214 <= p_Result_33_2_fu_575_p5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st7_fsm_6) & ~(in_stream_TVALID == 1'b0) & ~(1'b0 == grp_fu_418_p1))) begin
        user_1_1_reg_193 <= in_stream_TUSER;
    end else if (((1'b1 == ap_sig_cseq_ST_st8_fsm_7) & (1'b0 == in_stream_last_V_val4_reg_911) & ~ap_sig_323)) begin
        user_1_1_reg_193 <= user_3_1_fu_545_p2;
    end
end

always @ (posedge ap_clk) begin
    if (ap_sig_335) begin
        if (~(1'b0 == last_6_1_reg_173)) begin
            user_1_2_reg_224 <= user_1_1_reg_193;
        end else if ((1'b0 == last_6_1_reg_173)) begin
            user_1_2_reg_224 <= user_3_2_fu_565_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == 1'b1) & (1'b0 == alpha_V_0_vld_reg)) | ((1'b1 == 1'b1) & (1'b1 == alpha_V_0_vld_reg) & (1'b1 == alpha_V_0_ack_out)))) begin
        alpha_V_0_data_reg <= alpha_V;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        alpha_V_read_reg_847 <= alpha_V_0_data_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp4_stg0_fsm_11) & (1'b1 == ap_reg_ppiten_pp4_it0) & ~(((1'b1 == ap_reg_ppiten_pp4_it0) & (in_stream_TVALID == 1'b0)) | ((1'b1 == ap_reg_ppiten_pp4_it1) & (1'b0 == ap_sig_ioackin_out_stream_TREADY))) & ~(1'b0 == grp_fu_418_p1))) begin
        ap_reg_phiprechg_last_2_1_reg_267pp4_it0 <= in_stream_TLAST;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st7_fsm_6) & ~(in_stream_TVALID == 1'b0))) begin
        in_stream_last_V_val4_reg_911 <= in_stream_TLAST;
        in_stream_user_V_val6_reg_905 <= in_stream_TUSER;
        p_Result_9_reg_916 <= p_Result_9_fu_533_p5;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp4_stg0_fsm_11) & (1'b1 == ap_reg_ppiten_pp4_it0) & ~(((1'b1 == ap_reg_ppiten_pp4_it0) & (in_stream_TVALID == 1'b0)) | ((1'b1 == ap_reg_ppiten_pp4_it1) & (1'b0 == ap_sig_ioackin_out_stream_TREADY))))) begin
        in_stream_last_V_val_reg_945 <= in_stream_TLAST;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_sig_cseq_ST_st8_fsm_7) & (1'b0 == in_stream_last_V_val4_reg_911) & ~ap_sig_323) | ((1'b1 == ap_sig_cseq_ST_st7_fsm_6) & ~(in_stream_TVALID == 1'b0) & ~(1'b0 == grp_fu_418_p1)))) begin
        last_6_1_reg_173 <= in_stream_TLAST;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == 1'b1) & (1'b0 == mode_0_vld_reg)) | ((1'b1 == 1'b1) & (1'b1 == mode_0_vld_reg) & (1'b1 == mode_0_ack_out)))) begin
        mode_0_data_reg <= mode;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st10_fsm_9) & ~((1'b0 == ap_sig_ioackin_out_stream_TREADY) | ap_sig_425))) begin
        p_0464_s_fu_122 <= p_0464_2_3_phi_fu_237_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp4_it0) & (1'b1 == ap_sig_cseq_ST_pp4_stg3_fsm_14) & ~((1'b1 == ap_reg_ppiten_pp4_it0) & ((1'b0 == ap_sig_ioackin_out_stream_TREADY) | ap_sig_382)))) begin
        p_067_s_fu_130 <= p_067_2_3_phi_fu_361_p4;
        p_071_s_fu_134 <= p_071_2_3_phi_fu_351_p4;
        p_084_s_fu_126 <= p_084_2_3_phi_fu_371_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp4_stg3_fsm_14) & ~((1'b1 == ap_reg_ppiten_pp4_it0) & ((1'b0 == ap_sig_ioackin_out_stream_TREADY) | ap_sig_382)))) begin
        p_Result_29_1_reg_998 <= {{p_084_2_3_phi_fu_371_p4[ap_const_lv32_3F : ap_const_lv32_20]}};
        p_Result_29_2_reg_1013 <= {{p_084_2_3_phi_fu_371_p4[ap_const_lv32_5F : ap_const_lv32_40]}};
        tmp_28_reg_1003 <= p_071_2_3_phi_fu_351_p4[ap_const_lv32_1];
        tmp_29_reg_1008 <= p_067_2_3_phi_fu_361_p4[ap_const_lv32_2];
        tmp_30_reg_1018 <= p_071_2_3_phi_fu_351_p4[ap_const_lv32_2];
        tmp_31_reg_1023 <= p_067_2_3_phi_fu_361_p4[ap_const_lv32_3];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st3_fsm_2) & ~(in_stream_TVALID == 1'b0))) begin
        p_Result_3_reg_884 <= {{in_stream_TDATA[ap_const_lv32_17 : ap_const_lv32_10]}};
        p_Result_s_30_reg_879 <= {{in_stream_TDATA[ap_const_lv32_F : ap_const_lv32_8]}};
        tmp_11_reg_889 <= tmp_11_fu_444_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp4_stg0_fsm_11) & ~(((1'b1 == ap_reg_ppiten_pp4_it0) & (in_stream_TVALID == 1'b0)) | ((1'b1 == ap_reg_ppiten_pp4_it1) & (1'b0 == ap_sig_ioackin_out_stream_TREADY))))) begin
        p_Result_7_reg_950 <= p_Result_7_fu_633_p5;
        tmp_13_reg_956 <= tmp_13_fu_645_p4;
        tmp_14_reg_962 <= tmp_14_fu_655_p4;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_sig_cseq_ST_st3_fsm_2) & ~(in_stream_TVALID == 1'b0)) | ((1'b1 == ap_sig_cseq_ST_st5_fsm_4) & ~(in_stream_TVALID == 1'b0)))) begin
        reg_429_1 <= in_stream_TUSER;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st5_fsm_4) & ~(in_stream_TVALID == 1'b0))) begin
        tmp_8_reg_897 <= tmp_8_fu_510_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st18_fsm_15)) begin
        alpha_V_0_ack_out = 1'b1;
    end else begin
        alpha_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_89) begin
        ap_sig_cseq_ST_pp4_stg0_fsm_11 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp4_stg0_fsm_11 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_101) begin
        ap_sig_cseq_ST_pp4_stg1_fsm_12 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp4_stg1_fsm_12 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_114) begin
        ap_sig_cseq_ST_pp4_stg2_fsm_13 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp4_stg2_fsm_13 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_126) begin
        ap_sig_cseq_ST_pp4_stg3_fsm_14 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp4_stg3_fsm_14 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_176) begin
        ap_sig_cseq_ST_st10_fsm_9 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st10_fsm_9 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_138) begin
        ap_sig_cseq_ST_st11_fsm_10 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st11_fsm_10 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_814) begin
        ap_sig_cseq_ST_st18_fsm_15 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st18_fsm_15 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_304) begin
        ap_sig_cseq_ST_st2_fsm_1 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_203) begin
        ap_sig_cseq_ST_st3_fsm_2 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_211) begin
        ap_sig_cseq_ST_st4_fsm_3 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st4_fsm_3 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_187) begin
        ap_sig_cseq_ST_st5_fsm_4 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st5_fsm_4 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_195) begin
        ap_sig_cseq_ST_st6_fsm_5 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st6_fsm_5 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_146) begin
        ap_sig_cseq_ST_st7_fsm_6 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st7_fsm_6 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_154) begin
        ap_sig_cseq_ST_st8_fsm_7 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st8_fsm_7 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_165) begin
        ap_sig_cseq_ST_st9_fsm_8 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st9_fsm_8 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_reg_ioackin_out_stream_TREADY)) begin
        ap_sig_ioackin_out_stream_TREADY = out_stream_TREADY;
    end else begin
        ap_sig_ioackin_out_stream_TREADY = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_sig_cseq_ST_pp4_stg0_fsm_11) & (1'b1 == ap_reg_ppiten_pp4_it0)) | ((1'b1 == ap_reg_ppiten_pp4_it0) & (1'b1 == ap_sig_cseq_ST_pp4_stg1_fsm_12) & (in_stream_last_V_val_reg_945 == 1'b0)) | ((1'b1 == ap_reg_ppiten_pp4_it0) & (1'b1 == ap_sig_cseq_ST_pp4_stg2_fsm_13) & (1'b0 == last_2_1_reg_267)) | ((1'b1 == ap_reg_ppiten_pp4_it0) & (1'b1 == ap_sig_cseq_ST_pp4_stg3_fsm_14) & (1'b0 == last_2_2_reg_307)) | (1'b1 == ap_sig_cseq_ST_st11_fsm_10) | (1'b1 == ap_sig_cseq_ST_st7_fsm_6) | ((1'b1 == ap_sig_cseq_ST_st8_fsm_7) & (1'b0 == in_stream_last_V_val4_reg_911)) | ((1'b1 == ap_sig_cseq_ST_st9_fsm_8) & (1'b0 == last_6_1_reg_173)) | ((1'b1 == ap_sig_cseq_ST_st10_fsm_9) & (1'b0 == last_6_2_reg_203)) | (1'b1 == ap_sig_cseq_ST_st5_fsm_4) | (1'b1 == ap_sig_cseq_ST_st6_fsm_5) | (1'b1 == ap_sig_cseq_ST_st3_fsm_2) | (1'b1 == ap_sig_cseq_ST_st4_fsm_3))) begin
        in_stream_TDATA_blk_n = in_stream_TVALID;
    end else begin
        in_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_sig_cseq_ST_st3_fsm_2) & ~(in_stream_TVALID == 1'b0)) | ((1'b1 == ap_sig_cseq_ST_st5_fsm_4) & ~(in_stream_TVALID == 1'b0)) | ((1'b1 == ap_sig_cseq_ST_st7_fsm_6) & ~(in_stream_TVALID == 1'b0)) | ((1'b1 == ap_sig_cseq_ST_st8_fsm_7) & (1'b0 == in_stream_last_V_val4_reg_911) & ~ap_sig_323) | ((1'b1 == ap_sig_cseq_ST_st9_fsm_8) & (1'b0 == last_6_1_reg_173) & ~ap_sig_332) | ((1'b1 == ap_sig_cseq_ST_pp4_stg0_fsm_11) & (1'b1 == ap_reg_ppiten_pp4_it0) & ~(((1'b1 == ap_reg_ppiten_pp4_it0) & (in_stream_TVALID == 1'b0)) | ((1'b1 == ap_reg_ppiten_pp4_it1) & (1'b0 == ap_sig_ioackin_out_stream_TREADY)))) | ((1'b1 == ap_sig_cseq_ST_st10_fsm_9) & (1'b0 == last_6_2_reg_203) & ~((1'b0 == ap_sig_ioackin_out_stream_TREADY) | ap_sig_425)) | ((1'b1 == ap_reg_ppiten_pp4_it0) & (1'b1 == ap_sig_cseq_ST_pp4_stg1_fsm_12) & (in_stream_last_V_val_reg_945 == 1'b0) & ~(((1'b1 == ap_reg_ppiten_pp4_it1) & (1'b0 == ap_sig_ioackin_out_stream_TREADY)) | ((1'b1 == ap_reg_ppiten_pp4_it0) & ap_sig_357))) | ((1'b1 == ap_reg_ppiten_pp4_it0) & (1'b1 == ap_sig_cseq_ST_pp4_stg2_fsm_13) & (1'b0 == last_2_1_reg_267) & ~((1'b1 == ap_reg_ppiten_pp4_it0) & ap_sig_370)) | ((1'b1 == ap_reg_ppiten_pp4_it0) & (1'b1 == ap_sig_cseq_ST_pp4_stg3_fsm_14) & (1'b0 == last_2_2_reg_307) & ~((1'b1 == ap_reg_ppiten_pp4_it0) & ((1'b0 == ap_sig_ioackin_out_stream_TREADY) | ap_sig_382))) | ((1'b1 == ap_sig_cseq_ST_st4_fsm_3) & ~((in_stream_TVALID == 1'b0) | (1'b0 == ap_sig_ioackin_out_stream_TREADY))) | ((1'b1 == ap_sig_cseq_ST_st6_fsm_5) & ~((in_stream_TVALID == 1'b0) | (1'b0 == ap_sig_ioackin_out_stream_TREADY))) | ((1'b1 == ap_sig_cseq_ST_st11_fsm_10) & ~((in_stream_TVALID == 1'b0) | (1'b0 == ap_sig_ioackin_out_stream_TREADY))))) begin
        in_stream_TREADY = 1'b1;
    end else begin
        in_stream_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_129) begin
        if (~(1'b0 == last_2_2_reg_307)) begin
            last_2_3_phi_fu_381_p4 = last_2_2_reg_307;
        end else if ((1'b0 == last_2_2_reg_307)) begin
            last_2_3_phi_fu_381_p4 = in_stream_TLAST;
        end else begin
            last_2_3_phi_fu_381_p4 = ap_reg_phiprechg_last_2_3_reg_378pp4_it0;
        end
    end else begin
        last_2_3_phi_fu_381_p4 = ap_reg_phiprechg_last_2_3_reg_378pp4_it0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st10_fsm_9)) begin
        if (~(1'b0 == last_6_2_reg_203)) begin
            last_6_3_phi_fu_248_p4 = last_6_2_reg_203;
        end else if ((1'b0 == last_6_2_reg_203)) begin
            last_6_3_phi_fu_248_p4 = in_stream_TLAST;
        end else begin
            last_6_3_phi_fu_248_p4 = 'bx;
        end
    end else begin
        last_6_3_phi_fu_248_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st18_fsm_15)) begin
        mode_0_ack_out = 1'b1;
    end else begin
        mode_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp4_it1) & (1'b1 == ap_sig_cseq_ST_pp4_stg1_fsm_12) & ~((1'b1 == ap_reg_ppiten_pp4_it0) & ap_sig_357))) begin
        out_stream_TDATA = p_Result_29_2_reg_1013;
    end else if (((1'b1 == ap_sig_cseq_ST_pp4_stg0_fsm_11) & (1'b1 == ap_reg_ppiten_pp4_it1) & ~((1'b1 == ap_reg_ppiten_pp4_it0) & (in_stream_TVALID == 1'b0)))) begin
        out_stream_TDATA = p_Result_29_1_reg_998;
    end else if (((1'b1 == ap_reg_ppiten_pp4_it0) & (1'b1 == ap_sig_cseq_ST_pp4_stg3_fsm_14) & ~((1'b1 == ap_reg_ppiten_pp4_it0) & ap_sig_382))) begin
        out_stream_TDATA = tmp_25_fu_761_p1;
    end else if (((1'b1 == ap_sig_cseq_ST_st11_fsm_10) & ~(in_stream_TVALID == 1'b0))) begin
        out_stream_TDATA = p_Result_s_fu_616_p3;
    end else if (((1'b1 == ap_sig_cseq_ST_st10_fsm_9) & ~ap_sig_425)) begin
        out_stream_TDATA = p_0464_2_3_phi_fu_237_p4;
    end else if (((1'b1 == ap_sig_cseq_ST_st6_fsm_5) & ~(in_stream_TVALID == 1'b0))) begin
        out_stream_TDATA = p_Result_35_1_fu_518_p3;
    end else if (((1'b1 == ap_sig_cseq_ST_st4_fsm_3) & ~(in_stream_TVALID == 1'b0))) begin
        out_stream_TDATA = p_Result_2_fu_498_p5;
    end else begin
        out_stream_TDATA = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp4_it0) & (1'b1 == ap_sig_cseq_ST_pp4_stg3_fsm_14)) | (1'b1 == ap_sig_cseq_ST_st11_fsm_10) | (1'b1 == ap_sig_cseq_ST_st10_fsm_9) | (1'b1 == ap_sig_cseq_ST_st6_fsm_5) | (1'b1 == ap_sig_cseq_ST_st4_fsm_3) | ((1'b1 == ap_sig_cseq_ST_pp4_stg0_fsm_11) & (1'b1 == ap_reg_ppiten_pp4_it1)) | ((1'b1 == ap_reg_ppiten_pp4_it1) & (1'b1 == ap_sig_cseq_ST_pp4_stg1_fsm_12)))) begin
        out_stream_TDATA_blk_n = out_stream_TREADY;
    end else begin
        out_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp4_it1) & (1'b1 == ap_sig_cseq_ST_pp4_stg1_fsm_12) & ~((1'b1 == ap_reg_ppiten_pp4_it0) & ap_sig_357))) begin
        out_stream_TLAST = tmp_31_reg_1023;
    end else if (((1'b1 == ap_sig_cseq_ST_pp4_stg0_fsm_11) & (1'b1 == ap_reg_ppiten_pp4_it1) & ~((1'b1 == ap_reg_ppiten_pp4_it0) & (in_stream_TVALID == 1'b0)))) begin
        out_stream_TLAST = tmp_29_reg_1008;
    end else if (((1'b1 == ap_reg_ppiten_pp4_it0) & (1'b1 == ap_sig_cseq_ST_pp4_stg3_fsm_14) & ~((1'b1 == ap_reg_ppiten_pp4_it0) & ap_sig_382))) begin
        out_stream_TLAST = p_067_2_3_phi_fu_361_p4[ap_const_lv32_1];
    end else if (((1'b1 == ap_sig_cseq_ST_st10_fsm_9) & ~ap_sig_425)) begin
        out_stream_TLAST = last_6_3_phi_fu_248_p4;
    end else if ((((1'b1 == ap_sig_cseq_ST_st4_fsm_3) & ~(in_stream_TVALID == 1'b0)) | ((1'b1 == ap_sig_cseq_ST_st6_fsm_5) & ~(in_stream_TVALID == 1'b0)) | ((1'b1 == ap_sig_cseq_ST_st11_fsm_10) & ~(in_stream_TVALID == 1'b0)))) begin
        out_stream_TLAST = in_stream_TLAST;
    end else begin
        out_stream_TLAST = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp4_it1) & (1'b1 == ap_sig_cseq_ST_pp4_stg1_fsm_12) & ~((1'b1 == ap_reg_ppiten_pp4_it0) & ap_sig_357))) begin
        out_stream_TUSER = tmp_30_reg_1018;
    end else if (((1'b1 == ap_sig_cseq_ST_pp4_stg0_fsm_11) & (1'b1 == ap_reg_ppiten_pp4_it1) & ~((1'b1 == ap_reg_ppiten_pp4_it0) & (in_stream_TVALID == 1'b0)))) begin
        out_stream_TUSER = tmp_28_reg_1003;
    end else if (((1'b1 == ap_reg_ppiten_pp4_it0) & (1'b1 == ap_sig_cseq_ST_pp4_stg3_fsm_14) & ~((1'b1 == ap_reg_ppiten_pp4_it0) & ap_sig_382))) begin
        out_stream_TUSER = tmp_26_fu_766_p1;
    end else if (((1'b1 == ap_sig_cseq_ST_st11_fsm_10) & ~(in_stream_TVALID == 1'b0))) begin
        out_stream_TUSER = in_stream_TUSER;
    end else if (((1'b1 == ap_sig_cseq_ST_st10_fsm_9) & ~ap_sig_425)) begin
        out_stream_TUSER = user_1_3_phi_fu_259_p4;
    end else if ((((1'b1 == ap_sig_cseq_ST_st4_fsm_3) & ~(in_stream_TVALID == 1'b0)) | ((1'b1 == ap_sig_cseq_ST_st6_fsm_5) & ~(in_stream_TVALID == 1'b0)))) begin
        out_stream_TUSER = grp_fu_437_p2;
    end else begin
        out_stream_TUSER = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_sig_cseq_ST_st4_fsm_3) & ~(in_stream_TVALID == 1'b0) & (1'b0 == ap_reg_ioackin_out_stream_TREADY)) | ((1'b1 == ap_sig_cseq_ST_st6_fsm_5) & ~(in_stream_TVALID == 1'b0) & (1'b0 == ap_reg_ioackin_out_stream_TREADY)) | ((1'b1 == ap_sig_cseq_ST_st10_fsm_9) & ~ap_sig_425 & (1'b0 == ap_reg_ioackin_out_stream_TREADY)) | ((1'b1 == ap_sig_cseq_ST_st11_fsm_10) & ~(in_stream_TVALID == 1'b0) & (1'b0 == ap_reg_ioackin_out_stream_TREADY)) | ((1'b1 == ap_reg_ppiten_pp4_it0) & (1'b1 == ap_sig_cseq_ST_pp4_stg3_fsm_14) & ~((1'b1 == ap_reg_ppiten_pp4_it0) & ap_sig_382) & (1'b0 == ap_reg_ioackin_out_stream_TREADY)) | ((1'b1 == ap_sig_cseq_ST_pp4_stg0_fsm_11) & (1'b1 == ap_reg_ppiten_pp4_it1) & ~((1'b1 == ap_reg_ppiten_pp4_it0) & (in_stream_TVALID == 1'b0)) & (1'b0 == ap_reg_ioackin_out_stream_TREADY)) | ((1'b1 == ap_reg_ppiten_pp4_it1) & (1'b1 == ap_sig_cseq_ST_pp4_stg1_fsm_12) & ~((1'b1 == ap_reg_ppiten_pp4_it0) & ap_sig_357) & (1'b0 == ap_reg_ioackin_out_stream_TREADY)))) begin
        out_stream_TVALID = 1'b1;
    end else begin
        out_stream_TVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st10_fsm_9)) begin
        if (~(1'b0 == last_6_2_reg_203)) begin
            p_0464_2_3_phi_fu_237_p4 = p_0464_2_2_reg_214;
        end else if ((1'b0 == last_6_2_reg_203)) begin
            p_0464_2_3_phi_fu_237_p4 = p_Result_33_3_fu_598_p5;
        end else begin
            p_0464_2_3_phi_fu_237_p4 = 'bx;
        end
    end else begin
        p_0464_2_3_phi_fu_237_p4 = 'bx;
    end
end

always @ (*) begin
    if (ap_sig_129) begin
        if (~(1'b0 == last_2_2_reg_307)) begin
            p_067_2_3_phi_fu_361_p4 = ap_reg_phiprechg_p_067_2_2_reg_328pp4_it0;
        end else if ((1'b0 == last_2_2_reg_307)) begin
            p_067_2_3_phi_fu_361_p4 = tmp_23_fu_750_p4;
        end else begin
            p_067_2_3_phi_fu_361_p4 = ap_reg_phiprechg_p_067_2_3_reg_358pp4_it0;
        end
    end else begin
        p_067_2_3_phi_fu_361_p4 = ap_reg_phiprechg_p_067_2_3_reg_358pp4_it0;
    end
end

always @ (*) begin
    if (ap_sig_129) begin
        if (~(1'b0 == last_2_2_reg_307)) begin
            p_071_2_3_phi_fu_351_p4 = ap_reg_phiprechg_p_071_2_2_reg_318pp4_it0;
        end else if ((1'b0 == last_2_2_reg_307)) begin
            p_071_2_3_phi_fu_351_p4 = tmp_22_fu_739_p4;
        end else begin
            p_071_2_3_phi_fu_351_p4 = ap_reg_phiprechg_p_071_2_3_reg_348pp4_it0;
        end
    end else begin
        p_071_2_3_phi_fu_351_p4 = ap_reg_phiprechg_p_071_2_3_reg_348pp4_it0;
    end
end

always @ (*) begin
    if (ap_sig_129) begin
        if (~(1'b0 == last_2_2_reg_307)) begin
            p_084_2_3_phi_fu_371_p4 = ap_reg_phiprechg_p_084_2_2_reg_338pp4_it0;
        end else if ((1'b0 == last_2_2_reg_307)) begin
            p_084_2_3_phi_fu_371_p4 = p_Result_26_3_fu_726_p5;
        end else begin
            p_084_2_3_phi_fu_371_p4 = ap_reg_phiprechg_p_084_2_3_reg_368pp4_it0;
        end
    end else begin
        p_084_2_3_phi_fu_371_p4 = ap_reg_phiprechg_p_084_2_3_reg_368pp4_it0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st10_fsm_9)) begin
        if (~(1'b0 == last_6_2_reg_203)) begin
            user_1_3_phi_fu_259_p4 = user_1_2_reg_224;
        end else if ((1'b0 == last_6_2_reg_203)) begin
            user_1_3_phi_fu_259_p4 = user_3_3_fu_587_p2;
        end else begin
            user_1_3_phi_fu_259_p4 = 'bx;
        end
    end else begin
        user_1_3_phi_fu_259_p4 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : begin
            ap_NS_fsm = ap_ST_st2_fsm_1;
        end
        ap_ST_st2_fsm_1 : begin
            if ((ap_const_lv32_0 == grp_read_fu_144_p2)) begin
                ap_NS_fsm = ap_ST_pp4_stg0_fsm_11;
            end else if ((ap_const_lv32_2 == grp_read_fu_144_p2)) begin
                ap_NS_fsm = ap_ST_st7_fsm_6;
            end else if ((~(ap_const_lv32_0 == grp_read_fu_144_p2) & ~(ap_const_lv32_1 == grp_read_fu_144_p2) & ~(ap_const_lv32_2 == grp_read_fu_144_p2) & ~(ap_const_lv32_3 == grp_read_fu_144_p2) & ~(ap_const_lv32_4 == grp_read_fu_144_p2))) begin
                ap_NS_fsm = ap_ST_st18_fsm_15;
            end else if ((ap_const_lv32_1 == grp_read_fu_144_p2)) begin
                ap_NS_fsm = ap_ST_st11_fsm_10;
            end else if ((ap_const_lv32_3 == grp_read_fu_144_p2)) begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end else begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end
        end
        ap_ST_st3_fsm_2 : begin
            if (~(in_stream_TVALID == 1'b0)) begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end else begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end
        end
        ap_ST_st4_fsm_3 : begin
            if (((1'b0 == grp_fu_418_p1) & ~((in_stream_TVALID == 1'b0) | (1'b0 == ap_sig_ioackin_out_stream_TREADY)))) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else if ((~(1'b0 == grp_fu_418_p1) & ~((in_stream_TVALID == 1'b0) | (1'b0 == ap_sig_ioackin_out_stream_TREADY)))) begin
                ap_NS_fsm = ap_ST_st18_fsm_15;
            end else begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end
        end
        ap_ST_st5_fsm_4 : begin
            if (~(in_stream_TVALID == 1'b0)) begin
                ap_NS_fsm = ap_ST_st6_fsm_5;
            end else begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end
        end
        ap_ST_st6_fsm_5 : begin
            if (((1'b0 == grp_fu_418_p1) & ~((in_stream_TVALID == 1'b0) | (1'b0 == ap_sig_ioackin_out_stream_TREADY)))) begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end else if ((~(1'b0 == grp_fu_418_p1) & ~((in_stream_TVALID == 1'b0) | (1'b0 == ap_sig_ioackin_out_stream_TREADY)))) begin
                ap_NS_fsm = ap_ST_st18_fsm_15;
            end else begin
                ap_NS_fsm = ap_ST_st6_fsm_5;
            end
        end
        ap_ST_st7_fsm_6 : begin
            if (~(in_stream_TVALID == 1'b0)) begin
                ap_NS_fsm = ap_ST_st8_fsm_7;
            end else begin
                ap_NS_fsm = ap_ST_st7_fsm_6;
            end
        end
        ap_ST_st8_fsm_7 : begin
            if (~ap_sig_323) begin
                ap_NS_fsm = ap_ST_st9_fsm_8;
            end else begin
                ap_NS_fsm = ap_ST_st8_fsm_7;
            end
        end
        ap_ST_st9_fsm_8 : begin
            if (~ap_sig_332) begin
                ap_NS_fsm = ap_ST_st10_fsm_9;
            end else begin
                ap_NS_fsm = ap_ST_st9_fsm_8;
            end
        end
        ap_ST_st10_fsm_9 : begin
            if ((~((1'b0 == ap_sig_ioackin_out_stream_TREADY) | ap_sig_425) & (1'b0 == last_6_3_phi_fu_248_p4))) begin
                ap_NS_fsm = ap_ST_st7_fsm_6;
            end else if ((~((1'b0 == ap_sig_ioackin_out_stream_TREADY) | ap_sig_425) & ~(1'b0 == last_6_3_phi_fu_248_p4))) begin
                ap_NS_fsm = ap_ST_st18_fsm_15;
            end else begin
                ap_NS_fsm = ap_ST_st10_fsm_9;
            end
        end
        ap_ST_st11_fsm_10 : begin
            if (((1'b0 == grp_fu_418_p1) & ~((in_stream_TVALID == 1'b0) | (1'b0 == ap_sig_ioackin_out_stream_TREADY)))) begin
                ap_NS_fsm = ap_ST_st11_fsm_10;
            end else if ((~(1'b0 == grp_fu_418_p1) & ~((in_stream_TVALID == 1'b0) | (1'b0 == ap_sig_ioackin_out_stream_TREADY)))) begin
                ap_NS_fsm = ap_ST_st18_fsm_15;
            end else begin
                ap_NS_fsm = ap_ST_st11_fsm_10;
            end
        end
        ap_ST_pp4_stg0_fsm_11 : begin
            if (~(((1'b1 == ap_reg_ppiten_pp4_it0) & (in_stream_TVALID == 1'b0)) | ((1'b1 == ap_reg_ppiten_pp4_it1) & (1'b0 == ap_sig_ioackin_out_stream_TREADY)))) begin
                ap_NS_fsm = ap_ST_pp4_stg1_fsm_12;
            end else begin
                ap_NS_fsm = ap_ST_pp4_stg0_fsm_11;
            end
        end
        ap_ST_pp4_stg1_fsm_12 : begin
            if ((~(((1'b1 == ap_reg_ppiten_pp4_it1) & (1'b0 == ap_sig_ioackin_out_stream_TREADY)) | ((1'b1 == ap_reg_ppiten_pp4_it0) & ap_sig_357)) & ~((1'b1 == ap_reg_ppiten_pp4_it1) & (1'b1 == ap_sig_cseq_ST_pp4_stg1_fsm_12) & ~(((1'b1 == ap_reg_ppiten_pp4_it1) & (1'b0 == ap_sig_ioackin_out_stream_TREADY)) | ((1'b1 == ap_reg_ppiten_pp4_it0) & ap_sig_357)) & ~(1'b1 == ap_reg_ppiten_pp4_it0)))) begin
                ap_NS_fsm = ap_ST_pp4_stg2_fsm_13;
            end else if (((1'b1 == ap_reg_ppiten_pp4_it1) & (1'b1 == ap_sig_cseq_ST_pp4_stg1_fsm_12) & ~(((1'b1 == ap_reg_ppiten_pp4_it1) & (1'b0 == ap_sig_ioackin_out_stream_TREADY)) | ((1'b1 == ap_reg_ppiten_pp4_it0) & ap_sig_357)) & ~(1'b1 == ap_reg_ppiten_pp4_it0))) begin
                ap_NS_fsm = ap_ST_st18_fsm_15;
            end else begin
                ap_NS_fsm = ap_ST_pp4_stg1_fsm_12;
            end
        end
        ap_ST_pp4_stg2_fsm_13 : begin
            if (~((1'b1 == ap_reg_ppiten_pp4_it0) & ap_sig_370)) begin
                ap_NS_fsm = ap_ST_pp4_stg3_fsm_14;
            end else begin
                ap_NS_fsm = ap_ST_pp4_stg2_fsm_13;
            end
        end
        ap_ST_pp4_stg3_fsm_14 : begin
            if (~((1'b1 == ap_reg_ppiten_pp4_it0) & ((1'b0 == ap_sig_ioackin_out_stream_TREADY) | ap_sig_382))) begin
                ap_NS_fsm = ap_ST_pp4_stg0_fsm_11;
            end else begin
                ap_NS_fsm = ap_ST_pp4_stg3_fsm_14;
            end
        end
        ap_ST_st18_fsm_15 : begin
            ap_NS_fsm = ap_ST_st1_fsm_0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_reg_phiprechg_last_2_2_reg_307pp4_it0 = 'bx;

assign ap_reg_phiprechg_last_2_3_reg_378pp4_it0 = 'bx;

assign ap_reg_phiprechg_p_067_2_3_reg_358pp4_it0 = 'bx;

assign ap_reg_phiprechg_p_071_2_3_reg_348pp4_it0 = 'bx;

assign ap_reg_phiprechg_p_084_2_3_reg_368pp4_it0 = 'bx;

always @ (*) begin
    ap_rst_n_control_inv = ~ap_rst_n_control;
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

always @ (*) begin
    ap_sig_101 = (1'b1 == ap_CS_fsm[ap_const_lv32_C]);
end

always @ (*) begin
    ap_sig_114 = (1'b1 == ap_CS_fsm[ap_const_lv32_D]);
end

always @ (*) begin
    ap_sig_126 = (1'b1 == ap_CS_fsm[ap_const_lv32_E]);
end

always @ (*) begin
    ap_sig_129 = ((1'b1 == ap_reg_ppiten_pp4_it0) & (1'b1 == ap_sig_cseq_ST_pp4_stg3_fsm_14));
end

always @ (*) begin
    ap_sig_138 = (1'b1 == ap_CS_fsm[ap_const_lv32_A]);
end

always @ (*) begin
    ap_sig_146 = (1'b1 == ap_CS_fsm[ap_const_lv32_6]);
end

always @ (*) begin
    ap_sig_154 = (1'b1 == ap_CS_fsm[ap_const_lv32_7]);
end

always @ (*) begin
    ap_sig_165 = (1'b1 == ap_CS_fsm[ap_const_lv32_8]);
end

always @ (*) begin
    ap_sig_176 = (1'b1 == ap_CS_fsm[ap_const_lv32_9]);
end

always @ (*) begin
    ap_sig_187 = (1'b1 == ap_CS_fsm[ap_const_lv32_4]);
end

always @ (*) begin
    ap_sig_195 = (1'b1 == ap_CS_fsm[ap_const_lv32_5]);
end

always @ (*) begin
    ap_sig_203 = (1'b1 == ap_CS_fsm[ap_const_lv32_2]);
end

always @ (*) begin
    ap_sig_211 = (1'b1 == ap_CS_fsm[ap_const_lv32_3]);
end

always @ (*) begin
    ap_sig_304 = (1'b1 == ap_CS_fsm[ap_const_lv32_1]);
end

always @ (*) begin
    ap_sig_323 = ((1'b0 == in_stream_last_V_val4_reg_911) & (in_stream_TVALID == 1'b0));
end

always @ (*) begin
    ap_sig_332 = ((1'b0 == last_6_1_reg_173) & (in_stream_TVALID == 1'b0));
end

always @ (*) begin
    ap_sig_335 = ((1'b1 == ap_sig_cseq_ST_st9_fsm_8) & ~ap_sig_332);
end

always @ (*) begin
    ap_sig_357 = ((in_stream_last_V_val_reg_945 == 1'b0) & (in_stream_TVALID == 1'b0));
end

always @ (*) begin
    ap_sig_363 = ((1'b1 == ap_sig_cseq_ST_pp4_stg1_fsm_12) & (in_stream_last_V_val_reg_945 == 1'b0) & ~(((1'b1 == ap_reg_ppiten_pp4_it1) & (1'b0 == ap_sig_ioackin_out_stream_TREADY)) | ((1'b1 == ap_reg_ppiten_pp4_it0) & ap_sig_357)));
end

always @ (*) begin
    ap_sig_370 = ((1'b0 == last_2_1_reg_267) & (in_stream_TVALID == 1'b0));
end

always @ (*) begin
    ap_sig_382 = ((1'b0 == last_2_2_reg_307) & (in_stream_TVALID == 1'b0));
end

always @ (*) begin
    ap_sig_425 = ((1'b0 == last_6_2_reg_203) & (in_stream_TVALID == 1'b0));
end

always @ (*) begin
    ap_sig_440 = ((1'b1 == ap_reg_ppiten_pp4_it0) & (1'b1 == ap_sig_cseq_ST_pp4_stg1_fsm_12) & ~(((1'b1 == ap_reg_ppiten_pp4_it1) & (1'b0 == ap_sig_ioackin_out_stream_TREADY)) | ((1'b1 == ap_reg_ppiten_pp4_it0) & ap_sig_357)));
end

always @ (*) begin
    ap_sig_445 = ((1'b1 == ap_reg_ppiten_pp4_it0) & (1'b1 == ap_sig_cseq_ST_pp4_stg2_fsm_13) & ~((1'b1 == ap_reg_ppiten_pp4_it0) & ap_sig_370));
end

always @ (*) begin
    ap_sig_814 = (1'b1 == ap_CS_fsm[ap_const_lv32_F]);
end

always @ (*) begin
    ap_sig_89 = (ap_CS_fsm[ap_const_lv32_B] == 1'b1);
end

always @ (*) begin
    ap_sig_892 = ((1'b1 == ap_sig_cseq_ST_pp4_stg0_fsm_11) & ~(((1'b1 == ap_reg_ppiten_pp4_it0) & (in_stream_TVALID == 1'b0)) | ((1'b1 == ap_reg_ppiten_pp4_it1) & (1'b0 == ap_sig_ioackin_out_stream_TREADY))) & ~(1'b0 == grp_fu_418_p1));
end

assign grp_fu_393_p4 = {{in_stream_TDATA[ap_const_lv32_F : ap_const_lv32_8]}};

assign grp_fu_403_p4 = {{in_stream_TDATA[ap_const_lv32_17 : ap_const_lv32_10]}};

assign grp_fu_418_p1 = in_stream_TLAST;

assign grp_fu_437_p2 = (reg_429_1 | in_stream_TUSER);

assign grp_read_fu_144_p2 = mode_0_data_reg;

assign out_c1_V_fu_455_p2 = (tmp_fu_448_p1 + tmp_1_fu_451_p1);

assign out_c2_V_fu_468_p2 = (tmp_3_fu_461_p1 + tmp_4_fu_464_p1);

assign p_Result_26_1_fu_665_p5 = {{p_Result_7_reg_950[32'd95 : 32'd48]}, {in_stream_TDATA}, {p_Result_7_reg_950[32'd23 : 32'd0]}};

assign p_Result_26_2_fu_694_p5 = {{ap_reg_phiprechg_p_084_2_1_reg_297pp4_it0[32'd95 : 32'd72]}, {in_stream_TDATA}, {ap_reg_phiprechg_p_084_2_1_reg_297pp4_it0[32'd47 : 32'd0]}};

assign p_Result_26_3_fu_726_p5 = {{in_stream_TDATA}, {ap_reg_phiprechg_p_084_2_2_reg_338pp4_it0[32'd71 : 32'd0]}};

assign p_Result_2_fu_498_p5 = {{{{p_Result_8_fu_488_p4}, {tmp_12_fu_484_p1}}, {p_Result_6_fu_474_p4}}, {tmp_11_reg_889}};

assign p_Result_33_1_fu_554_p5 = {{p_Result_9_reg_916[32'd31 : 32'd16]}, {tmp_18_fu_550_p1}, {p_Result_9_reg_916[32'd7 : 32'd0]}};

assign p_Result_33_2_fu_575_p5 = {{p_0464_2_1_reg_183[32'd31 : 32'd24]}, {tmp_21_fu_571_p1}, {p_0464_2_1_reg_183[32'd15 : 32'd0]}};

assign p_Result_33_3_fu_598_p5 = {{tmp_24_fu_594_p1}, {p_0464_2_2_reg_214[32'd23 : 32'd0]}};

assign p_Result_35_1_fu_518_p3 = {{tmp_10_fu_514_p1}, {tmp_8_reg_897}};

assign p_Result_6_fu_474_p4 = {{out_c1_V_fu_455_p2[ap_const_lv32_8 : ap_const_lv32_1]}};

assign p_Result_7_fu_633_p5 = {{p_084_s_fu_126[32'd95 : 32'd24]}, {in_stream_TDATA}};

assign p_Result_8_fu_488_p4 = {{out_c2_V_fu_468_p2[ap_const_lv32_8 : ap_const_lv32_1]}};

assign p_Result_9_fu_533_p5 = {{p_0464_s_fu_122[32'd31 : 32'd8]}, {tmp_15_fu_529_p1}};

assign p_Result_s_fu_616_p3 = {{alpha_V_read_reg_847}, {in_stream_TDATA}};

assign tmp_10_fu_514_p1 = in_stream_TDATA[15:0];

assign tmp_11_fu_444_p1 = in_stream_TDATA[7:0];

assign tmp_12_fu_484_p1 = in_stream_TDATA[7:0];

always @ (*) begin
    tmp_13_fu_645_p4 = p_071_s_fu_134;
    tmp_13_fu_645_p4[ap_const_lv32_0] = |(in_stream_TUSER);
end

always @ (*) begin
    tmp_14_fu_655_p4 = p_067_s_fu_130;
    tmp_14_fu_655_p4[ap_const_lv32_0] = |(in_stream_TLAST);
end

assign tmp_15_fu_529_p1 = in_stream_TDATA[7:0];

always @ (*) begin
    tmp_16_fu_676_p4 = tmp_13_reg_956;
    tmp_16_fu_676_p4[ap_const_lv32_1] = |(in_stream_TUSER);
end

always @ (*) begin
    tmp_17_fu_685_p4 = tmp_14_reg_962;
    tmp_17_fu_685_p4[ap_const_lv32_1] = |(in_stream_TLAST);
end

assign tmp_18_fu_550_p1 = in_stream_TDATA[7:0];

always @ (*) begin
    tmp_19_fu_706_p4 = ap_reg_phiprechg_p_071_2_1_reg_277pp4_it0;
    tmp_19_fu_706_p4[ap_const_lv32_2] = |(in_stream_TUSER);
end

assign tmp_1_fu_451_p1 = grp_fu_393_p4;

always @ (*) begin
    tmp_20_fu_716_p4 = ap_reg_phiprechg_p_067_2_1_reg_287pp4_it0;
    tmp_20_fu_716_p4[ap_const_lv32_2] = |(in_stream_TLAST);
end

assign tmp_21_fu_571_p1 = in_stream_TDATA[7:0];

always @ (*) begin
    tmp_22_fu_739_p4 = ap_reg_phiprechg_p_071_2_2_reg_318pp4_it0;
    tmp_22_fu_739_p4[ap_const_lv32_3] = |(in_stream_TUSER);
end

always @ (*) begin
    tmp_23_fu_750_p4 = ap_reg_phiprechg_p_067_2_2_reg_328pp4_it0;
    tmp_23_fu_750_p4[ap_const_lv32_3] = |(in_stream_TLAST);
end

assign tmp_24_fu_594_p1 = in_stream_TDATA[7:0];

assign tmp_25_fu_761_p1 = p_084_2_3_phi_fu_371_p4[31:0];

assign tmp_26_fu_766_p1 = p_071_2_3_phi_fu_351_p4[0:0];

assign tmp_3_fu_461_p1 = p_Result_3_reg_884;

assign tmp_4_fu_464_p1 = grp_fu_403_p4;

assign tmp_8_fu_510_p1 = in_stream_TDATA[15:0];

assign tmp_fu_448_p1 = p_Result_s_30_reg_879;

assign user_3_1_fu_545_p2 = (in_stream_user_V_val6_reg_905 | in_stream_TUSER);

assign user_3_2_fu_565_p2 = (in_stream_TUSER | user_1_1_reg_193);

assign user_3_3_fu_587_p2 = (in_stream_TUSER | user_1_2_reg_224);

endmodule //pixel_pack
