// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module filter_Duplicate (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        src_data_stream_0_V_dout,
        src_data_stream_0_V_empty_n,
        src_data_stream_0_V_read,
        src_data_stream_1_V_dout,
        src_data_stream_1_V_empty_n,
        src_data_stream_1_V_read,
        src_data_stream_2_V_dout,
        src_data_stream_2_V_empty_n,
        src_data_stream_2_V_read,
        dst1_data_stream_0_V_din,
        dst1_data_stream_0_V_full_n,
        dst1_data_stream_0_V_write,
        dst1_data_stream_1_V_din,
        dst1_data_stream_1_V_full_n,
        dst1_data_stream_1_V_write,
        dst1_data_stream_2_V_din,
        dst1_data_stream_2_V_full_n,
        dst1_data_stream_2_V_write,
        dst2_data_stream_0_V_din,
        dst2_data_stream_0_V_full_n,
        dst2_data_stream_0_V_write,
        dst2_data_stream_1_V_din,
        dst2_data_stream_1_V_full_n,
        dst2_data_stream_1_V_write,
        dst2_data_stream_2_V_din,
        dst2_data_stream_2_V_full_n,
        dst2_data_stream_2_V_write
);

parameter    ap_ST_st1_fsm_0 = 4'b1;
parameter    ap_ST_st2_fsm_1 = 4'b10;
parameter    ap_ST_pp0_stg0_fsm_2 = 4'b100;
parameter    ap_ST_st5_fsm_3 = 4'b1000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv11_438 = 11'b10000111000;
parameter    ap_const_lv11_1 = 11'b1;
parameter    ap_const_lv11_780 = 11'b11110000000;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] src_data_stream_0_V_dout;
input   src_data_stream_0_V_empty_n;
output   src_data_stream_0_V_read;
input  [7:0] src_data_stream_1_V_dout;
input   src_data_stream_1_V_empty_n;
output   src_data_stream_1_V_read;
input  [7:0] src_data_stream_2_V_dout;
input   src_data_stream_2_V_empty_n;
output   src_data_stream_2_V_read;
output  [7:0] dst1_data_stream_0_V_din;
input   dst1_data_stream_0_V_full_n;
output   dst1_data_stream_0_V_write;
output  [7:0] dst1_data_stream_1_V_din;
input   dst1_data_stream_1_V_full_n;
output   dst1_data_stream_1_V_write;
output  [7:0] dst1_data_stream_2_V_din;
input   dst1_data_stream_2_V_full_n;
output   dst1_data_stream_2_V_write;
output  [7:0] dst2_data_stream_0_V_din;
input   dst2_data_stream_0_V_full_n;
output   dst2_data_stream_0_V_write;
output  [7:0] dst2_data_stream_1_V_din;
input   dst2_data_stream_1_V_full_n;
output   dst2_data_stream_1_V_write;
output  [7:0] dst2_data_stream_2_V_din;
input   dst2_data_stream_2_V_full_n;
output   dst2_data_stream_2_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg src_data_stream_0_V_read;
reg src_data_stream_1_V_read;
reg src_data_stream_2_V_read;
reg dst1_data_stream_0_V_write;
reg dst1_data_stream_1_V_write;
reg dst1_data_stream_2_V_write;
reg dst2_data_stream_0_V_write;
reg dst2_data_stream_1_V_write;
reg dst2_data_stream_2_V_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_22;
reg    src_data_stream_0_V_blk_n;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_2;
reg    ap_sig_71;
reg    ap_reg_ppiten_pp0_it1;
reg    ap_reg_ppiten_pp0_it0;
reg   [0:0] exitcond_reg_191;
reg    src_data_stream_1_V_blk_n;
reg    src_data_stream_2_V_blk_n;
reg    dst1_data_stream_0_V_blk_n;
reg    dst1_data_stream_1_V_blk_n;
reg    dst1_data_stream_2_V_blk_n;
reg    dst2_data_stream_0_V_blk_n;
reg    dst2_data_stream_1_V_blk_n;
reg    dst2_data_stream_2_V_blk_n;
reg   [10:0] p_4_reg_147;
wire   [0:0] exitcond4_fu_158_p2;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_99;
wire   [10:0] i_V_fu_164_p2;
reg   [10:0] i_V_reg_186;
wire   [0:0] exitcond_fu_170_p2;
reg    ap_sig_130;
wire   [10:0] j_V_fu_176_p2;
reg   [10:0] p_s_reg_136;
reg    ap_sig_151;
reg    ap_sig_cseq_ST_st5_fsm_3;
reg    ap_sig_159;
reg   [3:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'b1;
#0 ap_reg_ppiten_pp0_it1 = 1'b0;
#0 ap_reg_ppiten_pp0_it0 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_continue)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == exitcond4_fu_158_p2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((1'b1 == ap_reg_ppiten_pp0_it1) & ap_sig_130) & ~(1'b0 == exitcond_fu_170_p2))) begin
            ap_reg_ppiten_pp0_it0 <= 1'b0;
        end else if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (1'b0 == exitcond4_fu_158_p2))) begin
            ap_reg_ppiten_pp0_it0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((1'b1 == ap_reg_ppiten_pp0_it1) & ap_sig_130) & (1'b0 == exitcond_fu_170_p2))) begin
            ap_reg_ppiten_pp0_it1 <= 1'b1;
        end else if ((((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (1'b0 == exitcond4_fu_158_p2)) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((1'b1 == ap_reg_ppiten_pp0_it1) & ap_sig_130) & ~(1'b0 == exitcond_fu_170_p2)))) begin
            ap_reg_ppiten_pp0_it1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it0) & ~((1'b1 == ap_reg_ppiten_pp0_it1) & ap_sig_130) & (1'b0 == exitcond_fu_170_p2))) begin
        p_4_reg_147 <= j_V_fu_176_p2;
    end else if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (1'b0 == exitcond4_fu_158_p2))) begin
        p_4_reg_147 <= ap_const_lv11_0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st5_fsm_3)) begin
        p_s_reg_136 <= i_V_reg_186;
    end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_151)) begin
        p_s_reg_136 <= ap_const_lv11_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((1'b1 == ap_reg_ppiten_pp0_it1) & ap_sig_130))) begin
        exitcond_reg_191 <= exitcond_fu_170_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        i_V_reg_186 <= i_V_fu_164_p2;
    end
end

always @ (*) begin
    if (((1'b1 == ap_done_reg) | ((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == exitcond4_fu_158_p2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == exitcond4_fu_158_p2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_71) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_22) begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_99) begin
        ap_sig_cseq_ST_st2_fsm_1 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_159) begin
        ap_sig_cseq_ST_st5_fsm_3 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st5_fsm_3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_reg_191 == 1'b0))) begin
        dst1_data_stream_0_V_blk_n = dst1_data_stream_0_V_full_n;
    end else begin
        dst1_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_reg_191 == 1'b0) & ~((1'b1 == ap_reg_ppiten_pp0_it1) & ap_sig_130))) begin
        dst1_data_stream_0_V_write = 1'b1;
    end else begin
        dst1_data_stream_0_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_reg_191 == 1'b0))) begin
        dst1_data_stream_1_V_blk_n = dst1_data_stream_1_V_full_n;
    end else begin
        dst1_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_reg_191 == 1'b0) & ~((1'b1 == ap_reg_ppiten_pp0_it1) & ap_sig_130))) begin
        dst1_data_stream_1_V_write = 1'b1;
    end else begin
        dst1_data_stream_1_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_reg_191 == 1'b0))) begin
        dst1_data_stream_2_V_blk_n = dst1_data_stream_2_V_full_n;
    end else begin
        dst1_data_stream_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_reg_191 == 1'b0) & ~((1'b1 == ap_reg_ppiten_pp0_it1) & ap_sig_130))) begin
        dst1_data_stream_2_V_write = 1'b1;
    end else begin
        dst1_data_stream_2_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_reg_191 == 1'b0))) begin
        dst2_data_stream_0_V_blk_n = dst2_data_stream_0_V_full_n;
    end else begin
        dst2_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_reg_191 == 1'b0) & ~((1'b1 == ap_reg_ppiten_pp0_it1) & ap_sig_130))) begin
        dst2_data_stream_0_V_write = 1'b1;
    end else begin
        dst2_data_stream_0_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_reg_191 == 1'b0))) begin
        dst2_data_stream_1_V_blk_n = dst2_data_stream_1_V_full_n;
    end else begin
        dst2_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_reg_191 == 1'b0) & ~((1'b1 == ap_reg_ppiten_pp0_it1) & ap_sig_130))) begin
        dst2_data_stream_1_V_write = 1'b1;
    end else begin
        dst2_data_stream_1_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_reg_191 == 1'b0))) begin
        dst2_data_stream_2_V_blk_n = dst2_data_stream_2_V_full_n;
    end else begin
        dst2_data_stream_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_reg_191 == 1'b0) & ~((1'b1 == ap_reg_ppiten_pp0_it1) & ap_sig_130))) begin
        dst2_data_stream_2_V_write = 1'b1;
    end else begin
        dst2_data_stream_2_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_reg_191 == 1'b0))) begin
        src_data_stream_0_V_blk_n = src_data_stream_0_V_empty_n;
    end else begin
        src_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_reg_191 == 1'b0) & ~((1'b1 == ap_reg_ppiten_pp0_it1) & ap_sig_130))) begin
        src_data_stream_0_V_read = 1'b1;
    end else begin
        src_data_stream_0_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_reg_191 == 1'b0))) begin
        src_data_stream_1_V_blk_n = src_data_stream_1_V_empty_n;
    end else begin
        src_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_reg_191 == 1'b0) & ~((1'b1 == ap_reg_ppiten_pp0_it1) & ap_sig_130))) begin
        src_data_stream_1_V_read = 1'b1;
    end else begin
        src_data_stream_1_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_reg_191 == 1'b0))) begin
        src_data_stream_2_V_blk_n = src_data_stream_2_V_empty_n;
    end else begin
        src_data_stream_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_reg_191 == 1'b0) & ~((1'b1 == ap_reg_ppiten_pp0_it1) & ap_sig_130))) begin
        src_data_stream_2_V_read = 1'b1;
    end else begin
        src_data_stream_2_V_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : begin
            if (~ap_sig_151) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : begin
            if (~(1'b0 == exitcond4_fu_158_p2)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end
        end
        ap_ST_pp0_stg0_fsm_2 : begin
            if (~((1'b1 == ap_reg_ppiten_pp0_it0) & ~((1'b1 == ap_reg_ppiten_pp0_it1) & ap_sig_130) & ~(1'b0 == exitcond_fu_170_p2))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end else if (((1'b1 == ap_reg_ppiten_pp0_it0) & ~((1'b1 == ap_reg_ppiten_pp0_it1) & ap_sig_130) & ~(1'b0 == exitcond_fu_170_p2))) begin
                ap_NS_fsm = ap_ST_st5_fsm_3;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end
        end
        ap_ST_st5_fsm_3 : begin
            ap_NS_fsm = ap_ST_st2_fsm_1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    ap_sig_130 = (((exitcond_reg_191 == 1'b0) & (src_data_stream_0_V_empty_n == 1'b0)) | ((exitcond_reg_191 == 1'b0) & (src_data_stream_1_V_empty_n == 1'b0)) | ((exitcond_reg_191 == 1'b0) & (src_data_stream_2_V_empty_n == 1'b0)) | ((exitcond_reg_191 == 1'b0) & (dst1_data_stream_0_V_full_n == 1'b0)) | ((exitcond_reg_191 == 1'b0) & (dst1_data_stream_1_V_full_n == 1'b0)) | ((exitcond_reg_191 == 1'b0) & (dst1_data_stream_2_V_full_n == 1'b0)) | ((exitcond_reg_191 == 1'b0) & (dst2_data_stream_0_V_full_n == 1'b0)) | ((exitcond_reg_191 == 1'b0) & (dst2_data_stream_1_V_full_n == 1'b0)) | ((exitcond_reg_191 == 1'b0) & (dst2_data_stream_2_V_full_n == 1'b0)));
end

always @ (*) begin
    ap_sig_151 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_sig_159 = (1'b1 == ap_CS_fsm[ap_const_lv32_3]);
end

always @ (*) begin
    ap_sig_22 = (ap_CS_fsm[ap_const_lv32_0] == 1'b1);
end

always @ (*) begin
    ap_sig_71 = (1'b1 == ap_CS_fsm[ap_const_lv32_2]);
end

always @ (*) begin
    ap_sig_99 = (1'b1 == ap_CS_fsm[ap_const_lv32_1]);
end

assign dst1_data_stream_0_V_din = src_data_stream_0_V_dout;

assign dst1_data_stream_1_V_din = src_data_stream_1_V_dout;

assign dst1_data_stream_2_V_din = src_data_stream_2_V_dout;

assign dst2_data_stream_0_V_din = src_data_stream_0_V_dout;

assign dst2_data_stream_1_V_din = src_data_stream_1_V_dout;

assign dst2_data_stream_2_V_din = src_data_stream_2_V_dout;

assign exitcond4_fu_158_p2 = ((p_s_reg_136 == ap_const_lv11_438) ? 1'b1 : 1'b0);

assign exitcond_fu_170_p2 = ((p_4_reg_147 == ap_const_lv11_780) ? 1'b1 : 1'b0);

assign i_V_fu_164_p2 = (p_s_reg_136 + ap_const_lv11_1);

assign j_V_fu_176_p2 = (p_4_reg_147 + ap_const_lv11_1);

endmodule //filter_Duplicate
