// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module filter_combine4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        img_in3_data_stream_V_dout,
        img_in3_data_stream_V_empty_n,
        img_in3_data_stream_V_read,
        img_in2_data_stream_V_dout,
        img_in2_data_stream_V_empty_n,
        img_in2_data_stream_V_read,
        img_in1_data_stream_V_dout,
        img_in1_data_stream_V_empty_n,
        img_in1_data_stream_V_read,
        img_in0_data_stream_V_dout,
        img_in0_data_stream_V_empty_n,
        img_in0_data_stream_V_read,
        img_out_data_stream_V_din,
        img_out_data_stream_V_full_n,
        img_out_data_stream_V_write
);

parameter    ap_ST_st1_fsm_0 = 2'b1;
parameter    ap_ST_pp0_stg0_fsm_1 = 2'b10;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv21_0 = 21'b000000000000000000000;
parameter    ap_const_lv11_1 = 11'b1;
parameter    ap_const_lv11_21C = 11'b1000011100;
parameter    ap_const_lv11_3C0 = 11'b1111000000;
parameter    ap_const_lv21_1 = 21'b1;
parameter    ap_const_lv11_780 = 11'b11110000000;
parameter    ap_const_lv21_1FA3FF = 21'b111111010001111111111;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] img_in3_data_stream_V_dout;
input   img_in3_data_stream_V_empty_n;
output   img_in3_data_stream_V_read;
input  [7:0] img_in2_data_stream_V_dout;
input   img_in2_data_stream_V_empty_n;
output   img_in2_data_stream_V_read;
input  [7:0] img_in1_data_stream_V_dout;
input   img_in1_data_stream_V_empty_n;
output   img_in1_data_stream_V_read;
input  [7:0] img_in0_data_stream_V_dout;
input   img_in0_data_stream_V_empty_n;
output   img_in0_data_stream_V_read;
output  [7:0] img_out_data_stream_V_din;
input   img_out_data_stream_V_full_n;
output   img_out_data_stream_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg img_in3_data_stream_V_read;
reg img_in2_data_stream_V_read;
reg img_in1_data_stream_V_read;
reg img_in0_data_stream_V_read;
reg img_out_data_stream_V_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_20;
wire   [0:0] exitcond_flatten_fu_225_p2;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_1;
reg    ap_sig_36;
wire    ap_reg_ppiten_pp0_it0;
wire   [0:0] tmp_s_fu_195_p2;
wire   [0:0] tmp_5_fu_201_p2;
reg    ap_sig_78;
reg    ap_reg_ppiten_pp0_it1;
reg    img_in0_data_stream_V_blk_n;
reg    img_in1_data_stream_V_blk_n;
reg    img_in2_data_stream_V_blk_n;
reg    img_in3_data_stream_V_blk_n;
reg    img_out_data_stream_V_blk_n;
reg   [0:0] exitcond5_reg_103;
reg   [10:0] col4_reg_117;
reg   [10:0] row3_reg_131;
reg   [20:0] indvar_flatten2_reg_145;
wire   [10:0] row_mid2_fu_187_p3;
reg   [10:0] row_mid2_reg_233;
wire   [20:0] indvar_flatten_next_fu_207_p2;
reg   [20:0] indvar_flatten_next_reg_246;
wire   [10:0] col_fu_213_p2;
reg   [10:0] col_reg_271;
wire   [0:0] exitcond_fu_219_p2;
reg   [0:0] exitcond_reg_276;
reg   [0:0] exitcond_flatten_reg_281;
reg    ap_sig_140;
reg   [0:0] exitcond5_phi_fu_107_p6;
reg   [10:0] col4_phi_fu_121_p6;
reg   [10:0] row3_phi_fu_135_p6;
reg   [20:0] indvar_flatten2_phi_fu_149_p6;
wire   [7:0] ap_reg_phiprechg_tmp_12_reg_159pp0_it0;
reg   [7:0] ap_reg_phiprechg_tmp_12_reg_159pp0_it1;
wire   [10:0] row_fu_173_p2;
wire   [10:0] col_mid2_fu_179_p3;
reg   [1:0] ap_NS_fsm;
reg    ap_sig_pprstidle_pp0;
reg    ap_sig_67;
reg    ap_sig_74;
reg    ap_sig_51;
reg    ap_sig_59;
reg    ap_sig_93;
reg    ap_sig_104;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'b1;
#0 ap_reg_ppiten_pp0_it1 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_continue)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_78) | ((img_out_data_stream_V_full_n == 1'b0) & (1'b1 == ap_reg_ppiten_pp0_it1)) | (ap_done_reg == 1'b1)) & ~(1'b0 == exitcond_flatten_reg_281))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_78) | ((img_out_data_stream_V_full_n == 1'b0) & (1'b1 == ap_reg_ppiten_pp0_it1)) | (ap_done_reg == 1'b1)))) begin
            ap_reg_ppiten_pp0_it1 <= ap_start;
        end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_140)) begin
            ap_reg_ppiten_pp0_it1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_sig_93) begin
        if (ap_sig_59) begin
            ap_reg_phiprechg_tmp_12_reg_159pp0_it1 <= img_in2_data_stream_V_dout;
        end else if (ap_sig_51) begin
            ap_reg_phiprechg_tmp_12_reg_159pp0_it1 <= img_in3_data_stream_V_dout;
        end else if (ap_sig_74) begin
            ap_reg_phiprechg_tmp_12_reg_159pp0_it1 <= img_in0_data_stream_V_dout;
        end else if (ap_sig_67) begin
            ap_reg_phiprechg_tmp_12_reg_159pp0_it1 <= img_in1_data_stream_V_dout;
        end else if ((1'b1 == 1'b1)) begin
            ap_reg_phiprechg_tmp_12_reg_159pp0_it1 <= ap_reg_phiprechg_tmp_12_reg_159pp0_it0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_78) | ((img_out_data_stream_V_full_n == 1'b0) & (1'b1 == ap_reg_ppiten_pp0_it1)) | (ap_done_reg == 1'b1)) & (1'b0 == exitcond_flatten_reg_281))) begin
        col4_reg_117 <= col_reg_271;
    end else if ((((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_140) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_78) | ((img_out_data_stream_V_full_n == 1'b0) & (1'b1 == ap_reg_ppiten_pp0_it1)) | (ap_done_reg == 1'b1)) & ~(1'b0 == exitcond_flatten_reg_281)))) begin
        col4_reg_117 <= ap_const_lv11_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_78) | ((img_out_data_stream_V_full_n == 1'b0) & (1'b1 == ap_reg_ppiten_pp0_it1)) | (ap_done_reg == 1'b1)) & (1'b0 == exitcond_flatten_reg_281))) begin
        exitcond5_reg_103 <= exitcond_reg_276;
    end else if ((((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_140) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_78) | ((img_out_data_stream_V_full_n == 1'b0) & (1'b1 == ap_reg_ppiten_pp0_it1)) | (ap_done_reg == 1'b1)) & ~(1'b0 == exitcond_flatten_reg_281)))) begin
        exitcond5_reg_103 <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_78) | ((img_out_data_stream_V_full_n == 1'b0) & (1'b1 == ap_reg_ppiten_pp0_it1)) | (ap_done_reg == 1'b1)) & (1'b0 == exitcond_flatten_reg_281))) begin
        indvar_flatten2_reg_145 <= indvar_flatten_next_reg_246;
    end else if ((((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_140) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_78) | ((img_out_data_stream_V_full_n == 1'b0) & (1'b1 == ap_reg_ppiten_pp0_it1)) | (ap_done_reg == 1'b1)) & ~(1'b0 == exitcond_flatten_reg_281)))) begin
        indvar_flatten2_reg_145 <= ap_const_lv21_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_78) | ((img_out_data_stream_V_full_n == 1'b0) & (1'b1 == ap_reg_ppiten_pp0_it1)) | (ap_done_reg == 1'b1)) & (1'b0 == exitcond_flatten_reg_281))) begin
        row3_reg_131 <= row_mid2_reg_233;
    end else if ((((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_140) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_78) | ((img_out_data_stream_V_full_n == 1'b0) & (1'b1 == ap_reg_ppiten_pp0_it1)) | (ap_done_reg == 1'b1)) & ~(1'b0 == exitcond_flatten_reg_281)))) begin
        row3_reg_131 <= ap_const_lv11_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_78) | ((img_out_data_stream_V_full_n == 1'b0) & (1'b1 == ap_reg_ppiten_pp0_it1)) | (ap_done_reg == 1'b1)))) begin
        col_reg_271 <= col_fu_213_p2;
        exitcond_reg_276 <= exitcond_fu_219_p2;
        indvar_flatten_next_reg_246 <= indvar_flatten_next_fu_207_p2;
        row_mid2_reg_233 <= row_mid2_fu_187_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_78) | ((img_out_data_stream_V_full_n == 1'b0) & (1'b1 == ap_reg_ppiten_pp0_it1)) | (ap_done_reg == 1'b1)))) begin
        exitcond_flatten_reg_281 <= exitcond_flatten_fu_225_p2;
    end
end

always @ (*) begin
    if (((1'b1 == ap_done_reg) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_78) | ((img_out_data_stream_V_full_n == 1'b0) & (1'b1 == ap_reg_ppiten_pp0_it1)) | (ap_done_reg == 1'b1)) & ~(1'b0 == exitcond_flatten_reg_281)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~(exitcond_flatten_fu_225_p2 == 1'b0) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_78) | ((img_out_data_stream_V_full_n == 1'b0) & (1'b1 == ap_reg_ppiten_pp0_it1)) | (ap_done_reg == 1'b1)))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_36) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_20) begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b0 == ap_reg_ppiten_pp0_it0))) begin
        ap_sig_pprstidle_pp0 = 1'b1;
    end else begin
        ap_sig_pprstidle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_104) begin
        if (~(1'b0 == exitcond_flatten_reg_281)) begin
            col4_phi_fu_121_p6 = ap_const_lv11_0;
        end else if ((1'b0 == exitcond_flatten_reg_281)) begin
            col4_phi_fu_121_p6 = col_reg_271;
        end else begin
            col4_phi_fu_121_p6 = col4_reg_117;
        end
    end else begin
        col4_phi_fu_121_p6 = col4_reg_117;
    end
end

always @ (*) begin
    if (ap_sig_104) begin
        if (~(1'b0 == exitcond_flatten_reg_281)) begin
            exitcond5_phi_fu_107_p6 = 1'b0;
        end else if ((1'b0 == exitcond_flatten_reg_281)) begin
            exitcond5_phi_fu_107_p6 = exitcond_reg_276;
        end else begin
            exitcond5_phi_fu_107_p6 = exitcond5_reg_103;
        end
    end else begin
        exitcond5_phi_fu_107_p6 = exitcond5_reg_103;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0) & ~(1'b0 == tmp_5_fu_201_p2) & ~(1'b0 == tmp_s_fu_195_p2))) begin
        img_in0_data_stream_V_blk_n = img_in0_data_stream_V_empty_n;
    end else begin
        img_in0_data_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0) & ~(1'b0 == tmp_5_fu_201_p2) & ~(1'b0 == tmp_s_fu_195_p2) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_78) | ((img_out_data_stream_V_full_n == 1'b0) & (1'b1 == ap_reg_ppiten_pp0_it1)) | (ap_done_reg == 1'b1)))) begin
        img_in0_data_stream_V_read = 1'b1;
    end else begin
        img_in0_data_stream_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0) & (1'b0 == tmp_5_fu_201_p2) & ~(1'b0 == tmp_s_fu_195_p2))) begin
        img_in1_data_stream_V_blk_n = img_in1_data_stream_V_empty_n;
    end else begin
        img_in1_data_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0) & (1'b0 == tmp_5_fu_201_p2) & ~(1'b0 == tmp_s_fu_195_p2) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_78) | ((img_out_data_stream_V_full_n == 1'b0) & (1'b1 == ap_reg_ppiten_pp0_it1)) | (ap_done_reg == 1'b1)))) begin
        img_in1_data_stream_V_read = 1'b1;
    end else begin
        img_in1_data_stream_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0) & (1'b0 == tmp_s_fu_195_p2) & ~(1'b0 == tmp_5_fu_201_p2))) begin
        img_in2_data_stream_V_blk_n = img_in2_data_stream_V_empty_n;
    end else begin
        img_in2_data_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0) & (1'b0 == tmp_s_fu_195_p2) & ~(1'b0 == tmp_5_fu_201_p2) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_78) | ((img_out_data_stream_V_full_n == 1'b0) & (1'b1 == ap_reg_ppiten_pp0_it1)) | (ap_done_reg == 1'b1)))) begin
        img_in2_data_stream_V_read = 1'b1;
    end else begin
        img_in2_data_stream_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0) & (1'b0 == tmp_s_fu_195_p2) & (1'b0 == tmp_5_fu_201_p2))) begin
        img_in3_data_stream_V_blk_n = img_in3_data_stream_V_empty_n;
    end else begin
        img_in3_data_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0) & (1'b0 == tmp_s_fu_195_p2) & (1'b0 == tmp_5_fu_201_p2) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_78) | ((img_out_data_stream_V_full_n == 1'b0) & (1'b1 == ap_reg_ppiten_pp0_it1)) | (ap_done_reg == 1'b1)))) begin
        img_in3_data_stream_V_read = 1'b1;
    end else begin
        img_in3_data_stream_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it1))) begin
        img_out_data_stream_V_blk_n = img_out_data_stream_V_full_n;
    end else begin
        img_out_data_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_78) | ((img_out_data_stream_V_full_n == 1'b0) & (1'b1 == ap_reg_ppiten_pp0_it1)) | (ap_done_reg == 1'b1)))) begin
        img_out_data_stream_V_write = 1'b1;
    end else begin
        img_out_data_stream_V_write = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_104) begin
        if (~(1'b0 == exitcond_flatten_reg_281)) begin
            indvar_flatten2_phi_fu_149_p6 = ap_const_lv21_0;
        end else if ((1'b0 == exitcond_flatten_reg_281)) begin
            indvar_flatten2_phi_fu_149_p6 = indvar_flatten_next_reg_246;
        end else begin
            indvar_flatten2_phi_fu_149_p6 = indvar_flatten2_reg_145;
        end
    end else begin
        indvar_flatten2_phi_fu_149_p6 = indvar_flatten2_reg_145;
    end
end

always @ (*) begin
    if (ap_sig_104) begin
        if (~(1'b0 == exitcond_flatten_reg_281)) begin
            row3_phi_fu_135_p6 = ap_const_lv11_0;
        end else if ((1'b0 == exitcond_flatten_reg_281)) begin
            row3_phi_fu_135_p6 = row_mid2_reg_233;
        end else begin
            row3_phi_fu_135_p6 = row3_reg_131;
        end
    end else begin
        row3_phi_fu_135_p6 = row3_reg_131;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : begin
            if (~ap_sig_140) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_pp0_stg0_fsm_1 : begin
            if (~(1'b1 == ap_sig_pprstidle_pp0)) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            end else if ((~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_78) | ((img_out_data_stream_V_full_n == 1'b0) & (1'b1 == ap_reg_ppiten_pp0_it1)) | (ap_done_reg == 1'b1)) & (1'b1 == ap_sig_pprstidle_pp0))) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_reg_phiprechg_tmp_12_reg_159pp0_it0 = 'bx;

assign ap_reg_ppiten_pp0_it0 = ap_start;

always @ (*) begin
    ap_sig_104 = ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it1));
end

always @ (*) begin
    ap_sig_140 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_sig_20 = (ap_CS_fsm[ap_const_lv32_0] == 1'b1);
end

always @ (*) begin
    ap_sig_36 = (1'b1 == ap_CS_fsm[ap_const_lv32_1]);
end

always @ (*) begin
    ap_sig_51 = ((1'b0 == tmp_s_fu_195_p2) & (1'b0 == tmp_5_fu_201_p2));
end

always @ (*) begin
    ap_sig_59 = ((1'b0 == tmp_s_fu_195_p2) & ~(1'b0 == tmp_5_fu_201_p2));
end

always @ (*) begin
    ap_sig_67 = ((1'b0 == tmp_5_fu_201_p2) & ~(1'b0 == tmp_s_fu_195_p2));
end

always @ (*) begin
    ap_sig_74 = (~(1'b0 == tmp_5_fu_201_p2) & ~(1'b0 == tmp_s_fu_195_p2));
end

always @ (*) begin
    ap_sig_78 = (((img_in3_data_stream_V_empty_n == 1'b0) & (1'b0 == tmp_s_fu_195_p2) & (1'b0 == tmp_5_fu_201_p2)) | ((1'b0 == tmp_s_fu_195_p2) & (img_in2_data_stream_V_empty_n == 1'b0) & ~(1'b0 == tmp_5_fu_201_p2)) | ((1'b0 == tmp_5_fu_201_p2) & (img_in1_data_stream_V_empty_n == 1'b0) & ~(1'b0 == tmp_s_fu_195_p2)) | (~(1'b0 == tmp_5_fu_201_p2) & ~(1'b0 == tmp_s_fu_195_p2) & (img_in0_data_stream_V_empty_n == 1'b0)));
end

always @ (*) begin
    ap_sig_93 = ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_78) | ((img_out_data_stream_V_full_n == 1'b0) & (1'b1 == ap_reg_ppiten_pp0_it1)) | (ap_done_reg == 1'b1)));
end

assign col_fu_213_p2 = (col_mid2_fu_179_p3 + ap_const_lv11_1);

assign col_mid2_fu_179_p3 = ((exitcond5_phi_fu_107_p6[0:0] === 1'b1) ? ap_const_lv11_0 : col4_phi_fu_121_p6);

assign exitcond_flatten_fu_225_p2 = ((indvar_flatten2_phi_fu_149_p6 == ap_const_lv21_1FA3FF) ? 1'b1 : 1'b0);

assign exitcond_fu_219_p2 = ((col_fu_213_p2 == ap_const_lv11_780) ? 1'b1 : 1'b0);

assign img_out_data_stream_V_din = ap_reg_phiprechg_tmp_12_reg_159pp0_it1;

assign indvar_flatten_next_fu_207_p2 = (indvar_flatten2_phi_fu_149_p6 + ap_const_lv21_1);

assign row_fu_173_p2 = (row3_phi_fu_135_p6 + ap_const_lv11_1);

assign row_mid2_fu_187_p3 = ((exitcond5_phi_fu_107_p6[0:0] === 1'b1) ? row_fu_173_p2 : row3_phi_fu_135_p6);

assign tmp_5_fu_201_p2 = ((col_mid2_fu_179_p3 < ap_const_lv11_3C0) ? 1'b1 : 1'b0);

assign tmp_s_fu_195_p2 = ((row_mid2_fu_187_p3 < ap_const_lv11_21C) ? 1'b1 : 1'b0);

endmodule //filter_combine4
