# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Pynq2/PYNQ-master/boards/Pynq-Z1/base/vivado/constraints/top.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system}]

# IP: bd/system/ip/system_proc_sys_reset_fclk1_0/system_proc_sys_reset_fclk1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_fclk1_0 || ORIG_REF_NAME==system_proc_sys_reset_fclk1_0}]

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0}]

# IP: bd/system/ip/system_processing_system7_0_axi_periph_0/system_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==system_processing_system7_0_axi_periph_0}]

# IP: bd/system/ip/system_rst_processing_system7_0_fclk0_0/system_rst_processing_system7_0_fclk0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_processing_system7_0_fclk0_0 || ORIG_REF_NAME==system_rst_processing_system7_0_fclk0_0}]

# IP: bd/system/ip/system_system_interrupts_0/system_system_interrupts_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_system_interrupts_0 || ORIG_REF_NAME==system_system_interrupts_0}]

# IP: bd/system/ip/system_axi_interconnect_0_1/system_axi_interconnect_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_1 || ORIG_REF_NAME==system_axi_interconnect_0_1}]

# IP: bd/system/ip/system_axi_mem_intercon_1/system_axi_mem_intercon_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_mem_intercon_1 || ORIG_REF_NAME==system_axi_mem_intercon_1}]

# IP: bd/system/ip/system_axi_vdma_0/system_axi_vdma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_vdma_0 || ORIG_REF_NAME==system_axi_vdma_0}]

# IP: bd/system/ip/system_axis_register_slice_0_0/system_axis_register_slice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_register_slice_0_0 || ORIG_REF_NAME==system_axis_register_slice_0_0}]

# IP: bd/system/ip/system_color_convert_0/system_color_convert_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_color_convert_0 || ORIG_REF_NAME==system_color_convert_0}]

# IP: bd/system/ip/system_axi_gpio_hdmiin_0/system_axi_gpio_hdmiin_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_hdmiin_0 || ORIG_REF_NAME==system_axi_gpio_hdmiin_0}]

# IP: bd/system/ip/system_dvi2rgb_0_0/system_dvi2rgb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_dvi2rgb_0_0 || ORIG_REF_NAME==system_dvi2rgb_0_0}]

# IP: bd/system/ip/system_v_vid_in_axi4s_0_0/system_v_vid_in_axi4s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==system_v_vid_in_axi4s_0_0}]

# IP: bd/system/ip/system_vtc_in_0/system_vtc_in_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_vtc_in_0 || ORIG_REF_NAME==system_vtc_in_0}]

# IP: bd/system/ip/system_pixel_pack_0/system_pixel_pack_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_pixel_pack_0 || ORIG_REF_NAME==system_pixel_pack_0}]

# IP: bd/system/ip/system_axis_register_slice_0_1/system_axis_register_slice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_register_slice_0_1 || ORIG_REF_NAME==system_axis_register_slice_0_1}]

# IP: bd/system/ip/system_color_convert_1/system_color_convert_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_color_convert_1 || ORIG_REF_NAME==system_color_convert_1}]

# IP: bd/system/ip/system_axi_dynclk_0/system_axi_dynclk_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_dynclk_0 || ORIG_REF_NAME==system_axi_dynclk_0}]

# IP: bd/system/ip/system_hdmi_out_hpd_video_0/system_hdmi_out_hpd_video_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_hdmi_out_hpd_video_0 || ORIG_REF_NAME==system_hdmi_out_hpd_video_0}]

# IP: bd/system/ip/system_proc_sys_reset_pixelclk_0/system_proc_sys_reset_pixelclk_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_pixelclk_0 || ORIG_REF_NAME==system_proc_sys_reset_pixelclk_0}]

# IP: bd/system/ip/system_rgb2dvi_0_0/system_rgb2dvi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rgb2dvi_0_0 || ORIG_REF_NAME==system_rgb2dvi_0_0}]

# IP: bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==system_v_axi4s_vid_out_0_0}]

# IP: bd/system/ip/system_vtc_out_0/system_vtc_out_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_vtc_out_0 || ORIG_REF_NAME==system_vtc_out_0}]

# IP: bd/system/ip/system_pixel_unpack_0/system_pixel_unpack_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_pixel_unpack_0 || ORIG_REF_NAME==system_pixel_unpack_0}]

# IP: bd/system/ip/system_xlconcat_0_0/system_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconcat_0_0 || ORIG_REF_NAME==system_xlconcat_0_0}]

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0}]

# IP: bd/system/ip/system_xbar_1/system_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_1 || ORIG_REF_NAME==system_xbar_1}]

# IP: bd/system/ip/system_xbar_2/system_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_2 || ORIG_REF_NAME==system_xbar_2}]

# IP: bd/system/ip/system_filter_0_0/system_filter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_filter_0_0 || ORIG_REF_NAME==system_filter_0_0}]

# IP: bd/system/ip/system_add_function_0_1/system_add_function_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_add_function_0_1 || ORIG_REF_NAME==system_add_function_0_1}]

# IP: bd/system/ip/system_auto_cc_0/system_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_0 || ORIG_REF_NAME==system_auto_cc_0}]

# IP: bd/system/ip/system_auto_cc_1/system_auto_cc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_1 || ORIG_REF_NAME==system_auto_cc_1}]

# IP: bd/system/ip/system_auto_cc_2/system_auto_cc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_2 || ORIG_REF_NAME==system_auto_cc_2}]

# IP: bd/system/ip/system_auto_cc_3/system_auto_cc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_3 || ORIG_REF_NAME==system_auto_cc_3}]

# IP: bd/system/ip/system_auto_cc_4/system_auto_cc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_4 || ORIG_REF_NAME==system_auto_cc_4}]

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0}]

# IP: bd/system/ip/system_auto_pc_1/system_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_1 || ORIG_REF_NAME==system_auto_pc_1}]

# IP: bd/system/ip/system_auto_us_0/system_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_0 || ORIG_REF_NAME==system_auto_us_0}]

# IP: bd/system/ip/system_auto_us_1/system_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_1 || ORIG_REF_NAME==system_auto_us_1}]

# IP: bd/system/ip/system_auto_pc_2/system_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_2 || ORIG_REF_NAME==system_auto_pc_2}]

# IP: bd/system/ip/system_auto_pc_3/system_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_3 || ORIG_REF_NAME==system_auto_pc_3}]

# IP: bd/system/ip/system_auto_pc_4/system_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_4 || ORIG_REF_NAME==system_auto_pc_4}]

# XDC: bd/system/ip/system_proc_sys_reset_fclk1_0/system_proc_sys_reset_fclk1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_fclk1_0 || ORIG_REF_NAME==system_proc_sys_reset_fclk1_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_proc_sys_reset_fclk1_0/system_proc_sys_reset_fclk1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_fclk1_0 || ORIG_REF_NAME==system_proc_sys_reset_fclk1_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_proc_sys_reset_fclk1_0/system_proc_sys_reset_fclk1_0_ooc.xdc

# XDC: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_rst_processing_system7_0_fclk0_0/system_rst_processing_system7_0_fclk0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_processing_system7_0_fclk0_0 || ORIG_REF_NAME==system_rst_processing_system7_0_fclk0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_rst_processing_system7_0_fclk0_0/system_rst_processing_system7_0_fclk0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_processing_system7_0_fclk0_0 || ORIG_REF_NAME==system_rst_processing_system7_0_fclk0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_rst_processing_system7_0_fclk0_0/system_rst_processing_system7_0_fclk0_0_ooc.xdc

# XDC: bd/system/ip/system_system_interrupts_0/system_system_interrupts_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_system_interrupts_0 || ORIG_REF_NAME==system_system_interrupts_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_system_interrupts_0/system_system_interrupts_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_system_interrupts_0 || ORIG_REF_NAME==system_system_interrupts_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_system_interrupts_0/system_system_interrupts_0_ooc.xdc

# XDC: bd/system/ip/system_axi_vdma_0/system_axi_vdma_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_vdma_0 || ORIG_REF_NAME==system_axi_vdma_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_vdma_0/system_axi_vdma_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_vdma_0 || ORIG_REF_NAME==system_axi_vdma_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_vdma_0/system_axi_vdma_0_ooc.xdc

# XDC: bd/system/ip/system_axis_register_slice_0_0/system_axis_register_slice_0_0_ooc.xdc

# XDC: bd/system/ip/system_color_convert_0/constraints/color_convert_ooc.xdc

# XDC: bd/system/ip/system_axi_gpio_hdmiin_0/system_axi_gpio_hdmiin_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_hdmiin_0 || ORIG_REF_NAME==system_axi_gpio_hdmiin_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_gpio_hdmiin_0/system_axi_gpio_hdmiin_0_ooc.xdc

# XDC: bd/system/ip/system_axi_gpio_hdmiin_0/system_axi_gpio_hdmiin_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_hdmiin_0 || ORIG_REF_NAME==system_axi_gpio_hdmiin_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_dvi2rgb_0_0/src/dvi2rgb.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_dvi2rgb_0_0 || ORIG_REF_NAME==system_dvi2rgb_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_dvi2rgb_0_0/src/dvi2rgb_ooc.xdc

# XDC: bd/system/ip/system_v_vid_in_axi4s_0_0/system_v_vid_in_axi4s_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==system_v_vid_in_axi4s_0_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_v_vid_in_axi4s_0_0/system_v_vid_in_axi4s_0_0_ooc.xdc

# XDC: bd/system/ip/system_vtc_in_0/system_vtc_in_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_vtc_in_0 || ORIG_REF_NAME==system_vtc_in_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_vtc_in_0/system_vtc_in_0_ooc.xdc

# XDC: bd/system/ip/system_pixel_pack_0/constraints/pixel_pack_ooc.xdc

# XDC: bd/system/ip/system_axis_register_slice_0_1/system_axis_register_slice_0_1_ooc.xdc

# XDC: bd/system/ip/system_color_convert_1/constraints/color_convert_ooc.xdc

# XDC: bd/system/ip/system_hdmi_out_hpd_video_0/system_hdmi_out_hpd_video_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_hdmi_out_hpd_video_0 || ORIG_REF_NAME==system_hdmi_out_hpd_video_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_hdmi_out_hpd_video_0/system_hdmi_out_hpd_video_0_ooc.xdc

# XDC: bd/system/ip/system_hdmi_out_hpd_video_0/system_hdmi_out_hpd_video_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_hdmi_out_hpd_video_0 || ORIG_REF_NAME==system_hdmi_out_hpd_video_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_proc_sys_reset_pixelclk_0/system_proc_sys_reset_pixelclk_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_pixelclk_0 || ORIG_REF_NAME==system_proc_sys_reset_pixelclk_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_proc_sys_reset_pixelclk_0/system_proc_sys_reset_pixelclk_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_pixelclk_0 || ORIG_REF_NAME==system_proc_sys_reset_pixelclk_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_proc_sys_reset_pixelclk_0/system_proc_sys_reset_pixelclk_0_ooc.xdc

# XDC: bd/system/ip/system_rgb2dvi_0_0/src/rgb2dvi.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rgb2dvi_0_0 || ORIG_REF_NAME==system_rgb2dvi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_rgb2dvi_0_0/src/rgb2dvi_ooc.xdc

# XDC: bd/system/ip/system_rgb2dvi_0_0/src/rgb2dvi_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rgb2dvi_0_0 || ORIG_REF_NAME==system_rgb2dvi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==system_v_axi4s_vid_out_0_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0_ooc.xdc

# XDC: bd/system/ip/system_vtc_out_0/system_vtc_out_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_vtc_out_0 || ORIG_REF_NAME==system_vtc_out_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_vtc_out_0/system_vtc_out_0_ooc.xdc

# XDC: bd/system/ip/system_pixel_unpack_0/constraints/pixel_unpack_ooc.xdc

# XDC: bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc

# XDC: bd/system/ip/system_xbar_1/system_xbar_1_ooc.xdc

# XDC: bd/system/ip/system_xbar_2/system_xbar_2_ooc.xdc

# XDC: bd/system/ip/system_filter_0_0/constraints/filter_ooc.xdc

# XDC: bd/system/ip/system_add_function_0_1/constraints/add_function_ooc.xdc

# XDC: bd/system/ip/system_auto_cc_0/system_auto_cc_0_ooc.xdc

# XDC: bd/system/ip/system_auto_cc_0/system_auto_cc_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_cc_0 || ORIG_REF_NAME==system_auto_cc_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_cc_1/system_auto_cc_1_ooc.xdc

# XDC: bd/system/ip/system_auto_cc_1/system_auto_cc_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_cc_1 || ORIG_REF_NAME==system_auto_cc_1}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_cc_2/system_auto_cc_2_ooc.xdc

# XDC: bd/system/ip/system_auto_cc_2/system_auto_cc_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_cc_2 || ORIG_REF_NAME==system_auto_cc_2}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_cc_3/system_auto_cc_3_ooc.xdc

# XDC: bd/system/ip/system_auto_cc_3/system_auto_cc_3_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_cc_3 || ORIG_REF_NAME==system_auto_cc_3}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_cc_4/system_auto_cc_4_ooc.xdc

# XDC: bd/system/ip/system_auto_cc_4/system_auto_cc_4_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_cc_4 || ORIG_REF_NAME==system_auto_cc_4}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc

# XDC: bd/system/ip/system_auto_us_0/system_auto_us_0_ooc.xdc

# XDC: bd/system/ip/system_auto_us_0/system_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_us_0 || ORIG_REF_NAME==system_auto_us_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_us_1/system_auto_us_1_ooc.xdc

# XDC: bd/system/ip/system_auto_us_1/system_auto_us_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_us_1 || ORIG_REF_NAME==system_auto_us_1}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_pc_2/system_auto_pc_2_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_3/system_auto_pc_3_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_4/system_auto_pc_4_ooc.xdc

# XDC: bd/system/system_ooc.xdc
