// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module filter_Filter2D (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_src_data_stream_0_V_dout,
        p_src_data_stream_0_V_empty_n,
        p_src_data_stream_0_V_read,
        p_src_data_stream_1_V_dout,
        p_src_data_stream_1_V_empty_n,
        p_src_data_stream_1_V_read,
        p_src_data_stream_2_V_dout,
        p_src_data_stream_2_V_empty_n,
        p_src_data_stream_2_V_read,
        p_dst_data_stream_0_V_din,
        p_dst_data_stream_0_V_full_n,
        p_dst_data_stream_0_V_write,
        p_dst_data_stream_1_V_din,
        p_dst_data_stream_1_V_full_n,
        p_dst_data_stream_1_V_write,
        p_dst_data_stream_2_V_din,
        p_dst_data_stream_2_V_full_n,
        p_dst_data_stream_2_V_write,
        p_kernel_val_0_V_0_read,
        p_kernel_val_0_V_1_read,
        p_kernel_val_1_V_0_read,
        p_kernel_val_1_V_2_read,
        p_kernel_val_2_V_1_read,
        p_kernel_val_2_V_2_read
);

parameter    ap_ST_st1_fsm_0 = 5'b1;
parameter    ap_ST_st2_fsm_1 = 5'b10;
parameter    ap_ST_st3_fsm_2 = 5'b100;
parameter    ap_ST_pp0_stg0_fsm_3 = 5'b1000;
parameter    ap_ST_st10_fsm_4 = 5'b10000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv2_1 = 2'b1;
parameter    ap_const_lv2_2 = 2'b10;
parameter    ap_const_lv11_43A = 11'b10000111010;
parameter    ap_const_lv11_1 = 11'b1;
parameter    ap_const_lv11_438 = 11'b10000111000;
parameter    ap_const_lv11_437 = 11'b10000110111;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv10_0 = 10'b0000000000;
parameter    ap_const_lv12_FFF = 12'b111111111111;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv12_438 = 12'b10000111000;
parameter    ap_const_lv12_1 = 12'b1;
parameter    ap_const_lv12_86E = 12'b100001101110;
parameter    ap_const_lv12_FFE = 12'b111111111110;
parameter    ap_const_lv12_FFD = 12'b111111111101;
parameter    ap_const_lv2_3 = 2'b11;
parameter    ap_const_lv11_782 = 11'b11110000010;
parameter    ap_const_lv12_780 = 12'b11110000000;
parameter    ap_const_lv13_EFE = 13'b111011111110;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv9_0 = 9'b000000000;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_lv8_FF = 8'b11111111;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] p_src_data_stream_0_V_dout;
input   p_src_data_stream_0_V_empty_n;
output   p_src_data_stream_0_V_read;
input  [7:0] p_src_data_stream_1_V_dout;
input   p_src_data_stream_1_V_empty_n;
output   p_src_data_stream_1_V_read;
input  [7:0] p_src_data_stream_2_V_dout;
input   p_src_data_stream_2_V_empty_n;
output   p_src_data_stream_2_V_read;
output  [7:0] p_dst_data_stream_0_V_din;
input   p_dst_data_stream_0_V_full_n;
output   p_dst_data_stream_0_V_write;
output  [7:0] p_dst_data_stream_1_V_din;
input   p_dst_data_stream_1_V_full_n;
output   p_dst_data_stream_1_V_write;
output  [7:0] p_dst_data_stream_2_V_din;
input   p_dst_data_stream_2_V_full_n;
output   p_dst_data_stream_2_V_write;
input  [1:0] p_kernel_val_0_V_0_read;
input  [1:0] p_kernel_val_0_V_1_read;
input  [3:0] p_kernel_val_1_V_0_read;
input  [2:0] p_kernel_val_1_V_2_read;
input  [2:0] p_kernel_val_2_V_1_read;
input  [1:0] p_kernel_val_2_V_2_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_data_stream_0_V_read;
reg p_src_data_stream_1_V_read;
reg p_src_data_stream_2_V_read;
reg p_dst_data_stream_0_V_write;
reg p_dst_data_stream_1_V_write;
reg p_dst_data_stream_2_V_write;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_22;
reg    p_src_data_stream_0_V_blk_n;
reg    ap_reg_ppiten_pp0_it2;
reg    ap_reg_ppiten_pp0_it0;
reg    ap_reg_ppiten_pp0_it1;
reg    ap_reg_ppiten_pp0_it3;
reg    ap_reg_ppiten_pp0_it4;
reg    ap_reg_ppiten_pp0_it5;
reg   [0:0] exitcond_reg_2625;
reg   [0:0] ap_reg_ppstg_exitcond_reg_2625_pp0_iter1;
reg   [0:0] or_cond_i_i_reg_2634;
reg   [0:0] ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1;
reg   [0:0] icmp_reg_2574;
reg   [0:0] tmp_5_reg_2565;
reg    p_src_data_stream_1_V_blk_n;
reg    p_src_data_stream_2_V_blk_n;
reg    p_dst_data_stream_0_V_blk_n;
reg   [0:0] or_cond_i_reg_2661;
reg   [0:0] ap_reg_ppstg_or_cond_i_reg_2661_pp0_iter4;
reg    p_dst_data_stream_1_V_blk_n;
reg    p_dst_data_stream_2_V_blk_n;
reg   [10:0] p_027_0_i_reg_560;
wire   [1:0] tmp_3_fu_571_p2;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_125;
wire  signed [9:0] OP2_V_0_0_cast_fu_583_p1;
reg  signed [9:0] OP2_V_0_0_cast_reg_2514;
wire   [0:0] tmp_4_fu_577_p2;
wire  signed [9:0] OP2_V_0_0_1_cast_fu_586_p1;
reg  signed [9:0] OP2_V_0_0_1_cast_reg_2521;
wire  signed [10:0] OP2_V_0_1_2_cast_fu_589_p1;
reg  signed [10:0] OP2_V_0_1_2_cast_reg_2528;
wire   [10:0] OP2_V_0_2_1_cast_fu_592_p1;
reg   [10:0] OP2_V_0_2_1_cast_reg_2535;
wire  signed [9:0] OP2_V_0_2_2_cast_fu_595_p1;
reg  signed [9:0] OP2_V_0_2_2_cast_reg_2542;
wire   [10:0] tmp_s_fu_598_p1;
reg   [10:0] tmp_s_reg_2549;
wire   [0:0] exitcond1_fu_605_p2;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_150;
wire   [10:0] i_V_fu_611_p2;
reg   [10:0] i_V_reg_2560;
wire   [0:0] tmp_5_fu_617_p2;
wire   [0:0] tmp_82_not_fu_623_p2;
reg   [0:0] tmp_82_not_reg_2569;
wire   [0:0] icmp_fu_639_p2;
wire   [0:0] tmp_6_fu_645_p2;
reg   [0:0] tmp_6_reg_2579;
wire   [0:0] tmp_128_0_1_fu_651_p2;
reg   [0:0] tmp_128_0_1_reg_2583;
wire   [0:0] tmp_7_fu_657_p2;
reg   [0:0] tmp_7_reg_2587;
wire   [1:0] row_assign_s_fu_813_p2;
reg   [1:0] row_assign_s_reg_2600;
wire   [1:0] row_assign_10_0_1_t_fu_845_p2;
reg   [1:0] row_assign_10_0_1_t_reg_2605;
wire   [1:0] row_assign_10_0_2_t_fu_877_p2;
reg   [1:0] row_assign_10_0_2_t_reg_2612;
wire   [1:0] row_assign_10_1_0_t_fu_913_p2;
reg   [1:0] row_assign_10_1_0_t_reg_2619;
wire   [0:0] exitcond_fu_923_p2;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_3;
reg    ap_sig_180;
reg    ap_sig_196;
reg    ap_sig_206;
reg   [0:0] ap_reg_ppstg_exitcond_reg_2625_pp0_iter2;
wire   [10:0] j_V_fu_929_p2;
wire   [0:0] or_cond_i_i_fu_981_p2;
wire   [13:0] x_fu_1059_p3;
reg   [13:0] x_reg_2638;
wire   [1:0] tmp_83_fu_1067_p1;
reg   [1:0] tmp_83_reg_2643;
reg   [1:0] ap_reg_ppstg_tmp_83_reg_2643_pp0_iter1;
wire   [0:0] brmerge_fu_1071_p2;
reg   [0:0] brmerge_reg_2648;
reg   [0:0] ap_reg_ppstg_brmerge_reg_2648_pp0_iter1;
wire   [0:0] or_cond_i_fu_1076_p2;
reg   [0:0] ap_reg_ppstg_or_cond_i_reg_2661_pp0_iter1;
reg   [0:0] ap_reg_ppstg_or_cond_i_reg_2661_pp0_iter2;
reg   [0:0] ap_reg_ppstg_or_cond_i_reg_2661_pp0_iter3;
reg   [10:0] k_buf_0_val_3_addr_reg_2665;
reg   [10:0] k_buf_0_val_4_addr_reg_2671;
reg   [10:0] k_buf_0_val_5_addr_reg_2677;
reg   [10:0] k_buf_1_val_3_addr_reg_2683;
reg   [10:0] k_buf_1_val_4_addr_reg_2689;
reg   [10:0] k_buf_1_val_5_addr_reg_2695;
reg   [10:0] k_buf_2_val_3_addr_reg_2701;
reg   [10:0] k_buf_2_val_4_addr_reg_2707;
reg   [10:0] k_buf_2_val_5_addr_reg_2713;
wire   [7:0] src_kernel_win_0_val_0_0_fu_1236_p3;
reg   [7:0] src_kernel_win_0_val_0_0_reg_2719;
wire   [7:0] src_kernel_win_0_val_1_0_fu_1254_p3;
reg   [7:0] src_kernel_win_0_val_1_0_reg_2725;
reg   [7:0] ap_reg_ppstg_src_kernel_win_0_val_1_0_reg_2725_pp0_iter3;
wire   [7:0] src_kernel_win_0_val_2_0_fu_1272_p3;
reg   [7:0] src_kernel_win_0_val_2_0_reg_2731;
wire   [9:0] p_Val2_0_0_1_fu_1286_p2;
reg  signed [9:0] p_Val2_0_0_1_reg_2736;
wire   [7:0] src_kernel_win_1_val_0_0_fu_1416_p3;
reg   [7:0] src_kernel_win_1_val_0_0_reg_2741;
wire   [7:0] src_kernel_win_1_val_1_0_fu_1434_p3;
reg   [7:0] src_kernel_win_1_val_1_0_reg_2747;
reg   [7:0] ap_reg_ppstg_src_kernel_win_1_val_1_0_reg_2747_pp0_iter3;
wire   [7:0] src_kernel_win_1_val_2_0_fu_1452_p3;
reg   [7:0] src_kernel_win_1_val_2_0_reg_2753;
wire   [9:0] p_Val2_1_0_1_fu_1466_p2;
reg  signed [9:0] p_Val2_1_0_1_reg_2758;
wire   [7:0] src_kernel_win_2_val_0_0_fu_1578_p3;
reg   [7:0] src_kernel_win_2_val_0_0_reg_2763;
wire   [7:0] src_kernel_win_2_val_1_0_fu_1596_p3;
reg   [7:0] src_kernel_win_2_val_1_0_reg_2769;
reg   [7:0] ap_reg_ppstg_src_kernel_win_2_val_1_0_reg_2769_pp0_iter3;
wire   [7:0] src_kernel_win_2_val_2_0_fu_1614_p3;
reg   [7:0] src_kernel_win_2_val_2_0_reg_2775;
wire   [9:0] p_Val2_2_0_1_fu_1628_p2;
reg  signed [9:0] p_Val2_2_0_1_reg_2780;
reg   [7:0] src_kernel_win_0_val_2_1_lo_1_reg_2785;
reg   [7:0] src_kernel_win_1_val_2_1_lo_1_reg_2790;
reg   [7:0] src_kernel_win_2_val_2_1_lo_reg_2795;
wire   [10:0] grp_fu_2150_p3;
reg  signed [10:0] p_Val2_5_0_1_1_reg_2800;
wire  signed [10:0] grp_fu_2179_p3;
reg  signed [10:0] tmp3_reg_2805;
wire   [10:0] grp_fu_2186_p3;
reg  signed [10:0] p_Val2_5_1_1_1_reg_2810;
wire  signed [10:0] grp_fu_2172_p3;
reg  signed [10:0] tmp8_reg_2815;
wire   [10:0] grp_fu_2165_p3;
reg  signed [10:0] p_Val2_5_2_1_1_reg_2820;
wire  signed [10:0] grp_fu_2217_p3;
reg  signed [10:0] tmp13_reg_2825;
wire   [7:0] p_Val2_12_fu_1974_p3;
reg   [7:0] p_Val2_12_reg_2830;
wire   [7:0] p_Val2_13_fu_2050_p3;
reg   [7:0] p_Val2_13_reg_2835;
wire   [7:0] p_Val2_14_fu_2126_p3;
reg   [7:0] p_Val2_14_reg_2840;
wire   [10:0] k_buf_0_val_3_address0;
reg    k_buf_0_val_3_ce0;
wire   [7:0] k_buf_0_val_3_q0;
reg    k_buf_0_val_3_ce1;
reg    k_buf_0_val_3_we1;
wire   [10:0] k_buf_0_val_4_address0;
reg    k_buf_0_val_4_ce0;
wire   [7:0] k_buf_0_val_4_q0;
reg    k_buf_0_val_4_ce1;
reg    k_buf_0_val_4_we1;
reg   [7:0] k_buf_0_val_4_d1;
wire   [10:0] k_buf_0_val_5_address0;
reg    k_buf_0_val_5_ce0;
wire   [7:0] k_buf_0_val_5_q0;
reg    k_buf_0_val_5_ce1;
reg    k_buf_0_val_5_we1;
reg   [7:0] k_buf_0_val_5_d1;
wire   [10:0] k_buf_1_val_3_address0;
reg    k_buf_1_val_3_ce0;
wire   [7:0] k_buf_1_val_3_q0;
reg    k_buf_1_val_3_ce1;
reg    k_buf_1_val_3_we1;
wire   [10:0] k_buf_1_val_4_address0;
reg    k_buf_1_val_4_ce0;
wire   [7:0] k_buf_1_val_4_q0;
reg    k_buf_1_val_4_ce1;
reg    k_buf_1_val_4_we1;
reg   [7:0] k_buf_1_val_4_d1;
wire   [10:0] k_buf_1_val_5_address0;
reg    k_buf_1_val_5_ce0;
wire   [7:0] k_buf_1_val_5_q0;
reg    k_buf_1_val_5_ce1;
reg    k_buf_1_val_5_we1;
reg   [7:0] k_buf_1_val_5_d1;
wire   [10:0] k_buf_2_val_3_address0;
reg    k_buf_2_val_3_ce0;
wire   [7:0] k_buf_2_val_3_q0;
reg    k_buf_2_val_3_ce1;
reg    k_buf_2_val_3_we1;
wire   [10:0] k_buf_2_val_4_address0;
reg    k_buf_2_val_4_ce0;
wire   [7:0] k_buf_2_val_4_q0;
reg    k_buf_2_val_4_ce1;
reg    k_buf_2_val_4_we1;
reg   [7:0] k_buf_2_val_4_d1;
wire   [10:0] k_buf_2_val_5_address0;
reg    k_buf_2_val_5_ce0;
wire   [7:0] k_buf_2_val_5_q0;
reg    k_buf_2_val_5_ce1;
reg    k_buf_2_val_5_we1;
reg   [7:0] k_buf_2_val_5_d1;
reg   [1:0] tmp_2_reg_538;
reg   [10:0] p_014_0_i_reg_549;
reg    ap_sig_cseq_ST_st10_fsm_4;
reg    ap_sig_441;
wire   [63:0] tmp_18_fu_1084_p1;
reg   [7:0] src_kernel_win_0_val_0_1_fu_178;
reg   [7:0] src_kernel_win_0_val_0_1_1_fu_182;
reg   [7:0] src_kernel_win_0_val_1_1_fu_186;
reg   [7:0] src_kernel_win_0_val_1_1_1_fu_190;
reg   [7:0] src_kernel_win_0_val_2_1_fu_194;
reg   [7:0] src_kernel_win_0_val_2_1_1_fu_198;
reg   [7:0] src_kernel_win_1_val_0_1_fu_202;
reg   [7:0] src_kernel_win_1_val_0_1_1_fu_206;
reg   [7:0] src_kernel_win_1_val_1_1_fu_210;
reg   [7:0] src_kernel_win_1_val_1_1_1_fu_214;
reg   [7:0] src_kernel_win_1_val_2_1_fu_218;
reg   [7:0] src_kernel_win_1_val_2_1_1_fu_222;
reg   [7:0] src_kernel_win_2_val_0_1_fu_226;
reg   [7:0] src_kernel_win_2_val_0_1_1_fu_230;
reg   [7:0] src_kernel_win_2_val_1_1_fu_234;
reg   [7:0] src_kernel_win_2_val_1_1_1_fu_238;
reg   [7:0] src_kernel_win_2_val_2_1_fu_242;
reg   [7:0] src_kernel_win_2_val_2_1_1_fu_246;
reg   [7:0] right_border_buf_0_val_0_1_fu_250;
wire   [7:0] col_buf_0_val_0_0_fu_1141_p3;
reg   [7:0] right_border_buf_0_val_0_1_1_fu_254;
reg   [7:0] right_border_buf_2_val_2_1_fu_258;
reg   [7:0] right_border_buf_0_val_1_1_fu_262;
wire   [7:0] col_buf_0_val_1_0_fu_1160_p3;
reg   [7:0] right_border_buf_0_val_1_1_1_fu_266;
reg   [7:0] right_border_buf_2_val_2_1_1_fu_270;
wire   [7:0] col_buf_2_val_2_0_fu_1530_p3;
reg   [7:0] right_border_buf_0_val_2_1_fu_274;
wire   [7:0] col_buf_0_val_2_0_fu_1179_p3;
reg   [7:0] right_border_buf_0_val_2_1_1_fu_278;
reg   [7:0] right_border_buf_2_val_1_1_fu_282;
reg   [7:0] right_border_buf_1_val_0_1_fu_286;
wire   [7:0] col_buf_1_val_0_0_fu_1321_p3;
reg   [7:0] right_border_buf_1_val_0_1_1_fu_290;
reg   [7:0] right_border_buf_2_val_1_1_1_fu_294;
wire   [7:0] col_buf_2_val_1_0_fu_1511_p3;
reg   [7:0] right_border_buf_1_val_1_1_fu_298;
wire   [7:0] col_buf_1_val_1_0_fu_1340_p3;
reg   [7:0] right_border_buf_1_val_1_1_1_fu_302;
reg   [7:0] right_border_buf_2_val_0_1_fu_306;
reg   [7:0] right_border_buf_1_val_2_1_fu_310;
wire   [7:0] col_buf_1_val_2_0_fu_1359_p3;
reg   [7:0] right_border_buf_1_val_2_1_1_fu_314;
reg   [7:0] right_border_buf_2_val_0_1_1_fu_318;
wire   [7:0] col_buf_2_val_0_0_fu_1492_p3;
wire   [9:0] tmp_fu_629_p4;
wire   [11:0] p_014_0_i_cast_fu_601_p1;
wire   [11:0] tmp_8_fu_663_p2;
wire   [0:0] tmp_55_fu_669_p3;
wire   [0:0] tmp_9_fu_683_p2;
wire   [0:0] rev_fu_677_p2;
wire   [0:0] tmp_56_fu_695_p3;
wire   [11:0] p_assign_7_fu_703_p2;
wire   [11:0] p_p2_i424_i_fu_709_p3;
wire   [11:0] p_assign_6_0_1_fu_729_p2;
wire   [11:0] p_assign_6_0_2_fu_755_p2;
wire   [11:0] p_assign_8_fu_723_p2;
wire   [0:0] tmp_10_fu_717_p2;
wire   [1:0] tmp_67_fu_789_p1;
wire   [1:0] tmp_68_fu_793_p1;
wire   [0:0] or_cond_i423_i_fu_689_p2;
wire   [1:0] tmp_66_fu_785_p1;
wire   [1:0] tmp_69_fu_797_p3;
wire   [1:0] tmp_70_fu_805_p3;
wire   [1:0] tmp_60_fu_751_p1;
wire   [0:0] tmp_59_fu_743_p3;
wire   [1:0] tmp_72_fu_823_p2;
wire   [1:0] tmp_71_fu_819_p1;
wire   [0:0] tmp_58_fu_735_p3;
wire   [1:0] tmp_73_fu_829_p3;
wire   [1:0] tmp_11_fu_837_p3;
wire   [1:0] tmp_64_fu_777_p1;
wire   [0:0] tmp_63_fu_769_p3;
wire   [1:0] tmp_75_fu_855_p2;
wire   [1:0] tmp_74_fu_851_p1;
wire   [0:0] tmp_62_fu_761_p3;
wire   [1:0] tmp_76_fu_861_p3;
wire   [1:0] tmp_12_fu_869_p3;
wire   [1:0] tmp_65_fu_781_p1;
wire   [1:0] tmp_78_fu_887_p1;
wire   [1:0] tmp_79_fu_891_p2;
wire   [1:0] tmp_77_fu_883_p1;
wire   [1:0] tmp_13_fu_897_p3;
wire   [1:0] tmp_14_fu_905_p3;
wire   [9:0] tmp_80_fu_935_p4;
wire   [11:0] p_027_0_i_cast_fu_919_p1;
wire   [11:0] ImagLoc_x_fu_951_p2;
wire   [0:0] tmp_81_fu_961_p3;
wire   [0:0] tmp_16_fu_975_p2;
wire   [0:0] rev1_fu_969_p2;
wire   [0:0] tmp_82_fu_987_p3;
wire   [11:0] p_assign_1_fu_995_p2;
wire   [11:0] p_p2_i_i_fu_1001_p3;
wire  signed [12:0] p_p2_i_i_cast_cast_fu_1013_p1;
wire   [12:0] p_assign_2_fu_1023_p2;
wire  signed [13:0] ImagLoc_x_cast_fu_957_p1;
wire   [13:0] p_assign_2_cast_fu_1029_p1;
wire   [0:0] tmp_21_not_fu_1041_p2;
wire   [0:0] tmp_17_fu_1017_p2;
wire   [0:0] sel_tmp1_fu_1047_p2;
wire   [0:0] sel_tmp2_fu_1053_p2;
wire  signed [13:0] p_p2_i_i_cast_fu_1009_p1;
wire   [13:0] sel_tmp_fu_1033_p3;
wire   [0:0] icmp1_fu_945_p2;
wire  signed [31:0] x_cast_fu_1081_p1;
wire   [1:0] col_assign_3_0_t_fu_1124_p2;
wire   [7:0] tmp_19_fu_1129_p5;
wire   [7:0] tmp_20_fu_1148_p5;
wire   [7:0] tmp_21_fu_1167_p5;
wire   [7:0] tmp_22_fu_1225_p5;
wire   [7:0] tmp_23_fu_1243_p5;
wire   [7:0] tmp_24_fu_1261_p5;
wire  signed [1:0] p_Val2_0_0_1_fu_1286_p0;
wire   [7:0] p_Val2_0_0_1_fu_1286_p1;
wire   [7:0] tmp_27_fu_1309_p5;
wire   [7:0] tmp_28_fu_1328_p5;
wire   [7:0] tmp_29_fu_1347_p5;
wire   [7:0] tmp_30_fu_1405_p5;
wire   [7:0] tmp_31_fu_1423_p5;
wire   [7:0] tmp_32_fu_1441_p5;
wire  signed [1:0] p_Val2_1_0_1_fu_1466_p0;
wire   [7:0] p_Val2_1_0_1_fu_1466_p1;
wire   [7:0] tmp_35_fu_1480_p5;
wire   [7:0] tmp_36_fu_1499_p5;
wire   [7:0] tmp_37_fu_1518_p5;
wire   [7:0] tmp_38_fu_1567_p5;
wire   [7:0] tmp_39_fu_1585_p5;
wire   [7:0] tmp_40_fu_1603_p5;
wire  signed [1:0] p_Val2_2_0_1_fu_1628_p0;
wire   [7:0] p_Val2_2_0_1_fu_1628_p1;
wire   [8:0] OP1_V_0_0_2_cast_fu_1676_p1;
wire   [8:0] p_Val2_0_0_2_fu_1679_p2;
wire  signed [10:0] tmp_172_0_0_2_cast_cast_fu_1685_p1;
wire  signed [10:0] grp_fu_2240_p3;
wire  signed [9:0] grp_fu_2209_p3;
wire   [8:0] OP1_V_1_0_2_cast_fu_1731_p1;
wire   [8:0] p_Val2_1_0_2_fu_1734_p2;
wire  signed [10:0] tmp_172_1_0_2_cast_cast_fu_1740_p1;
wire  signed [10:0] grp_fu_2193_p3;
wire  signed [9:0] grp_fu_2224_p3;
wire   [8:0] OP1_V_2_0_2_cast_fu_1786_p1;
wire   [8:0] p_Val2_2_0_2_fu_1789_p2;
wire  signed [10:0] tmp_172_2_0_2_cast_cast_fu_1795_p1;
wire  signed [10:0] grp_fu_2142_p3;
wire  signed [9:0] grp_fu_2201_p3;
wire  signed [11:0] grp_fu_2232_p3;
wire  signed [11:0] tmp3_cast_fu_1912_p1;
(* use_dsp48 = "no" *) wire   [11:0] p_Val2_1_111_fu_1915_p2;
wire   [0:0] isneg_fu_1920_p3;
wire   [3:0] tmp_26_fu_1932_p4;
wire   [0:0] not_i_i_i_fu_1948_p2;
wire   [0:0] tmp_i_i_fu_1942_p2;
wire   [0:0] overflow_fu_1954_p2;
wire   [0:0] tmp_i_i_112_fu_1968_p2;
wire   [7:0] p_mux_i_i_cast_fu_1960_p3;
wire   [7:0] p_Val2_9_fu_1928_p1;
wire  signed [11:0] grp_fu_2134_p3;
wire  signed [11:0] tmp8_cast_fu_1988_p1;
(* use_dsp48 = "no" *) wire   [11:0] p_Val2_4_fu_1991_p2;
wire   [0:0] isneg_1_fu_1996_p3;
wire   [3:0] tmp_34_fu_2008_p4;
wire   [0:0] not_i_i_i5_fu_2024_p2;
wire   [0:0] tmp_i_i4_fu_2018_p2;
wire   [0:0] overflow_1_fu_2030_p2;
wire   [0:0] tmp_i_i8_fu_2044_p2;
wire   [7:0] p_mux_i_i7_cast_fu_2036_p3;
wire   [7:0] p_Val2_10_fu_2004_p1;
wire  signed [11:0] grp_fu_2157_p3;
wire  signed [11:0] tmp13_cast_fu_2064_p1;
(* use_dsp48 = "no" *) wire   [11:0] p_Val2_s_113_fu_2067_p2;
wire   [0:0] isneg_2_fu_2072_p3;
wire   [3:0] tmp_42_fu_2084_p4;
wire   [0:0] not_i_i_i1_fu_2100_p2;
wire   [0:0] tmp_i_i1_fu_2094_p2;
wire   [0:0] overflow_2_fu_2106_p2;
wire   [0:0] tmp_i_i1_114_fu_2120_p2;
wire   [7:0] p_mux_i_i16_cast_fu_2112_p3;
wire   [7:0] p_Val2_11_fu_2080_p1;
wire  signed [2:0] grp_fu_2134_p0;
wire   [7:0] grp_fu_2134_p1;
wire  signed [1:0] grp_fu_2142_p0;
wire   [7:0] grp_fu_2142_p1;
wire   [3:0] grp_fu_2150_p0;
wire   [7:0] grp_fu_2150_p1;
wire   [10:0] grp_fu_2150_p2;
wire  signed [2:0] grp_fu_2157_p0;
wire   [7:0] grp_fu_2157_p1;
wire   [3:0] grp_fu_2165_p0;
wire   [7:0] grp_fu_2165_p1;
wire   [10:0] grp_fu_2165_p2;
wire   [2:0] grp_fu_2172_p0;
wire   [7:0] grp_fu_2172_p1;
wire   [2:0] grp_fu_2179_p0;
wire   [7:0] grp_fu_2179_p1;
wire   [3:0] grp_fu_2186_p0;
wire   [7:0] grp_fu_2186_p1;
wire   [10:0] grp_fu_2186_p2;
wire  signed [1:0] grp_fu_2193_p0;
wire   [7:0] grp_fu_2193_p1;
wire  signed [1:0] grp_fu_2201_p0;
wire   [7:0] grp_fu_2201_p1;
wire   [7:0] grp_fu_2201_p2;
wire  signed [1:0] grp_fu_2209_p0;
wire   [7:0] grp_fu_2209_p1;
wire   [7:0] grp_fu_2209_p2;
wire   [2:0] grp_fu_2217_p0;
wire   [7:0] grp_fu_2217_p1;
wire  signed [1:0] grp_fu_2224_p0;
wire   [7:0] grp_fu_2224_p1;
wire   [7:0] grp_fu_2224_p2;
wire  signed [2:0] grp_fu_2232_p0;
wire   [7:0] grp_fu_2232_p1;
wire  signed [1:0] grp_fu_2240_p0;
wire   [7:0] grp_fu_2240_p1;
reg   [4:0] ap_NS_fsm;
wire   [10:0] grp_fu_2134_p10;
wire   [9:0] grp_fu_2142_p10;
wire   [10:0] grp_fu_2150_p10;
wire   [10:0] grp_fu_2157_p10;
wire   [10:0] grp_fu_2165_p10;
wire   [10:0] grp_fu_2172_p10;
wire   [10:0] grp_fu_2179_p10;
wire   [10:0] grp_fu_2186_p10;
wire   [9:0] grp_fu_2193_p10;
wire   [9:0] grp_fu_2201_p10;
wire   [9:0] grp_fu_2201_p20;
wire   [9:0] grp_fu_2209_p10;
wire   [9:0] grp_fu_2209_p20;
wire   [10:0] grp_fu_2217_p10;
wire   [9:0] grp_fu_2224_p10;
wire   [9:0] grp_fu_2224_p20;
wire   [10:0] grp_fu_2232_p10;
wire   [9:0] grp_fu_2240_p10;
wire   [9:0] p_Val2_0_0_1_fu_1286_p10;
wire   [9:0] p_Val2_1_0_1_fu_1466_p10;
wire   [9:0] p_Val2_2_0_1_fu_1628_p10;
reg    ap_sig_1608;
reg    ap_sig_1610;
reg    ap_sig_1607;
reg    ap_sig_1613;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'b1;
#0 ap_reg_ppiten_pp0_it2 = 1'b0;
#0 ap_reg_ppiten_pp0_it0 = 1'b0;
#0 ap_reg_ppiten_pp0_it1 = 1'b0;
#0 ap_reg_ppiten_pp0_it3 = 1'b0;
#0 ap_reg_ppiten_pp0_it4 = 1'b0;
#0 ap_reg_ppiten_pp0_it5 = 1'b0;
end

filter_Filter2D_k_buf_0_val_3 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_3_address0),
    .ce0(k_buf_0_val_3_ce0),
    .q0(k_buf_0_val_3_q0),
    .address1(k_buf_0_val_3_addr_reg_2665),
    .ce1(k_buf_0_val_3_ce1),
    .we1(k_buf_0_val_3_we1),
    .d1(p_src_data_stream_0_V_dout)
);

filter_Filter2D_k_buf_0_val_3 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_4_address0),
    .ce0(k_buf_0_val_4_ce0),
    .q0(k_buf_0_val_4_q0),
    .address1(k_buf_0_val_4_addr_reg_2671),
    .ce1(k_buf_0_val_4_ce1),
    .we1(k_buf_0_val_4_we1),
    .d1(k_buf_0_val_4_d1)
);

filter_Filter2D_k_buf_0_val_3 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_5_address0),
    .ce0(k_buf_0_val_5_ce0),
    .q0(k_buf_0_val_5_q0),
    .address1(k_buf_0_val_5_addr_reg_2677),
    .ce1(k_buf_0_val_5_ce1),
    .we1(k_buf_0_val_5_we1),
    .d1(k_buf_0_val_5_d1)
);

filter_Filter2D_k_buf_0_val_3 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_1_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_3_address0),
    .ce0(k_buf_1_val_3_ce0),
    .q0(k_buf_1_val_3_q0),
    .address1(k_buf_1_val_3_addr_reg_2683),
    .ce1(k_buf_1_val_3_ce1),
    .we1(k_buf_1_val_3_we1),
    .d1(p_src_data_stream_1_V_dout)
);

filter_Filter2D_k_buf_0_val_3 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_1_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_4_address0),
    .ce0(k_buf_1_val_4_ce0),
    .q0(k_buf_1_val_4_q0),
    .address1(k_buf_1_val_4_addr_reg_2689),
    .ce1(k_buf_1_val_4_ce1),
    .we1(k_buf_1_val_4_we1),
    .d1(k_buf_1_val_4_d1)
);

filter_Filter2D_k_buf_0_val_3 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_1_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_5_address0),
    .ce0(k_buf_1_val_5_ce0),
    .q0(k_buf_1_val_5_q0),
    .address1(k_buf_1_val_5_addr_reg_2695),
    .ce1(k_buf_1_val_5_ce1),
    .we1(k_buf_1_val_5_we1),
    .d1(k_buf_1_val_5_d1)
);

filter_Filter2D_k_buf_0_val_3 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_2_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_3_address0),
    .ce0(k_buf_2_val_3_ce0),
    .q0(k_buf_2_val_3_q0),
    .address1(k_buf_2_val_3_addr_reg_2701),
    .ce1(k_buf_2_val_3_ce1),
    .we1(k_buf_2_val_3_we1),
    .d1(p_src_data_stream_2_V_dout)
);

filter_Filter2D_k_buf_0_val_3 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_2_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_4_address0),
    .ce0(k_buf_2_val_4_ce0),
    .q0(k_buf_2_val_4_q0),
    .address1(k_buf_2_val_4_addr_reg_2707),
    .ce1(k_buf_2_val_4_ce1),
    .we1(k_buf_2_val_4_we1),
    .d1(k_buf_2_val_4_d1)
);

filter_Filter2D_k_buf_0_val_3 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_2_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_5_address0),
    .ce0(k_buf_2_val_5_ce0),
    .q0(k_buf_2_val_5_q0),
    .address1(k_buf_2_val_5_addr_reg_2713),
    .ce1(k_buf_2_val_5_ce1),
    .we1(k_buf_2_val_5_we1),
    .d1(k_buf_2_val_5_d1)
);

filter_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
filter_mux_3to1_sel2_8_1_U57(
    .din1(right_border_buf_0_val_0_1_fu_250),
    .din2(right_border_buf_0_val_0_1_1_fu_254),
    .din3(ap_const_lv8_0),
    .din4(col_assign_3_0_t_fu_1124_p2),
    .dout(tmp_19_fu_1129_p5)
);

filter_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
filter_mux_3to1_sel2_8_1_U58(
    .din1(right_border_buf_0_val_1_1_fu_262),
    .din2(right_border_buf_0_val_1_1_1_fu_266),
    .din3(ap_const_lv8_0),
    .din4(col_assign_3_0_t_fu_1124_p2),
    .dout(tmp_20_fu_1148_p5)
);

filter_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
filter_mux_3to1_sel2_8_1_U59(
    .din1(right_border_buf_0_val_2_1_fu_274),
    .din2(right_border_buf_0_val_2_1_1_fu_278),
    .din3(ap_const_lv8_0),
    .din4(col_assign_3_0_t_fu_1124_p2),
    .dout(tmp_21_fu_1167_p5)
);

filter_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
filter_mux_3to1_sel2_8_1_U60(
    .din1(col_buf_0_val_0_0_fu_1141_p3),
    .din2(col_buf_0_val_1_0_fu_1160_p3),
    .din3(col_buf_0_val_2_0_fu_1179_p3),
    .din4(row_assign_s_reg_2600),
    .dout(tmp_22_fu_1225_p5)
);

filter_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
filter_mux_3to1_sel2_8_1_U61(
    .din1(col_buf_0_val_0_0_fu_1141_p3),
    .din2(col_buf_0_val_1_0_fu_1160_p3),
    .din3(col_buf_0_val_2_0_fu_1179_p3),
    .din4(row_assign_10_0_1_t_reg_2605),
    .dout(tmp_23_fu_1243_p5)
);

filter_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
filter_mux_3to1_sel2_8_1_U62(
    .din1(col_buf_0_val_0_0_fu_1141_p3),
    .din2(col_buf_0_val_1_0_fu_1160_p3),
    .din3(col_buf_0_val_2_0_fu_1179_p3),
    .din4(row_assign_10_0_2_t_reg_2612),
    .dout(tmp_24_fu_1261_p5)
);

filter_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
filter_mux_3to1_sel2_8_1_U63(
    .din1(right_border_buf_1_val_0_1_fu_286),
    .din2(right_border_buf_1_val_0_1_1_fu_290),
    .din3(ap_const_lv8_0),
    .din4(col_assign_3_0_t_fu_1124_p2),
    .dout(tmp_27_fu_1309_p5)
);

filter_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
filter_mux_3to1_sel2_8_1_U64(
    .din1(right_border_buf_1_val_1_1_fu_298),
    .din2(right_border_buf_1_val_1_1_1_fu_302),
    .din3(ap_const_lv8_0),
    .din4(col_assign_3_0_t_fu_1124_p2),
    .dout(tmp_28_fu_1328_p5)
);

filter_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
filter_mux_3to1_sel2_8_1_U65(
    .din1(right_border_buf_1_val_2_1_fu_310),
    .din2(right_border_buf_1_val_2_1_1_fu_314),
    .din3(ap_const_lv8_0),
    .din4(col_assign_3_0_t_fu_1124_p2),
    .dout(tmp_29_fu_1347_p5)
);

filter_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
filter_mux_3to1_sel2_8_1_U66(
    .din1(col_buf_1_val_0_0_fu_1321_p3),
    .din2(col_buf_1_val_1_0_fu_1340_p3),
    .din3(col_buf_1_val_2_0_fu_1359_p3),
    .din4(row_assign_10_1_0_t_reg_2619),
    .dout(tmp_30_fu_1405_p5)
);

filter_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
filter_mux_3to1_sel2_8_1_U67(
    .din1(col_buf_1_val_0_0_fu_1321_p3),
    .din2(col_buf_1_val_1_0_fu_1340_p3),
    .din3(col_buf_1_val_2_0_fu_1359_p3),
    .din4(row_assign_10_0_1_t_reg_2605),
    .dout(tmp_31_fu_1423_p5)
);

filter_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
filter_mux_3to1_sel2_8_1_U68(
    .din1(col_buf_1_val_0_0_fu_1321_p3),
    .din2(col_buf_1_val_1_0_fu_1340_p3),
    .din3(col_buf_1_val_2_0_fu_1359_p3),
    .din4(row_assign_10_0_2_t_reg_2612),
    .dout(tmp_32_fu_1441_p5)
);

filter_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
filter_mux_3to1_sel2_8_1_U69(
    .din1(right_border_buf_2_val_0_1_1_fu_318),
    .din2(right_border_buf_2_val_0_1_fu_306),
    .din3(ap_const_lv8_0),
    .din4(col_assign_3_0_t_fu_1124_p2),
    .dout(tmp_35_fu_1480_p5)
);

filter_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
filter_mux_3to1_sel2_8_1_U70(
    .din1(right_border_buf_2_val_1_1_1_fu_294),
    .din2(right_border_buf_2_val_1_1_fu_282),
    .din3(ap_const_lv8_0),
    .din4(col_assign_3_0_t_fu_1124_p2),
    .dout(tmp_36_fu_1499_p5)
);

filter_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
filter_mux_3to1_sel2_8_1_U71(
    .din1(right_border_buf_2_val_2_1_1_fu_270),
    .din2(right_border_buf_2_val_2_1_fu_258),
    .din3(ap_const_lv8_0),
    .din4(col_assign_3_0_t_fu_1124_p2),
    .dout(tmp_37_fu_1518_p5)
);

filter_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
filter_mux_3to1_sel2_8_1_U72(
    .din1(col_buf_2_val_0_0_fu_1492_p3),
    .din2(col_buf_2_val_1_0_fu_1511_p3),
    .din3(col_buf_2_val_2_0_fu_1530_p3),
    .din4(row_assign_10_1_0_t_reg_2619),
    .dout(tmp_38_fu_1567_p5)
);

filter_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
filter_mux_3to1_sel2_8_1_U73(
    .din1(col_buf_2_val_0_0_fu_1492_p3),
    .din2(col_buf_2_val_1_0_fu_1511_p3),
    .din3(col_buf_2_val_2_0_fu_1530_p3),
    .din4(row_assign_10_0_1_t_reg_2605),
    .dout(tmp_39_fu_1585_p5)
);

filter_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
filter_mux_3to1_sel2_8_1_U74(
    .din1(col_buf_2_val_0_0_fu_1492_p3),
    .din2(col_buf_2_val_1_0_fu_1511_p3),
    .din3(col_buf_2_val_2_0_fu_1530_p3),
    .din4(row_assign_10_0_2_t_reg_2612),
    .dout(tmp_40_fu_1603_p5)
);

filter_mac_muladd_3s_8ns_11s_12_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 11 ),
    .dout_WIDTH( 12 ))
filter_mac_muladd_3s_8ns_11s_12_1_U75(
    .din0(grp_fu_2134_p0),
    .din1(grp_fu_2134_p1),
    .din2(p_Val2_5_1_1_1_reg_2810),
    .dout(grp_fu_2134_p3)
);

filter_mac_muladd_2s_8ns_10s_11_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 10 ),
    .dout_WIDTH( 11 ))
filter_mac_muladd_2s_8ns_10s_11_1_U76(
    .din0(grp_fu_2142_p0),
    .din1(grp_fu_2142_p1),
    .din2(p_Val2_2_0_1_reg_2780),
    .dout(grp_fu_2142_p3)
);

filter_mac_muladd_4ns_8ns_11ns_11_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 11 ),
    .dout_WIDTH( 11 ))
filter_mac_muladd_4ns_8ns_11ns_11_1_U77(
    .din0(grp_fu_2150_p0),
    .din1(grp_fu_2150_p1),
    .din2(grp_fu_2150_p2),
    .dout(grp_fu_2150_p3)
);

filter_mac_muladd_3s_8ns_11s_12_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 11 ),
    .dout_WIDTH( 12 ))
filter_mac_muladd_3s_8ns_11s_12_1_U78(
    .din0(grp_fu_2157_p0),
    .din1(grp_fu_2157_p1),
    .din2(p_Val2_5_2_1_1_reg_2820),
    .dout(grp_fu_2157_p3)
);

filter_mac_muladd_4ns_8ns_11ns_11_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 11 ),
    .dout_WIDTH( 11 ))
filter_mac_muladd_4ns_8ns_11ns_11_1_U79(
    .din0(grp_fu_2165_p0),
    .din1(grp_fu_2165_p1),
    .din2(grp_fu_2165_p2),
    .dout(grp_fu_2165_p3)
);

filter_mac_muladd_3ns_8ns_10s_11_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 10 ),
    .dout_WIDTH( 11 ))
filter_mac_muladd_3ns_8ns_10s_11_1_U80(
    .din0(grp_fu_2172_p0),
    .din1(grp_fu_2172_p1),
    .din2(grp_fu_2224_p3),
    .dout(grp_fu_2172_p3)
);

filter_mac_muladd_3ns_8ns_10s_11_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 10 ),
    .dout_WIDTH( 11 ))
filter_mac_muladd_3ns_8ns_10s_11_1_U81(
    .din0(grp_fu_2179_p0),
    .din1(grp_fu_2179_p1),
    .din2(grp_fu_2209_p3),
    .dout(grp_fu_2179_p3)
);

filter_mac_muladd_4ns_8ns_11ns_11_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 11 ),
    .dout_WIDTH( 11 ))
filter_mac_muladd_4ns_8ns_11ns_11_1_U82(
    .din0(grp_fu_2186_p0),
    .din1(grp_fu_2186_p1),
    .din2(grp_fu_2186_p2),
    .dout(grp_fu_2186_p3)
);

filter_mac_muladd_2s_8ns_10s_11_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 10 ),
    .dout_WIDTH( 11 ))
filter_mac_muladd_2s_8ns_10s_11_1_U83(
    .din0(grp_fu_2193_p0),
    .din1(grp_fu_2193_p1),
    .din2(p_Val2_1_0_1_reg_2758),
    .dout(grp_fu_2193_p3)
);

filter_mac_muladd_2s_8ns_8ns_10_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .dout_WIDTH( 10 ))
filter_mac_muladd_2s_8ns_8ns_10_1_U84(
    .din0(grp_fu_2201_p0),
    .din1(grp_fu_2201_p1),
    .din2(grp_fu_2201_p2),
    .dout(grp_fu_2201_p3)
);

filter_mac_muladd_2s_8ns_8ns_10_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .dout_WIDTH( 10 ))
filter_mac_muladd_2s_8ns_8ns_10_1_U85(
    .din0(grp_fu_2209_p0),
    .din1(grp_fu_2209_p1),
    .din2(grp_fu_2209_p2),
    .dout(grp_fu_2209_p3)
);

filter_mac_muladd_3ns_8ns_10s_11_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 10 ),
    .dout_WIDTH( 11 ))
filter_mac_muladd_3ns_8ns_10s_11_1_U86(
    .din0(grp_fu_2217_p0),
    .din1(grp_fu_2217_p1),
    .din2(grp_fu_2201_p3),
    .dout(grp_fu_2217_p3)
);

filter_mac_muladd_2s_8ns_8ns_10_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .dout_WIDTH( 10 ))
filter_mac_muladd_2s_8ns_8ns_10_1_U87(
    .din0(grp_fu_2224_p0),
    .din1(grp_fu_2224_p1),
    .din2(grp_fu_2224_p2),
    .dout(grp_fu_2224_p3)
);

filter_mac_muladd_3s_8ns_11s_12_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 11 ),
    .dout_WIDTH( 12 ))
filter_mac_muladd_3s_8ns_11s_12_1_U88(
    .din0(grp_fu_2232_p0),
    .din1(grp_fu_2232_p1),
    .din2(p_Val2_5_0_1_1_reg_2800),
    .dout(grp_fu_2232_p3)
);

filter_mac_muladd_2s_8ns_10s_11_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 10 ),
    .dout_WIDTH( 11 ))
filter_mac_muladd_2s_8ns_10s_11_1_U89(
    .din0(grp_fu_2240_p0),
    .din1(grp_fu_2240_p1),
    .din2(p_Val2_0_0_1_reg_2736),
    .dout(grp_fu_2240_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b0 == exitcond_fu_923_p2))) begin
            ap_reg_ppiten_pp0_it0 <= 1'b0;
        end else if (((1'b1 == ap_sig_cseq_ST_st3_fsm_2) & (1'b0 == exitcond1_fu_605_p2))) begin
            ap_reg_ppiten_pp0_it0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)))) begin
            ap_reg_ppiten_pp0_it1 <= ap_reg_ppiten_pp0_it0;
        end else if (((1'b1 == ap_sig_cseq_ST_st3_fsm_2) & (1'b0 == exitcond1_fu_605_p2))) begin
            ap_reg_ppiten_pp0_it1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it3 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) begin
            if (~(1'b1 == ap_reg_ppiten_pp0_it1)) begin
                ap_reg_ppiten_pp0_it3 <= 1'b0;
            end else if ((1'b1 == ap_reg_ppiten_pp0_it1)) begin
                ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it4 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) begin
            ap_reg_ppiten_pp0_it4 <= ap_reg_ppiten_pp0_it3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it5 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) begin
            ap_reg_ppiten_pp0_it5 <= ap_reg_ppiten_pp0_it4;
        end else if (((1'b1 == ap_sig_cseq_ST_st3_fsm_2) & (1'b0 == exitcond1_fu_605_p2))) begin
            ap_reg_ppiten_pp0_it5 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st10_fsm_4)) begin
        p_014_0_i_reg_549 <= i_V_reg_2560;
    end else if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == tmp_4_fu_577_p2))) begin
        p_014_0_i_reg_549 <= ap_const_lv11_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & (1'b0 == exitcond_fu_923_p2))) begin
        p_027_0_i_reg_560 <= j_V_fu_929_p2;
    end else if (((1'b1 == ap_sig_cseq_ST_st3_fsm_2) & (1'b0 == exitcond1_fu_605_p2))) begin
        p_027_0_i_reg_560 <= ap_const_lv11_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        tmp_2_reg_538 <= ap_const_lv2_0;
    end else if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (1'b0 == tmp_4_fu_577_p2))) begin
        tmp_2_reg_538 <= tmp_3_fu_571_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == tmp_4_fu_577_p2))) begin
        OP2_V_0_0_1_cast_reg_2521 <= OP2_V_0_0_1_cast_fu_586_p1;
        OP2_V_0_0_cast_reg_2514 <= OP2_V_0_0_cast_fu_583_p1;
        OP2_V_0_1_2_cast_reg_2528 <= OP2_V_0_1_2_cast_fu_589_p1;
        OP2_V_0_2_1_cast_reg_2535[2 : 0] <= OP2_V_0_2_1_cast_fu_592_p1[2 : 0];
        OP2_V_0_2_2_cast_reg_2542 <= OP2_V_0_2_2_cast_fu_595_p1;
        tmp_s_reg_2549[3 : 0] <= tmp_s_fu_598_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)))) begin
        ap_reg_ppstg_brmerge_reg_2648_pp0_iter1 <= brmerge_reg_2648;
        ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 <= exitcond_reg_2625;
        ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1 <= or_cond_i_i_reg_2634;
        ap_reg_ppstg_or_cond_i_reg_2661_pp0_iter1 <= or_cond_i_reg_2661;
        ap_reg_ppstg_tmp_83_reg_2643_pp0_iter1 <= tmp_83_reg_2643;
        exitcond_reg_2625 <= exitcond_fu_923_p2;
    end
end

always @ (posedge ap_clk) begin
    if (~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) begin
        ap_reg_ppstg_exitcond_reg_2625_pp0_iter2 <= ap_reg_ppstg_exitcond_reg_2625_pp0_iter1;
        ap_reg_ppstg_or_cond_i_reg_2661_pp0_iter2 <= ap_reg_ppstg_or_cond_i_reg_2661_pp0_iter1;
        ap_reg_ppstg_or_cond_i_reg_2661_pp0_iter3 <= ap_reg_ppstg_or_cond_i_reg_2661_pp0_iter2;
        ap_reg_ppstg_or_cond_i_reg_2661_pp0_iter4 <= ap_reg_ppstg_or_cond_i_reg_2661_pp0_iter3;
        ap_reg_ppstg_src_kernel_win_0_val_1_0_reg_2725_pp0_iter3 <= src_kernel_win_0_val_1_0_reg_2725;
        ap_reg_ppstg_src_kernel_win_1_val_1_0_reg_2747_pp0_iter3 <= src_kernel_win_1_val_1_0_reg_2747;
        ap_reg_ppstg_src_kernel_win_2_val_1_0_reg_2769_pp0_iter3 <= src_kernel_win_2_val_1_0_reg_2769;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & (1'b0 == exitcond_fu_923_p2))) begin
        brmerge_reg_2648 <= brmerge_fu_1071_p2;
        or_cond_i_i_reg_2634 <= or_cond_i_i_fu_981_p2;
        or_cond_i_reg_2661 <= or_cond_i_fu_1076_p2;
        tmp_83_reg_2643 <= tmp_83_fu_1067_p1;
        x_reg_2638 <= x_fu_1059_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        i_V_reg_2560 <= i_V_fu_611_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st3_fsm_2) & (1'b0 == exitcond1_fu_605_p2))) begin
        icmp_reg_2574 <= icmp_fu_639_p2;
        row_assign_10_0_1_t_reg_2605 <= row_assign_10_0_1_t_fu_845_p2;
        row_assign_10_0_2_t_reg_2612 <= row_assign_10_0_2_t_fu_877_p2;
        row_assign_10_1_0_t_reg_2619 <= row_assign_10_1_0_t_fu_913_p2;
        row_assign_s_reg_2600 <= row_assign_s_fu_813_p2;
        tmp_128_0_1_reg_2583 <= tmp_128_0_1_fu_651_p2;
        tmp_5_reg_2565 <= tmp_5_fu_617_p2;
        tmp_6_reg_2579 <= tmp_6_fu_645_p2;
        tmp_7_reg_2587 <= tmp_7_fu_657_p2;
        tmp_82_not_reg_2569 <= tmp_82_not_fu_623_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & (exitcond_reg_2625 == 1'b0))) begin
        k_buf_0_val_3_addr_reg_2665 <= tmp_18_fu_1084_p1;
        k_buf_0_val_4_addr_reg_2671 <= tmp_18_fu_1084_p1;
        k_buf_0_val_5_addr_reg_2677 <= tmp_18_fu_1084_p1;
        k_buf_1_val_3_addr_reg_2683 <= tmp_18_fu_1084_p1;
        k_buf_1_val_4_addr_reg_2689 <= tmp_18_fu_1084_p1;
        k_buf_1_val_5_addr_reg_2695 <= tmp_18_fu_1084_p1;
        k_buf_2_val_3_addr_reg_2701 <= tmp_18_fu_1084_p1;
        k_buf_2_val_4_addr_reg_2707 <= tmp_18_fu_1084_p1;
        k_buf_2_val_5_addr_reg_2713 <= tmp_18_fu_1084_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b0 == ap_reg_ppstg_or_cond_i_reg_2661_pp0_iter1))) begin
        p_Val2_0_0_1_reg_2736 <= p_Val2_0_0_1_fu_1286_p2;
        p_Val2_1_0_1_reg_2758 <= p_Val2_1_0_1_fu_1466_p2;
        p_Val2_2_0_1_reg_2780 <= p_Val2_2_0_1_fu_1628_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b0 == ap_reg_ppstg_or_cond_i_reg_2661_pp0_iter3))) begin
        p_Val2_12_reg_2830 <= p_Val2_12_fu_1974_p3;
        p_Val2_13_reg_2835 <= p_Val2_13_fu_2050_p3;
        p_Val2_14_reg_2840 <= p_Val2_14_fu_2126_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it3) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b0 == ap_reg_ppstg_or_cond_i_reg_2661_pp0_iter2))) begin
        p_Val2_5_0_1_1_reg_2800 <= grp_fu_2150_p3;
        p_Val2_5_1_1_1_reg_2810 <= grp_fu_2186_p3;
        p_Val2_5_2_1_1_reg_2820 <= grp_fu_2165_p3;
        tmp13_reg_2825 <= grp_fu_2217_p3;
        tmp3_reg_2805 <= grp_fu_2179_p3;
        tmp8_reg_2815 <= grp_fu_2172_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & ~(1'b0 == icmp_reg_2574) & ~(1'b0 == tmp_5_reg_2565) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)))) begin
        right_border_buf_0_val_0_1_1_fu_254 <= right_border_buf_0_val_0_1_fu_250;
        right_border_buf_0_val_0_1_fu_250 <= col_buf_0_val_0_0_fu_1141_p3;
        right_border_buf_0_val_1_1_1_fu_266 <= right_border_buf_0_val_1_1_fu_262;
        right_border_buf_0_val_1_1_fu_262 <= col_buf_0_val_1_0_fu_1160_p3;
        right_border_buf_0_val_2_1_1_fu_278 <= right_border_buf_0_val_2_1_fu_274;
        right_border_buf_0_val_2_1_fu_274 <= col_buf_0_val_2_0_fu_1179_p3;
        right_border_buf_1_val_0_1_1_fu_290 <= right_border_buf_1_val_0_1_fu_286;
        right_border_buf_1_val_0_1_fu_286 <= col_buf_1_val_0_0_fu_1321_p3;
        right_border_buf_1_val_1_1_1_fu_302 <= right_border_buf_1_val_1_1_fu_298;
        right_border_buf_1_val_1_1_fu_298 <= col_buf_1_val_1_0_fu_1340_p3;
        right_border_buf_1_val_2_1_1_fu_314 <= right_border_buf_1_val_2_1_fu_310;
        right_border_buf_1_val_2_1_fu_310 <= col_buf_1_val_2_0_fu_1359_p3;
        right_border_buf_2_val_0_1_1_fu_318 <= col_buf_2_val_0_0_fu_1492_p3;
        right_border_buf_2_val_0_1_fu_306 <= right_border_buf_2_val_0_1_1_fu_318;
        right_border_buf_2_val_1_1_1_fu_294 <= col_buf_2_val_1_0_fu_1511_p3;
        right_border_buf_2_val_1_1_fu_282 <= right_border_buf_2_val_1_1_1_fu_294;
        right_border_buf_2_val_2_1_1_fu_270 <= col_buf_2_val_2_0_fu_1530_p3;
        right_border_buf_2_val_2_1_fu_258 <= right_border_buf_2_val_2_1_1_fu_270;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)))) begin
        src_kernel_win_0_val_0_0_reg_2719 <= src_kernel_win_0_val_0_0_fu_1236_p3;
        src_kernel_win_0_val_1_0_reg_2725 <= src_kernel_win_0_val_1_0_fu_1254_p3;
        src_kernel_win_0_val_2_0_reg_2731 <= src_kernel_win_0_val_2_0_fu_1272_p3;
        src_kernel_win_0_val_2_1_lo_1_reg_2785 <= src_kernel_win_0_val_2_1_fu_194;
        src_kernel_win_1_val_0_0_reg_2741 <= src_kernel_win_1_val_0_0_fu_1416_p3;
        src_kernel_win_1_val_1_0_reg_2747 <= src_kernel_win_1_val_1_0_fu_1434_p3;
        src_kernel_win_1_val_2_0_reg_2753 <= src_kernel_win_1_val_2_0_fu_1452_p3;
        src_kernel_win_1_val_2_1_lo_1_reg_2790 <= src_kernel_win_1_val_2_1_fu_218;
        src_kernel_win_2_val_0_0_reg_2763 <= src_kernel_win_2_val_0_0_fu_1578_p3;
        src_kernel_win_2_val_1_0_reg_2769 <= src_kernel_win_2_val_1_0_fu_1596_p3;
        src_kernel_win_2_val_2_0_reg_2775 <= src_kernel_win_2_val_2_0_fu_1614_p3;
        src_kernel_win_2_val_2_1_lo_reg_2795 <= src_kernel_win_2_val_2_1_fu_242;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it3) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & (1'b0 == ap_reg_ppstg_exitcond_reg_2625_pp0_iter2))) begin
        src_kernel_win_0_val_0_1_1_fu_182 <= src_kernel_win_0_val_0_1_fu_178;
        src_kernel_win_0_val_0_1_fu_178 <= src_kernel_win_0_val_0_0_reg_2719;
        src_kernel_win_0_val_1_1_1_fu_190 <= src_kernel_win_0_val_1_1_fu_186;
        src_kernel_win_0_val_1_1_fu_186 <= src_kernel_win_0_val_1_0_reg_2725;
        src_kernel_win_0_val_2_1_1_fu_198 <= src_kernel_win_0_val_2_1_lo_1_reg_2785;
        src_kernel_win_1_val_0_1_1_fu_206 <= src_kernel_win_1_val_0_1_fu_202;
        src_kernel_win_1_val_0_1_fu_202 <= src_kernel_win_1_val_0_0_reg_2741;
        src_kernel_win_1_val_1_1_1_fu_214 <= src_kernel_win_1_val_1_1_fu_210;
        src_kernel_win_1_val_1_1_fu_210 <= src_kernel_win_1_val_1_0_reg_2747;
        src_kernel_win_1_val_2_1_1_fu_222 <= src_kernel_win_1_val_2_1_lo_1_reg_2790;
        src_kernel_win_2_val_0_1_1_fu_230 <= src_kernel_win_2_val_0_1_fu_226;
        src_kernel_win_2_val_0_1_fu_226 <= src_kernel_win_2_val_0_0_reg_2763;
        src_kernel_win_2_val_1_1_1_fu_238 <= src_kernel_win_2_val_1_1_fu_234;
        src_kernel_win_2_val_1_1_fu_234 <= src_kernel_win_2_val_1_0_reg_2769;
        src_kernel_win_2_val_2_1_1_fu_246 <= src_kernel_win_2_val_2_1_lo_reg_2795;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)))) begin
        src_kernel_win_0_val_2_1_fu_194 <= src_kernel_win_0_val_2_0_fu_1272_p3;
        src_kernel_win_1_val_2_1_fu_218 <= src_kernel_win_1_val_2_0_fu_1452_p3;
        src_kernel_win_2_val_2_1_fu_242 <= src_kernel_win_2_val_2_0_fu_1614_p3;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_st1_fsm_0)) | ((1'b1 == ap_sig_cseq_ST_st3_fsm_2) & ~(1'b0 == exitcond1_fu_605_p2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st3_fsm_2) & ~(1'b0 == exitcond1_fu_605_p2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_180) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_3 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_3 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_441) begin
        ap_sig_cseq_ST_st10_fsm_4 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st10_fsm_4 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_22) begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_125) begin
        ap_sig_cseq_ST_st2_fsm_1 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_150) begin
        ap_sig_cseq_ST_st3_fsm_2 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)))) begin
        k_buf_0_val_3_ce0 = 1'b1;
    end else begin
        k_buf_0_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & ~(1'b0 == icmp_reg_2574) & ~(1'b0 == tmp_5_reg_2565) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & (1'b0 == icmp_reg_2574) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b0 == tmp_6_reg_2579)))) begin
        k_buf_0_val_3_ce1 = 1'b1;
    end else begin
        k_buf_0_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & ~(1'b0 == icmp_reg_2574) & ~(1'b0 == tmp_5_reg_2565) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & (1'b0 == icmp_reg_2574) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b0 == tmp_6_reg_2579)))) begin
        k_buf_0_val_3_we1 = 1'b1;
    end else begin
        k_buf_0_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)))) begin
        k_buf_0_val_4_ce0 = 1'b1;
    end else begin
        k_buf_0_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & ~(1'b0 == icmp_reg_2574) & ~(1'b0 == tmp_5_reg_2565) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & (1'b0 == icmp_reg_2574) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b0 == tmp_128_0_1_reg_2583)))) begin
        k_buf_0_val_4_ce1 = 1'b1;
    end else begin
        k_buf_0_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_1607) begin
        if (ap_sig_1610) begin
            k_buf_0_val_4_d1 = k_buf_0_val_3_q0;
        end else if (ap_sig_1608) begin
            k_buf_0_val_4_d1 = p_src_data_stream_0_V_dout;
        end else begin
            k_buf_0_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & ~(1'b0 == icmp_reg_2574) & ~(1'b0 == tmp_5_reg_2565) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & (1'b0 == icmp_reg_2574) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b0 == tmp_128_0_1_reg_2583)))) begin
        k_buf_0_val_4_we1 = 1'b1;
    end else begin
        k_buf_0_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)))) begin
        k_buf_0_val_5_ce0 = 1'b1;
    end else begin
        k_buf_0_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & ~(1'b0 == icmp_reg_2574) & ~(1'b0 == tmp_5_reg_2565) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & (1'b0 == icmp_reg_2574) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b0 == tmp_6_reg_2579)))) begin
        k_buf_0_val_5_ce1 = 1'b1;
    end else begin
        k_buf_0_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_1607) begin
        if (ap_sig_1610) begin
            k_buf_0_val_5_d1 = k_buf_0_val_4_q0;
        end else if (ap_sig_1613) begin
            k_buf_0_val_5_d1 = p_src_data_stream_0_V_dout;
        end else begin
            k_buf_0_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & ~(1'b0 == icmp_reg_2574) & ~(1'b0 == tmp_5_reg_2565) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & (1'b0 == icmp_reg_2574) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b0 == tmp_6_reg_2579)))) begin
        k_buf_0_val_5_we1 = 1'b1;
    end else begin
        k_buf_0_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)))) begin
        k_buf_1_val_3_ce0 = 1'b1;
    end else begin
        k_buf_1_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & ~(1'b0 == icmp_reg_2574) & ~(1'b0 == tmp_5_reg_2565) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & (1'b0 == icmp_reg_2574) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b0 == tmp_6_reg_2579)))) begin
        k_buf_1_val_3_ce1 = 1'b1;
    end else begin
        k_buf_1_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & ~(1'b0 == icmp_reg_2574) & ~(1'b0 == tmp_5_reg_2565) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & (1'b0 == icmp_reg_2574) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b0 == tmp_6_reg_2579)))) begin
        k_buf_1_val_3_we1 = 1'b1;
    end else begin
        k_buf_1_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)))) begin
        k_buf_1_val_4_ce0 = 1'b1;
    end else begin
        k_buf_1_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & ~(1'b0 == icmp_reg_2574) & ~(1'b0 == tmp_5_reg_2565) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & (1'b0 == icmp_reg_2574) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b0 == tmp_128_0_1_reg_2583)))) begin
        k_buf_1_val_4_ce1 = 1'b1;
    end else begin
        k_buf_1_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_1607) begin
        if (ap_sig_1610) begin
            k_buf_1_val_4_d1 = k_buf_1_val_3_q0;
        end else if (ap_sig_1608) begin
            k_buf_1_val_4_d1 = p_src_data_stream_1_V_dout;
        end else begin
            k_buf_1_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_1_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & ~(1'b0 == icmp_reg_2574) & ~(1'b0 == tmp_5_reg_2565) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & (1'b0 == icmp_reg_2574) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b0 == tmp_128_0_1_reg_2583)))) begin
        k_buf_1_val_4_we1 = 1'b1;
    end else begin
        k_buf_1_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)))) begin
        k_buf_1_val_5_ce0 = 1'b1;
    end else begin
        k_buf_1_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & ~(1'b0 == icmp_reg_2574) & ~(1'b0 == tmp_5_reg_2565) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & (1'b0 == icmp_reg_2574) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b0 == tmp_6_reg_2579)))) begin
        k_buf_1_val_5_ce1 = 1'b1;
    end else begin
        k_buf_1_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_1607) begin
        if (ap_sig_1610) begin
            k_buf_1_val_5_d1 = k_buf_1_val_4_q0;
        end else if (ap_sig_1613) begin
            k_buf_1_val_5_d1 = p_src_data_stream_1_V_dout;
        end else begin
            k_buf_1_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_1_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & ~(1'b0 == icmp_reg_2574) & ~(1'b0 == tmp_5_reg_2565) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & (1'b0 == icmp_reg_2574) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b0 == tmp_6_reg_2579)))) begin
        k_buf_1_val_5_we1 = 1'b1;
    end else begin
        k_buf_1_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)))) begin
        k_buf_2_val_3_ce0 = 1'b1;
    end else begin
        k_buf_2_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & ~(1'b0 == icmp_reg_2574) & ~(1'b0 == tmp_5_reg_2565) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & (1'b0 == icmp_reg_2574) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b0 == tmp_6_reg_2579)))) begin
        k_buf_2_val_3_ce1 = 1'b1;
    end else begin
        k_buf_2_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & ~(1'b0 == icmp_reg_2574) & ~(1'b0 == tmp_5_reg_2565) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & (1'b0 == icmp_reg_2574) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b0 == tmp_6_reg_2579)))) begin
        k_buf_2_val_3_we1 = 1'b1;
    end else begin
        k_buf_2_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)))) begin
        k_buf_2_val_4_ce0 = 1'b1;
    end else begin
        k_buf_2_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & ~(1'b0 == icmp_reg_2574) & ~(1'b0 == tmp_5_reg_2565) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & (1'b0 == icmp_reg_2574) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b0 == tmp_128_0_1_reg_2583)))) begin
        k_buf_2_val_4_ce1 = 1'b1;
    end else begin
        k_buf_2_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_1607) begin
        if (ap_sig_1610) begin
            k_buf_2_val_4_d1 = k_buf_2_val_3_q0;
        end else if (ap_sig_1608) begin
            k_buf_2_val_4_d1 = p_src_data_stream_2_V_dout;
        end else begin
            k_buf_2_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_2_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & ~(1'b0 == icmp_reg_2574) & ~(1'b0 == tmp_5_reg_2565) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & (1'b0 == icmp_reg_2574) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b0 == tmp_128_0_1_reg_2583)))) begin
        k_buf_2_val_4_we1 = 1'b1;
    end else begin
        k_buf_2_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)))) begin
        k_buf_2_val_5_ce0 = 1'b1;
    end else begin
        k_buf_2_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & ~(1'b0 == icmp_reg_2574) & ~(1'b0 == tmp_5_reg_2565) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & (1'b0 == icmp_reg_2574) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b0 == tmp_6_reg_2579)))) begin
        k_buf_2_val_5_ce1 = 1'b1;
    end else begin
        k_buf_2_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_1607) begin
        if (ap_sig_1610) begin
            k_buf_2_val_5_d1 = k_buf_2_val_4_q0;
        end else if (ap_sig_1613) begin
            k_buf_2_val_5_d1 = p_src_data_stream_2_V_dout;
        end else begin
            k_buf_2_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_2_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & ~(1'b0 == icmp_reg_2574) & ~(1'b0 == tmp_5_reg_2565) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & (1'b0 == icmp_reg_2574) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b0 == tmp_6_reg_2579)))) begin
        k_buf_2_val_5_we1 = 1'b1;
    end else begin
        k_buf_2_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it5) & ~(1'b0 == ap_reg_ppstg_or_cond_i_reg_2661_pp0_iter4))) begin
        p_dst_data_stream_0_V_blk_n = p_dst_data_stream_0_V_full_n;
    end else begin
        p_dst_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it5) & ~(1'b0 == ap_reg_ppstg_or_cond_i_reg_2661_pp0_iter4) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)))) begin
        p_dst_data_stream_0_V_write = 1'b1;
    end else begin
        p_dst_data_stream_0_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it5) & ~(1'b0 == ap_reg_ppstg_or_cond_i_reg_2661_pp0_iter4))) begin
        p_dst_data_stream_1_V_blk_n = p_dst_data_stream_1_V_full_n;
    end else begin
        p_dst_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it5) & ~(1'b0 == ap_reg_ppstg_or_cond_i_reg_2661_pp0_iter4) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)))) begin
        p_dst_data_stream_1_V_write = 1'b1;
    end else begin
        p_dst_data_stream_1_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it5) & ~(1'b0 == ap_reg_ppstg_or_cond_i_reg_2661_pp0_iter4))) begin
        p_dst_data_stream_2_V_blk_n = p_dst_data_stream_2_V_full_n;
    end else begin
        p_dst_data_stream_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it5) & ~(1'b0 == ap_reg_ppstg_or_cond_i_reg_2661_pp0_iter4) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)))) begin
        p_dst_data_stream_2_V_write = 1'b1;
    end else begin
        p_dst_data_stream_2_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & ~(1'b0 == icmp_reg_2574) & ~(1'b0 == tmp_5_reg_2565)) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & (1'b0 == icmp_reg_2574)))) begin
        p_src_data_stream_0_V_blk_n = p_src_data_stream_0_V_empty_n;
    end else begin
        p_src_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & (1'b0 == icmp_reg_2574) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & ~(1'b0 == icmp_reg_2574) & ~(1'b0 == tmp_5_reg_2565) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))))) begin
        p_src_data_stream_0_V_read = 1'b1;
    end else begin
        p_src_data_stream_0_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & ~(1'b0 == icmp_reg_2574) & ~(1'b0 == tmp_5_reg_2565)) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & (1'b0 == icmp_reg_2574)))) begin
        p_src_data_stream_1_V_blk_n = p_src_data_stream_1_V_empty_n;
    end else begin
        p_src_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & (1'b0 == icmp_reg_2574) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & ~(1'b0 == icmp_reg_2574) & ~(1'b0 == tmp_5_reg_2565) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))))) begin
        p_src_data_stream_1_V_read = 1'b1;
    end else begin
        p_src_data_stream_1_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & ~(1'b0 == icmp_reg_2574) & ~(1'b0 == tmp_5_reg_2565)) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & (1'b0 == icmp_reg_2574)))) begin
        p_src_data_stream_2_V_blk_n = p_src_data_stream_2_V_empty_n;
    end else begin
        p_src_data_stream_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & (1'b0 == icmp_reg_2574) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & ~(1'b0 == icmp_reg_2574) & ~(1'b0 == tmp_5_reg_2565) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))))) begin
        p_src_data_stream_2_V_read = 1'b1;
    end else begin
        p_src_data_stream_2_V_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : begin
            if (~(ap_start == 1'b0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : begin
            if (~(1'b0 == tmp_4_fu_577_p2)) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        end
        ap_ST_st3_fsm_2 : begin
            if (~(1'b0 == exitcond1_fu_605_p2)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_3;
            end
        end
        ap_ST_pp0_stg0_fsm_3 : begin
            if ((~((1'b1 == ap_reg_ppiten_pp0_it5) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b1 == ap_reg_ppiten_pp0_it4)) & ~((1'b1 == ap_reg_ppiten_pp0_it2) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b1 == ap_reg_ppiten_pp0_it1) & ~(1'b1 == ap_reg_ppiten_pp0_it3)))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_3;
            end else if ((((1'b1 == ap_reg_ppiten_pp0_it5) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b1 == ap_reg_ppiten_pp0_it4)) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b1 == ap_reg_ppiten_pp0_it1) & ~(1'b1 == ap_reg_ppiten_pp0_it3)))) begin
                ap_NS_fsm = ap_ST_st10_fsm_4;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_3;
            end
        end
        ap_ST_st10_fsm_4 : begin
            ap_NS_fsm = ap_ST_st3_fsm_2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ImagLoc_x_cast_fu_957_p1 = $signed(ImagLoc_x_fu_951_p2);

assign ImagLoc_x_fu_951_p2 = ($signed(ap_const_lv12_FFF) + $signed(p_027_0_i_cast_fu_919_p1));

assign OP1_V_0_0_2_cast_fu_1676_p1 = src_kernel_win_0_val_2_0_reg_2731;

assign OP1_V_1_0_2_cast_fu_1731_p1 = src_kernel_win_1_val_2_0_reg_2753;

assign OP1_V_2_0_2_cast_fu_1786_p1 = src_kernel_win_2_val_2_0_reg_2775;

assign OP2_V_0_0_1_cast_fu_586_p1 = $signed(p_kernel_val_0_V_1_read);

assign OP2_V_0_0_cast_fu_583_p1 = $signed(p_kernel_val_0_V_0_read);

assign OP2_V_0_1_2_cast_fu_589_p1 = $signed(p_kernel_val_1_V_2_read);

assign OP2_V_0_2_1_cast_fu_592_p1 = p_kernel_val_2_V_1_read;

assign OP2_V_0_2_2_cast_fu_595_p1 = $signed(p_kernel_val_2_V_2_read);

always @ (*) begin
    ap_sig_125 = (1'b1 == ap_CS_fsm[ap_const_lv32_1]);
end

always @ (*) begin
    ap_sig_150 = (1'b1 == ap_CS_fsm[ap_const_lv32_2]);
end

always @ (*) begin
    ap_sig_1607 = ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1));
end

always @ (*) begin
    ap_sig_1608 = ((1'b0 == icmp_reg_2574) & ~(1'b0 == tmp_128_0_1_reg_2583));
end

always @ (*) begin
    ap_sig_1610 = (~(1'b0 == icmp_reg_2574) & ~(1'b0 == tmp_5_reg_2565));
end

always @ (*) begin
    ap_sig_1613 = ((1'b0 == icmp_reg_2574) & ~(1'b0 == tmp_6_reg_2579));
end

always @ (*) begin
    ap_sig_180 = (1'b1 == ap_CS_fsm[ap_const_lv32_3]);
end

always @ (*) begin
    ap_sig_196 = (((ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & (1'b0 == icmp_reg_2574) & (p_src_data_stream_0_V_empty_n == 1'b0)) | ((ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & ~(1'b0 == icmp_reg_2574) & ~(1'b0 == tmp_5_reg_2565) & (p_src_data_stream_0_V_empty_n == 1'b0)) | ((ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & (1'b0 == icmp_reg_2574) & (p_src_data_stream_1_V_empty_n == 1'b0)) | ((ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & ~(1'b0 == icmp_reg_2574) & ~(1'b0 == tmp_5_reg_2565) & (p_src_data_stream_1_V_empty_n == 1'b0)) | ((ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & (1'b0 == icmp_reg_2574) & (p_src_data_stream_2_V_empty_n == 1'b0)) | ((ap_reg_ppstg_exitcond_reg_2625_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2634_pp0_iter1) & ~(1'b0 == icmp_reg_2574) & ~(1'b0 == tmp_5_reg_2565) & (p_src_data_stream_2_V_empty_n == 1'b0)));
end

always @ (*) begin
    ap_sig_206 = ((~(1'b0 == ap_reg_ppstg_or_cond_i_reg_2661_pp0_iter4) & (p_dst_data_stream_0_V_full_n == 1'b0)) | (~(1'b0 == ap_reg_ppstg_or_cond_i_reg_2661_pp0_iter4) & (p_dst_data_stream_1_V_full_n == 1'b0)) | (~(1'b0 == ap_reg_ppstg_or_cond_i_reg_2661_pp0_iter4) & (p_dst_data_stream_2_V_full_n == 1'b0)));
end

always @ (*) begin
    ap_sig_22 = (ap_CS_fsm[ap_const_lv32_0] == 1'b1);
end

always @ (*) begin
    ap_sig_441 = (1'b1 == ap_CS_fsm[ap_const_lv32_4]);
end

assign brmerge_fu_1071_p2 = (tmp_82_not_reg_2569 | tmp_16_fu_975_p2);

assign col_assign_3_0_t_fu_1124_p2 = (ap_reg_ppstg_tmp_83_reg_2643_pp0_iter1 ^ ap_const_lv2_3);

assign col_buf_0_val_0_0_fu_1141_p3 = ((ap_reg_ppstg_brmerge_reg_2648_pp0_iter1[0:0] === 1'b1) ? k_buf_0_val_3_q0 : tmp_19_fu_1129_p5);

assign col_buf_0_val_1_0_fu_1160_p3 = ((ap_reg_ppstg_brmerge_reg_2648_pp0_iter1[0:0] === 1'b1) ? k_buf_0_val_4_q0 : tmp_20_fu_1148_p5);

assign col_buf_0_val_2_0_fu_1179_p3 = ((ap_reg_ppstg_brmerge_reg_2648_pp0_iter1[0:0] === 1'b1) ? k_buf_0_val_5_q0 : tmp_21_fu_1167_p5);

assign col_buf_1_val_0_0_fu_1321_p3 = ((ap_reg_ppstg_brmerge_reg_2648_pp0_iter1[0:0] === 1'b1) ? k_buf_1_val_3_q0 : tmp_27_fu_1309_p5);

assign col_buf_1_val_1_0_fu_1340_p3 = ((ap_reg_ppstg_brmerge_reg_2648_pp0_iter1[0:0] === 1'b1) ? k_buf_1_val_4_q0 : tmp_28_fu_1328_p5);

assign col_buf_1_val_2_0_fu_1359_p3 = ((ap_reg_ppstg_brmerge_reg_2648_pp0_iter1[0:0] === 1'b1) ? k_buf_1_val_5_q0 : tmp_29_fu_1347_p5);

assign col_buf_2_val_0_0_fu_1492_p3 = ((ap_reg_ppstg_brmerge_reg_2648_pp0_iter1[0:0] === 1'b1) ? k_buf_2_val_3_q0 : tmp_35_fu_1480_p5);

assign col_buf_2_val_1_0_fu_1511_p3 = ((ap_reg_ppstg_brmerge_reg_2648_pp0_iter1[0:0] === 1'b1) ? k_buf_2_val_4_q0 : tmp_36_fu_1499_p5);

assign col_buf_2_val_2_0_fu_1530_p3 = ((ap_reg_ppstg_brmerge_reg_2648_pp0_iter1[0:0] === 1'b1) ? k_buf_2_val_5_q0 : tmp_37_fu_1518_p5);

assign exitcond1_fu_605_p2 = ((p_014_0_i_reg_549 == ap_const_lv11_43A) ? 1'b1 : 1'b0);

assign exitcond_fu_923_p2 = ((p_027_0_i_reg_560 == ap_const_lv11_782) ? 1'b1 : 1'b0);

assign grp_fu_2134_p0 = OP2_V_0_1_2_cast_reg_2528;

assign grp_fu_2134_p1 = grp_fu_2134_p10;

assign grp_fu_2134_p10 = ap_reg_ppstg_src_kernel_win_1_val_1_0_reg_2747_pp0_iter3;

assign grp_fu_2142_p0 = OP2_V_0_0_cast_reg_2514;

assign grp_fu_2142_p1 = grp_fu_2142_p10;

assign grp_fu_2142_p10 = src_kernel_win_2_val_2_1_1_fu_246;

assign grp_fu_2150_p0 = tmp_s_reg_2549;

assign grp_fu_2150_p1 = grp_fu_2150_p10;

assign grp_fu_2150_p10 = src_kernel_win_0_val_1_1_1_fu_190;

assign grp_fu_2150_p2 = ($signed(tmp_172_0_0_2_cast_cast_fu_1685_p1) + $signed(grp_fu_2240_p3));

assign grp_fu_2157_p0 = OP2_V_0_1_2_cast_reg_2528;

assign grp_fu_2157_p1 = grp_fu_2157_p10;

assign grp_fu_2157_p10 = ap_reg_ppstg_src_kernel_win_2_val_1_0_reg_2769_pp0_iter3;

assign grp_fu_2165_p0 = tmp_s_reg_2549;

assign grp_fu_2165_p1 = grp_fu_2165_p10;

assign grp_fu_2165_p10 = src_kernel_win_2_val_1_1_1_fu_238;

assign grp_fu_2165_p2 = ($signed(tmp_172_2_0_2_cast_cast_fu_1795_p1) + $signed(grp_fu_2142_p3));

assign grp_fu_2172_p0 = OP2_V_0_2_1_cast_reg_2535;

assign grp_fu_2172_p1 = grp_fu_2172_p10;

assign grp_fu_2172_p10 = src_kernel_win_1_val_0_1_fu_202;

assign grp_fu_2179_p0 = OP2_V_0_2_1_cast_reg_2535;

assign grp_fu_2179_p1 = grp_fu_2179_p10;

assign grp_fu_2179_p10 = src_kernel_win_0_val_0_1_fu_178;

assign grp_fu_2186_p0 = tmp_s_reg_2549;

assign grp_fu_2186_p1 = grp_fu_2186_p10;

assign grp_fu_2186_p10 = src_kernel_win_1_val_1_1_1_fu_214;

assign grp_fu_2186_p2 = ($signed(tmp_172_1_0_2_cast_cast_fu_1740_p1) + $signed(grp_fu_2193_p3));

assign grp_fu_2193_p0 = OP2_V_0_0_cast_reg_2514;

assign grp_fu_2193_p1 = grp_fu_2193_p10;

assign grp_fu_2193_p10 = src_kernel_win_1_val_2_1_1_fu_222;

assign grp_fu_2201_p0 = OP2_V_0_2_2_cast_reg_2542;

assign grp_fu_2201_p1 = grp_fu_2201_p10;

assign grp_fu_2201_p10 = src_kernel_win_2_val_0_0_reg_2763;

assign grp_fu_2201_p2 = grp_fu_2201_p20;

assign grp_fu_2201_p20 = src_kernel_win_2_val_0_1_1_fu_230;

assign grp_fu_2209_p0 = OP2_V_0_2_2_cast_reg_2542;

assign grp_fu_2209_p1 = grp_fu_2209_p10;

assign grp_fu_2209_p10 = src_kernel_win_0_val_0_0_reg_2719;

assign grp_fu_2209_p2 = grp_fu_2209_p20;

assign grp_fu_2209_p20 = src_kernel_win_0_val_0_1_1_fu_182;

assign grp_fu_2217_p0 = OP2_V_0_2_1_cast_reg_2535;

assign grp_fu_2217_p1 = grp_fu_2217_p10;

assign grp_fu_2217_p10 = src_kernel_win_2_val_0_1_fu_226;

assign grp_fu_2224_p0 = OP2_V_0_2_2_cast_reg_2542;

assign grp_fu_2224_p1 = grp_fu_2224_p10;

assign grp_fu_2224_p10 = src_kernel_win_1_val_0_0_reg_2741;

assign grp_fu_2224_p2 = grp_fu_2224_p20;

assign grp_fu_2224_p20 = src_kernel_win_1_val_0_1_1_fu_206;

assign grp_fu_2232_p0 = OP2_V_0_1_2_cast_reg_2528;

assign grp_fu_2232_p1 = grp_fu_2232_p10;

assign grp_fu_2232_p10 = ap_reg_ppstg_src_kernel_win_0_val_1_0_reg_2725_pp0_iter3;

assign grp_fu_2240_p0 = OP2_V_0_0_cast_reg_2514;

assign grp_fu_2240_p1 = grp_fu_2240_p10;

assign grp_fu_2240_p10 = src_kernel_win_0_val_2_1_1_fu_198;

assign i_V_fu_611_p2 = (p_014_0_i_reg_549 + ap_const_lv11_1);

assign icmp1_fu_945_p2 = ((tmp_80_fu_935_p4 != ap_const_lv10_0) ? 1'b1 : 1'b0);

assign icmp_fu_639_p2 = ((tmp_fu_629_p4 != ap_const_lv10_0) ? 1'b1 : 1'b0);

assign isneg_1_fu_1996_p3 = p_Val2_4_fu_1991_p2[ap_const_lv32_B];

assign isneg_2_fu_2072_p3 = p_Val2_s_113_fu_2067_p2[ap_const_lv32_B];

assign isneg_fu_1920_p3 = p_Val2_1_111_fu_1915_p2[ap_const_lv32_B];

assign j_V_fu_929_p2 = (p_027_0_i_reg_560 + ap_const_lv11_1);

assign k_buf_0_val_3_address0 = tmp_18_fu_1084_p1;

assign k_buf_0_val_4_address0 = tmp_18_fu_1084_p1;

assign k_buf_0_val_5_address0 = tmp_18_fu_1084_p1;

assign k_buf_1_val_3_address0 = tmp_18_fu_1084_p1;

assign k_buf_1_val_4_address0 = tmp_18_fu_1084_p1;

assign k_buf_1_val_5_address0 = tmp_18_fu_1084_p1;

assign k_buf_2_val_3_address0 = tmp_18_fu_1084_p1;

assign k_buf_2_val_4_address0 = tmp_18_fu_1084_p1;

assign k_buf_2_val_5_address0 = tmp_18_fu_1084_p1;

assign not_i_i_i1_fu_2100_p2 = ((tmp_42_fu_2084_p4 != ap_const_lv4_0) ? 1'b1 : 1'b0);

assign not_i_i_i5_fu_2024_p2 = ((tmp_34_fu_2008_p4 != ap_const_lv4_0) ? 1'b1 : 1'b0);

assign not_i_i_i_fu_1948_p2 = ((tmp_26_fu_1932_p4 != ap_const_lv4_0) ? 1'b1 : 1'b0);

assign or_cond_i423_i_fu_689_p2 = (tmp_9_fu_683_p2 & rev_fu_677_p2);

assign or_cond_i_fu_1076_p2 = (icmp_reg_2574 & icmp1_fu_945_p2);

assign or_cond_i_i_fu_981_p2 = (tmp_16_fu_975_p2 & rev1_fu_969_p2);

assign overflow_1_fu_2030_p2 = (not_i_i_i5_fu_2024_p2 & tmp_i_i4_fu_2018_p2);

assign overflow_2_fu_2106_p2 = (not_i_i_i1_fu_2100_p2 & tmp_i_i1_fu_2094_p2);

assign overflow_fu_1954_p2 = (not_i_i_i_fu_1948_p2 & tmp_i_i_fu_1942_p2);

assign p_014_0_i_cast_fu_601_p1 = p_014_0_i_reg_549;

assign p_027_0_i_cast_fu_919_p1 = p_027_0_i_reg_560;

assign p_Val2_0_0_1_fu_1286_p0 = OP2_V_0_0_1_cast_reg_2521;

assign p_Val2_0_0_1_fu_1286_p1 = p_Val2_0_0_1_fu_1286_p10;

assign p_Val2_0_0_1_fu_1286_p10 = src_kernel_win_0_val_2_1_fu_194;

assign p_Val2_0_0_1_fu_1286_p2 = ($signed(p_Val2_0_0_1_fu_1286_p0) * $signed({{1'b0}, {p_Val2_0_0_1_fu_1286_p1}}));

assign p_Val2_0_0_2_fu_1679_p2 = (ap_const_lv9_0 - OP1_V_0_0_2_cast_fu_1676_p1);

assign p_Val2_10_fu_2004_p1 = p_Val2_4_fu_1991_p2[7:0];

assign p_Val2_11_fu_2080_p1 = p_Val2_s_113_fu_2067_p2[7:0];

assign p_Val2_12_fu_1974_p3 = ((tmp_i_i_112_fu_1968_p2[0:0] === 1'b1) ? p_mux_i_i_cast_fu_1960_p3 : p_Val2_9_fu_1928_p1);

assign p_Val2_13_fu_2050_p3 = ((tmp_i_i8_fu_2044_p2[0:0] === 1'b1) ? p_mux_i_i7_cast_fu_2036_p3 : p_Val2_10_fu_2004_p1);

assign p_Val2_14_fu_2126_p3 = ((tmp_i_i1_114_fu_2120_p2[0:0] === 1'b1) ? p_mux_i_i16_cast_fu_2112_p3 : p_Val2_11_fu_2080_p1);

assign p_Val2_1_0_1_fu_1466_p0 = OP2_V_0_0_1_cast_reg_2521;

assign p_Val2_1_0_1_fu_1466_p1 = p_Val2_1_0_1_fu_1466_p10;

assign p_Val2_1_0_1_fu_1466_p10 = src_kernel_win_1_val_2_1_fu_218;

assign p_Val2_1_0_1_fu_1466_p2 = ($signed(p_Val2_1_0_1_fu_1466_p0) * $signed({{1'b0}, {p_Val2_1_0_1_fu_1466_p1}}));

assign p_Val2_1_0_2_fu_1734_p2 = (ap_const_lv9_0 - OP1_V_1_0_2_cast_fu_1731_p1);

assign p_Val2_1_111_fu_1915_p2 = ($signed(grp_fu_2232_p3) + $signed(tmp3_cast_fu_1912_p1));

assign p_Val2_2_0_1_fu_1628_p0 = OP2_V_0_0_1_cast_reg_2521;

assign p_Val2_2_0_1_fu_1628_p1 = p_Val2_2_0_1_fu_1628_p10;

assign p_Val2_2_0_1_fu_1628_p10 = src_kernel_win_2_val_2_1_fu_242;

assign p_Val2_2_0_1_fu_1628_p2 = ($signed(p_Val2_2_0_1_fu_1628_p0) * $signed({{1'b0}, {p_Val2_2_0_1_fu_1628_p1}}));

assign p_Val2_2_0_2_fu_1789_p2 = (ap_const_lv9_0 - OP1_V_2_0_2_cast_fu_1786_p1);

assign p_Val2_4_fu_1991_p2 = ($signed(grp_fu_2134_p3) + $signed(tmp8_cast_fu_1988_p1));

assign p_Val2_9_fu_1928_p1 = p_Val2_1_111_fu_1915_p2[7:0];

assign p_Val2_s_113_fu_2067_p2 = ($signed(grp_fu_2157_p3) + $signed(tmp13_cast_fu_2064_p1));

assign p_assign_1_fu_995_p2 = (ap_const_lv12_1 - p_027_0_i_cast_fu_919_p1);

assign p_assign_2_cast_fu_1029_p1 = p_assign_2_fu_1023_p2;

assign p_assign_2_fu_1023_p2 = ($signed(ap_const_lv13_EFE) - $signed(p_p2_i_i_cast_cast_fu_1013_p1));

assign p_assign_6_0_1_fu_729_p2 = ($signed(p_014_0_i_cast_fu_601_p1) + $signed(ap_const_lv12_FFE));

assign p_assign_6_0_2_fu_755_p2 = ($signed(p_014_0_i_cast_fu_601_p1) + $signed(ap_const_lv12_FFD));

assign p_assign_7_fu_703_p2 = (ap_const_lv12_1 - p_014_0_i_cast_fu_601_p1);

assign p_assign_8_fu_723_p2 = ($signed(ap_const_lv12_86E) - $signed(p_p2_i424_i_fu_709_p3));

assign p_dst_data_stream_0_V_din = p_Val2_12_reg_2830;

assign p_dst_data_stream_1_V_din = p_Val2_13_reg_2835;

assign p_dst_data_stream_2_V_din = p_Val2_14_reg_2840;

assign p_mux_i_i16_cast_fu_2112_p3 = ((tmp_i_i1_fu_2094_p2[0:0] === 1'b1) ? ap_const_lv8_FF : ap_const_lv8_0);

assign p_mux_i_i7_cast_fu_2036_p3 = ((tmp_i_i4_fu_2018_p2[0:0] === 1'b1) ? ap_const_lv8_FF : ap_const_lv8_0);

assign p_mux_i_i_cast_fu_1960_p3 = ((tmp_i_i_fu_1942_p2[0:0] === 1'b1) ? ap_const_lv8_FF : ap_const_lv8_0);

assign p_p2_i424_i_fu_709_p3 = ((tmp_56_fu_695_p3[0:0] === 1'b1) ? p_assign_7_fu_703_p2 : tmp_8_fu_663_p2);

assign p_p2_i_i_cast_cast_fu_1013_p1 = $signed(p_p2_i_i_fu_1001_p3);

assign p_p2_i_i_cast_fu_1009_p1 = $signed(p_p2_i_i_fu_1001_p3);

assign p_p2_i_i_fu_1001_p3 = ((tmp_82_fu_987_p3[0:0] === 1'b1) ? p_assign_1_fu_995_p2 : ImagLoc_x_fu_951_p2);

assign rev1_fu_969_p2 = (tmp_81_fu_961_p3 ^ 1'b1);

assign rev_fu_677_p2 = (tmp_55_fu_669_p3 ^ 1'b1);

assign row_assign_10_0_1_t_fu_845_p2 = (tmp_11_fu_837_p3 ^ ap_const_lv2_3);

assign row_assign_10_0_2_t_fu_877_p2 = (tmp_12_fu_869_p3 ^ ap_const_lv2_3);

assign row_assign_10_1_0_t_fu_913_p2 = (tmp_14_fu_905_p3 ^ ap_const_lv2_3);

assign row_assign_s_fu_813_p2 = (tmp_70_fu_805_p3 ^ ap_const_lv2_3);

assign sel_tmp1_fu_1047_p2 = (tmp_81_fu_961_p3 | tmp_21_not_fu_1041_p2);

assign sel_tmp2_fu_1053_p2 = (tmp_17_fu_1017_p2 & sel_tmp1_fu_1047_p2);

assign sel_tmp_fu_1033_p3 = ((or_cond_i_i_fu_981_p2[0:0] === 1'b1) ? ImagLoc_x_cast_fu_957_p1 : p_assign_2_cast_fu_1029_p1);

assign src_kernel_win_0_val_0_0_fu_1236_p3 = ((tmp_7_reg_2587[0:0] === 1'b1) ? tmp_22_fu_1225_p5 : col_buf_0_val_0_0_fu_1141_p3);

assign src_kernel_win_0_val_1_0_fu_1254_p3 = ((tmp_7_reg_2587[0:0] === 1'b1) ? tmp_23_fu_1243_p5 : col_buf_0_val_1_0_fu_1160_p3);

assign src_kernel_win_0_val_2_0_fu_1272_p3 = ((tmp_7_reg_2587[0:0] === 1'b1) ? tmp_24_fu_1261_p5 : col_buf_0_val_2_0_fu_1179_p3);

assign src_kernel_win_1_val_0_0_fu_1416_p3 = ((tmp_7_reg_2587[0:0] === 1'b1) ? tmp_30_fu_1405_p5 : col_buf_1_val_0_0_fu_1321_p3);

assign src_kernel_win_1_val_1_0_fu_1434_p3 = ((tmp_7_reg_2587[0:0] === 1'b1) ? tmp_31_fu_1423_p5 : col_buf_1_val_1_0_fu_1340_p3);

assign src_kernel_win_1_val_2_0_fu_1452_p3 = ((tmp_7_reg_2587[0:0] === 1'b1) ? tmp_32_fu_1441_p5 : col_buf_1_val_2_0_fu_1359_p3);

assign src_kernel_win_2_val_0_0_fu_1578_p3 = ((tmp_7_reg_2587[0:0] === 1'b1) ? tmp_38_fu_1567_p5 : col_buf_2_val_0_0_fu_1492_p3);

assign src_kernel_win_2_val_1_0_fu_1596_p3 = ((tmp_7_reg_2587[0:0] === 1'b1) ? tmp_39_fu_1585_p5 : col_buf_2_val_1_0_fu_1511_p3);

assign src_kernel_win_2_val_2_0_fu_1614_p3 = ((tmp_7_reg_2587[0:0] === 1'b1) ? tmp_40_fu_1603_p5 : col_buf_2_val_2_0_fu_1530_p3);

assign tmp13_cast_fu_2064_p1 = tmp13_reg_2825;

assign tmp3_cast_fu_1912_p1 = tmp3_reg_2805;

assign tmp8_cast_fu_1988_p1 = tmp8_reg_2815;

assign tmp_10_fu_717_p2 = (($signed(p_p2_i424_i_fu_709_p3) < $signed(12'b10000111000)) ? 1'b1 : 1'b0);

assign tmp_11_fu_837_p3 = ((tmp_58_fu_735_p3[0:0] === 1'b1) ? tmp_73_fu_829_p3 : tmp_71_fu_819_p1);

assign tmp_128_0_1_fu_651_p2 = ((p_014_0_i_reg_549 == ap_const_lv11_0) ? 1'b1 : 1'b0);

assign tmp_12_fu_869_p3 = ((tmp_62_fu_761_p3[0:0] === 1'b1) ? tmp_76_fu_861_p3 : tmp_74_fu_851_p1);

assign tmp_13_fu_897_p3 = ((tmp_10_fu_717_p2[0:0] === 1'b1) ? tmp_78_fu_887_p1 : tmp_79_fu_891_p2);

assign tmp_14_fu_905_p3 = ((or_cond_i423_i_fu_689_p2[0:0] === 1'b1) ? tmp_77_fu_883_p1 : tmp_13_fu_897_p3);

assign tmp_16_fu_975_p2 = (($signed(ImagLoc_x_fu_951_p2) < $signed(12'b11110000000)) ? 1'b1 : 1'b0);

assign tmp_172_0_0_2_cast_cast_fu_1685_p1 = $signed(p_Val2_0_0_2_fu_1679_p2);

assign tmp_172_1_0_2_cast_cast_fu_1740_p1 = $signed(p_Val2_1_0_2_fu_1734_p2);

assign tmp_172_2_0_2_cast_cast_fu_1795_p1 = $signed(p_Val2_2_0_2_fu_1789_p2);

assign tmp_17_fu_1017_p2 = (($signed(p_p2_i_i_fu_1001_p3) < $signed(12'b11110000000)) ? 1'b1 : 1'b0);

assign tmp_18_fu_1084_p1 = $unsigned(x_cast_fu_1081_p1);

assign tmp_21_not_fu_1041_p2 = (tmp_16_fu_975_p2 ^ 1'b1);

assign tmp_26_fu_1932_p4 = {{p_Val2_1_111_fu_1915_p2[ap_const_lv32_B : ap_const_lv32_8]}};

assign tmp_34_fu_2008_p4 = {{p_Val2_4_fu_1991_p2[ap_const_lv32_B : ap_const_lv32_8]}};

assign tmp_3_fu_571_p2 = (tmp_2_reg_538 + ap_const_lv2_1);

assign tmp_42_fu_2084_p4 = {{p_Val2_s_113_fu_2067_p2[ap_const_lv32_B : ap_const_lv32_8]}};

assign tmp_4_fu_577_p2 = ((tmp_2_reg_538 == ap_const_lv2_2) ? 1'b1 : 1'b0);

assign tmp_55_fu_669_p3 = tmp_8_fu_663_p2[ap_const_lv32_B];

assign tmp_56_fu_695_p3 = tmp_8_fu_663_p2[ap_const_lv32_B];

assign tmp_58_fu_735_p3 = p_assign_6_0_1_fu_729_p2[ap_const_lv32_B];

assign tmp_59_fu_743_p3 = p_assign_6_0_1_fu_729_p2[ap_const_lv32_B];

assign tmp_5_fu_617_p2 = ((p_014_0_i_reg_549 < ap_const_lv11_438) ? 1'b1 : 1'b0);

assign tmp_60_fu_751_p1 = p_014_0_i_reg_549[1:0];

assign tmp_62_fu_761_p3 = p_assign_6_0_2_fu_755_p2[ap_const_lv32_B];

assign tmp_63_fu_769_p3 = p_assign_6_0_2_fu_755_p2[ap_const_lv32_B];

assign tmp_64_fu_777_p1 = p_014_0_i_reg_549[1:0];

assign tmp_65_fu_781_p1 = p_p2_i424_i_fu_709_p3[1:0];

assign tmp_66_fu_785_p1 = tmp_8_fu_663_p2[1:0];

assign tmp_67_fu_789_p1 = p_p2_i424_i_fu_709_p3[1:0];

assign tmp_68_fu_793_p1 = p_assign_8_fu_723_p2[1:0];

assign tmp_69_fu_797_p3 = ((tmp_10_fu_717_p2[0:0] === 1'b1) ? tmp_67_fu_789_p1 : tmp_68_fu_793_p1);

assign tmp_6_fu_645_p2 = ((p_014_0_i_reg_549 == ap_const_lv11_1) ? 1'b1 : 1'b0);

assign tmp_70_fu_805_p3 = ((or_cond_i423_i_fu_689_p2[0:0] === 1'b1) ? tmp_66_fu_785_p1 : tmp_69_fu_797_p3);

assign tmp_71_fu_819_p1 = p_assign_6_0_1_fu_729_p2[1:0];

assign tmp_72_fu_823_p2 = ($signed(ap_const_lv2_2) - $signed(tmp_60_fu_751_p1));

assign tmp_73_fu_829_p3 = ((tmp_59_fu_743_p3[0:0] === 1'b1) ? tmp_72_fu_823_p2 : tmp_71_fu_819_p1);

assign tmp_74_fu_851_p1 = p_assign_6_0_2_fu_755_p2[1:0];

assign tmp_75_fu_855_p2 = (tmp_64_fu_777_p1 ^ ap_const_lv2_3);

assign tmp_76_fu_861_p3 = ((tmp_63_fu_769_p3[0:0] === 1'b1) ? tmp_75_fu_855_p2 : tmp_74_fu_851_p1);

assign tmp_77_fu_883_p1 = tmp_8_fu_663_p2[1:0];

assign tmp_78_fu_887_p1 = p_p2_i424_i_fu_709_p3[1:0];

assign tmp_79_fu_891_p2 = ($signed(ap_const_lv2_2) - $signed(tmp_65_fu_781_p1));

assign tmp_7_fu_657_p2 = ((p_014_0_i_reg_549 > ap_const_lv11_438) ? 1'b1 : 1'b0);

assign tmp_80_fu_935_p4 = {{p_027_0_i_reg_560[ap_const_lv32_A : ap_const_lv32_1]}};

assign tmp_81_fu_961_p3 = ImagLoc_x_fu_951_p2[ap_const_lv32_B];

assign tmp_82_fu_987_p3 = ImagLoc_x_fu_951_p2[ap_const_lv32_B];

assign tmp_82_not_fu_623_p2 = ((p_014_0_i_reg_549 > ap_const_lv11_437) ? 1'b1 : 1'b0);

assign tmp_83_fu_1067_p1 = x_fu_1059_p3[1:0];

assign tmp_8_fu_663_p2 = ($signed(p_014_0_i_cast_fu_601_p1) + $signed(ap_const_lv12_FFF));

assign tmp_9_fu_683_p2 = (($signed(tmp_8_fu_663_p2) < $signed(12'b10000111000)) ? 1'b1 : 1'b0);

assign tmp_fu_629_p4 = {{p_014_0_i_reg_549[ap_const_lv32_A : ap_const_lv32_1]}};

assign tmp_i_i1_114_fu_2120_p2 = (isneg_2_fu_2072_p3 | overflow_2_fu_2106_p2);

assign tmp_i_i1_fu_2094_p2 = (isneg_2_fu_2072_p3 ^ 1'b1);

assign tmp_i_i4_fu_2018_p2 = (isneg_1_fu_1996_p3 ^ 1'b1);

assign tmp_i_i8_fu_2044_p2 = (isneg_1_fu_1996_p3 | overflow_1_fu_2030_p2);

assign tmp_i_i_112_fu_1968_p2 = (isneg_fu_1920_p3 | overflow_fu_1954_p2);

assign tmp_i_i_fu_1942_p2 = (isneg_fu_1920_p3 ^ 1'b1);

assign tmp_s_fu_598_p1 = p_kernel_val_1_V_0_read;

assign x_cast_fu_1081_p1 = $signed(x_reg_2638);

assign x_fu_1059_p3 = ((sel_tmp2_fu_1053_p2[0:0] === 1'b1) ? p_p2_i_i_cast_fu_1009_p1 : sel_tmp_fu_1033_p3);

always @ (posedge ap_clk) begin
    OP2_V_0_2_1_cast_reg_2535[10:3] <= 8'b00000000;
    tmp_s_reg_2549[10:4] <= 7'b0000000;
end

endmodule //filter_Filter2D
